### ISSUE TITLE
Monogame chipset problem

### ISSUE THREAD

**Issue by praemix** [MonoGame/MonoGame#6479] opened 2018-10-05 07:37 UTC
Hello ! 

I'm user of monogame on window 10 but i have problem !

I have a chipset (intel hd 2000) that does not support OpenGL 3.0 on Windows 10: /

I do not really want to downgrade to Window 8 or 7, however, if I create a simple Windows Monogame project, it works!

I do not understand why

**Comment by cra0zy** [comment] 2018-10-05 08:35
MonoGame DesktopGL project uses OpenGL and requires OpenGL 3.0 or newer
MonoGame Windows project uses DirectX, and requires DirectX 9.

As this is neither a bug report nor a feature request I am gonna close this issue.

**Closed by cra0zy** 2018-10-05 08:35 UTC

**Comment by mrhelmut** [comment] 2018-10-05 08:42
Please refer to this discussion to understand why it's not a bug and can't be fixed: #6414
