### ISSUE TITLE
SpriteFonts failing to load (iOS)

### ISSUE THREAD

**Issue by Lofionic** [MonoGame/MonoGame#7868] opened 2022-07-28 00:34 UTC
SpriteFonts failing to load in iOS:

`File.spriteFont` is default SpriteFont file generated by MGCB editor.

`Content.mgcb` entry:
```
#begin File.spritefont
/importer:FontDescriptionImporter
/processor:FontDescriptionProcessor
/processorParam:PremultiplyAlpha=True
/processorParam:TextureFormat=Compressed
/build:File.spritefont
```

Call:
`SpriteFont foo = Content.Load<SpriteFont>("File");`

Error:
`"Could not find ContentTypeReader Type. Please ensure the name of the Assembly that contains the Type matches the assembly in the full type name: Microsoft.Xna.Framework.Content.ListReader`

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.1.303

#### What operating system are you using:
- MacOS 12.4 / M1 / VS2022 

#### What MonoGame platform are you using:

- iOS

**Comment by mrhelmut** [comment] 2022-07-28 06:45
This is a reflection issue when using AOT compilation, you might want to disable trimming and/or assembly-level linking, or configuring the trimmer to not trim ```Microsoft.Xna.Framework.Content.ListReader``` (and likely other Reader types).

**Comment by corykroll** [comment] 2022-11-13 00:42
I've been digging through this one, and for me, the issue was in ContentTypeReaderManager.cs
When deploying to a physical iPhone for testing, this line of code is an issue:

`private static readonly bool _isRunningOnNetCore = Type.GetType("System.Private.CoreLib") != null;`

It does not work correctly.  Changing it to:

`private static readonly bool _isRunningOnNetCore = true;`

Does the trick.  This is because later on, if _isRunningOnNetCore is incorrect, mscorlib is attempted to be loaded, fails, and the app crashes.

Ultimately detecting if running on NET Core is something I'm trying to code a fix for.  I'm thinking a quick method to parse the string of RuntimeInformation.FrameworkDescription might do the trick.

**Comment by mrhelmut** [comment] 2023-12-16 10:13
Duplicate of #7872

**Closed by mrhelmut** 2023-12-16 10:13 UTC
