### ISSUE TITLE
Keyboard is up doesnt seem to work properly...

### ISSUE THREAD

**Issue by wardPlaced** [MonoGame/MonoGame#7216] opened 2020-06-21 13:32 UTC
Hi,

I did not check if this issue is appearent in the development branch, but suffice to say, the thing I encounterd was weird.

So, I programmed a shooter where you controll a space ship and i tried to have the game play a sound effect when shooting, I needed to figure out a process so the sound wouldnt play at full speed allways, only when I pressed the controller a button or the space bar, the ship is controllable with the arrow keys and wasd.

Now, I made it so that boolean variables would detect when the player lifted the A button or the space bar and when it was pressed, so the sound wouldnt play over and over again, just from a light tap.

After tried to test my solution, which i implemented for controller as well as keyboard, which were identical, I must have came across a bug.

My solution worked for the Controller, but not for the keyboard, so this means there must be an issue in the underlying code or somehthing along those lines, so I thought it would be valuable to report my findings and maybe even get answers as to why it doesnt work for keyboard.

I have even made sure to reinstall monogame... I hope to resolve this issue and hope to here from someone soon!

Best whishes.

Sebastian

RAM 7.7 GB
Processor: Intel Core i5-2430M CPU @ 2.40GHz × 4
GNOME 3.34.2
64 bit OS
320 GB Harddrive

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7.1

#### What operating system are you using:
- Ubuntu 19.10

#### What MonoGame platform are you using:
- DesktopGL

Heres my Game1.cs!

﻿using System;
using System.Threading;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Audio;
using Microsoft.Xna.Framework.Graphics;
using Microsoft.Xna.Framework.Input;

namespace BattleshipGunner.Desktop
{
    /// <summary>
    /// This is the main type for your game.
    /// </summary>
    public class Game1 : Game
    {
        private GraphicsDeviceManager graphics;
        private SpriteBatch spriteBatch;
        private SpriteFont font;
        private Texture2D backdropScrolling;
        private Texture2D battleship;
        //private Texture2D bullet;
        private SoundEffect shoot;
        private SoundEffect supergoodshot;
        private int battleship_x = 0, battleship_y = 0;
        private int scrollingOver = -2350;
        private bool awesomeshot;
        private bool shotpaused;

        public Game1()
        {
            graphics = new GraphicsDeviceManager(this);
            Content.RootDirectory = "Content";
            graphics.PreferredBackBufferWidth = 450;
            graphics.PreferredBackBufferHeight = 650;
            awesomeshot = false;
            shotpaused = false;
        }

        private void shootPlay()
        {
            var i = supergoodshot.CreateInstance();
            i.Volume = 0.4f;
            if (awesomeshot)
            {
                if (shotpaused)
                {
                    i.Play();
                    awesomeshot = false;
                }
            }
           
        }

        /// <summary>
        /// Allows the game to perform any initialization it needs to before starting to run.
        /// This is where it can query for any required services and load any non-graphic
        /// related content.  Calling base.Initialize will enumerate through any components
        /// and initialize them as well.
        /// </summary>
        protected override void Initialize()
        {
            // TODO: Add your initialization logic here
            //bullet = new Texture2D(GraphicsDevice, 1, 1);
            //bullet.SetData(new[] { Color.White });
            base.Initialize();
        }

        /// <summary>
        /// LoadContent will be called once per game and is the place to load
        /// all of your content.
        /// </summary>
        protected override void LoadContent()
        {
            // Create a new SpriteBatch, which can be used to draw textures.
            spriteBatch = new SpriteBatch(GraphicsDevice);
            font = Content.Load<SpriteFont>("Assets/File");
            backdropScrolling = Content.Load<Texture2D>("Assets/backgroundSpaceShooter");
            battleship = Content.Load<Texture2D>("Assets/battleship1");
            shoot = Content.Load<SoundEffect>("Assets/machinegun");
            supergoodshot = Content.Load<SoundEffect>("Assets/supergoodshot");
            // TODO: use this.Content to load your game content here
        }

        /// <summary>
        /// UnloadContent will be called once per game and is the place to unload
        /// game-specific content.
        /// </summary>
        protected override void UnloadContent()
        {
            // TODO: Unload any non ContentManager content here
        }

        /// <summary>
        /// Allows the game to run logic such as updating the world,
        /// checking for collisions, gathering input, and playing audio.
        /// </summary>
        /// <param name="gameTime">Provides a snapshot of timing values.</param>
        protected override void Update(GameTime gameTime)
        {
            if (GamePad.GetState(PlayerIndex.One).Buttons.Back == ButtonState.Pressed || Keyboard.GetState().IsKeyDown(Keys.Escape))
                Exit();

            if (Keyboard.GetState().IsKeyDown(Keys.Space))
            {
                awesomeshot = true;
                shotpaused = false;
            }

            if (Keyboard.GetState().IsKeyUp(Keys.Space))
            {
                shotpaused = true;
            }

            if (GamePad.GetState(PlayerIndex.One).Buttons.A == ButtonState.Pressed)
            {
                awesomeshot = true;
                shotpaused = false;
            }

            if (GamePad.GetState(PlayerIndex.One).Buttons.A == ButtonState.Released)
            {
                shotpaused = true;
            }

            if (Keyboard.GetState().IsKeyDown(Keys.A) || Keyboard.GetState().IsKeyDown(Keys.Left))
            {
                battleship_x -= 1;
            }

            if (Keyboard.GetState().IsKeyDown(Keys.D) || Keyboard.GetState().IsKeyDown(Keys.Right))
            {
                battleship_x += 1;
            }

            if (Keyboard.GetState().IsKeyDown(Keys.W) || Keyboard.GetState().IsKeyDown(Keys.Up))
            {
                battleship_y -= 1;
            }

            if (Keyboard.GetState().IsKeyDown(Keys.S) || Keyboard.GetState().IsKeyDown(Keys.Down))
            {
                battleship_y += 1;
            }

            if (GamePad.GetState(PlayerIndex.One).DPad.Down == ButtonState.Pressed)
            {
                battleship_y += 1;
            }

            if (GamePad.GetState(PlayerIndex.One).DPad.Up == ButtonState.Pressed)
            {
                battleship_y -= 1;
            }

            if (GamePad.GetState(PlayerIndex.One).DPad.Left == ButtonState.Pressed)
            {
                battleship_x -= 1;
            }

            if (GamePad.GetState(PlayerIndex.One).DPad.Right == ButtonState.Pressed)
            {
                battleship_x += 1;
            }

            shootPlay();
            // TODO: Add your update logic here

            base.Update(gameTime);
        }

        /// <summary>
        /// This is called when the game should draw itself.
        /// </summary>
        /// <param name="gameTime">Provides a snapshot of timing values.</param>
        protected override void Draw(GameTime gameTime)
        {
            GraphicsDevice.Clear(Color.CornflowerBlue);

            // TODO: Add your drawing code here

            spriteBatch.Begin();
            spriteBatch.Draw(backdropScrolling, new Rectangle(0, scrollingOver, 450, 3000), Color.White);
            if (scrollingOver != 0)
            {
                scrollingOver++;
            }
            spriteBatch.Draw(battleship, new Rectangle(battleship_x, battleship_y, 43, 80), Color.White);
            
            spriteBatch.DrawString(font, "BattleshipGunner_v0.1", new Vector2(4f,626f), Color.White);
            spriteBatch.End();

            base.Draw(gameTime);
        }
    }
}

**Comment by wardPlaced** [comment] 2020-06-21 14:17
I dont know why it doubles my copied code like that, I can fix it by editing my comment...

**Comment by harry-cpp** [comment] 2020-06-21 14:56
Gonna close this as its not a bug report / feature request. You can ask questions like this on the community site: https://community.monogame.net

**Closed by harry-cpp** 2020-06-21 14:56 UTC
