### ISSUE TITLE
Touch Controller does not work on Windows 10 using Windows.GL package

### ISSUE THREAD

**Issue by xanto** [MonoGame/MonoGame#4383] opened 2016-01-04 17:25 UTC
Hi, 
in my project based on Monogame 3.4.0.459 I use TouchPanel class.

For example:

``` c#
protected override void Update(GameTime gameTime)   {

        graphics.ApplyChanges();

        TouchCollection touchCollection = TouchPanel.GetState();

        foreach (TouchLocation tl in touchCollection) {
                   //  ....(do something)... // 
        }
        base.Update(gameTime);
}
```

If I use Windows.DX package version everything works correctly, while using Windows.GL version TouchLocation  does not work because it does not capture touch action.

My OS for this test is Windows 10.

**Comment by tomspilman** [comment] 2016-01-04 19:12
> while using Windows.GL version TouchLocation does not work because it does not capture touch action.

That is expected....  WindowsGL or the new DesktopGL doesn't currently support any touch APIs.

While I know we could add support for Windows...  I have no clue what the state of touch APIs are on MacOS and Linux.

@cra0zy @dellis1972 ?

**Comment by dellis1972** [comment] 2016-01-04 19:24
MacOS is non existent

**Comment by cra0zy** [comment] 2016-01-04 19:24
Linux is non existent

OpenTK is no multitouch support

**Comment by tomspilman** [comment] 2016-01-04 19:34
Since the goal of DesktopGL is to have one binary that works basically the same across Windows, Mac, and Linux desktops...  it sounds like we shouldn't support touch at all under DesktopGL.

@xanto - Note DesktopGL replaces WindowsGL in MonoGame 3.5.

**Comment by cra0zy** [comment] 2016-01-04 19:44
> Since the goal of DesktopGL is to have one binary that works basically the same across Windows, Mac, and Linux desktops... it sounds like we shouldn't support touch at all under DesktopGL.

It's already not supported by WindowsGL or Linux.... also stop adding Mac, Mac is Xamarin.Mac and a whole other platform...

**Comment by tomspilman** [comment] 2016-01-04 19:51
> also stop adding Mac, Mac is Xamarin.Mac and a whole other platform...

What else should I call DesktopGL running on MacOS?

**Comment by cra0zy** [comment] 2016-01-04 20:02
> What else should I call DesktopGL running on MacOS?

I misread something in you last comment, sorry about that :(

**Comment by xanto** [comment] 2016-01-04 20:22
I got it. All clear. It was probably more understandable launch some exceptions during use. Something like "NotImplementedException" or "NotSupportedException"

**Comment by danzel** [comment] 2016-01-05 01:13
@xanto have you tried ```TouchPanel.GetCapabilities().IsConnected``` ?

Looks like it should return false
https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Input/Touch/TouchPanelCapabilities.cs#L75-L76

**Comment by xanto** [comment] 2016-01-05 10:26
In my case it returns true

**Comment by tomspilman** [comment] 2016-01-05 14:07
> In my case it returns true

It possibly does under the old WindowsGL.  It shouldn't under the new DesktopGL.

Anyway the consensus here is that for now we're not adding touch support to the OpenGL desktop platforms as Mac and Linux have no support for it.  This could change in the future if those platforms support touch on the desktop.

For now @xanto if you want touch support on the Windows desktop you need to use the Windows DirectX platform.  Or if you really want to hack MonoGame to move the existing touch API under WinForms to OpenTK, but I have no information on exactly how to do that.

**Comment by cra0zy** [comment] 2016-01-05 14:10
> Anyway the consensus here is that for now we're not adding touch support to the OpenGL desktop platforms as Mac and Linux have no support for it. This could change in the future if those platforms support touch on the desktop.

Just so there is no confusion for @xanto, on out side there is no support for touch events from DesktopGL WindowsGL, Linux or Mac. OpenTK(the backend which we are using for getting most of the stuff on these platforms) does support touch events on all 3 platforms, but it does not support multitouch last time I checked.

**Comment by xanto** [comment] 2016-01-05 14:19
OK. Thank you. 
I'm working on Directx platform now.

**Comment by tomspilman** [comment] 2016-01-05 14:40
> does support touch events on all 3 platforms, but it does not support multitouch 

It does?  I totally must have misread what you said before.

All MonoGame needs to touch events from the platform with an id that is consistent when a finger is touching.  The platform code just needs to call this:

https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Input/Touch/TouchPanelState.cs#L154

... and everything else will just work.

**Comment by cra0zy** [comment] 2018-10-02 19:41
Duplicate of: #6174

**Closed by cra0zy** 2018-10-02 19:41 UTC
