### ISSUE TITLE
Dis-aligned texel to draw position on dx.

### ISSUE THREAD

**Issue by willmotil** [MonoGame/MonoGame#6000] opened 2017-10-12 00:34 UTC
I hope someone can tell me this is not a actual card issue and that this is somehow a bug in monogame or sharp dx or something.  The pictures show it all especially the farthest one down.

There is a artifact in drawing a triangle on dx windows when a indexed skewed quad is drawn.

 The centroid or barycenter is being offset to far down when a entire quad is drawn on the z plane with no perspective mapping at all and non of the sides of the drawn triangles are at right angles e.g. they are skewed on two of the points or 1 per triangle. This appears that the interpolation mapping is then thrown off to the barycenter being somehow displaced to far down the y axis.

http://community.monogame.net/t/how-can-i-skew-a-sprite/9801/13

Nevermind i see whats wrong the problem is that the gpu is not actually compensating when a all the points of the quad have the same z depth.

**Comment by Jjagg** [comment] 2017-10-12 11:36
This is not a bug/issue...

**Comment by tomspilman** [comment] 2017-10-12 19:31
Yeah... this is just a misunderstanding of the math behind rendering.  There is no bug in MG, so i'm closing this.

**Closed by tomspilman** 2017-10-12 19:31 UTC
