### ISSUE TITLE
Xml To Xnb

### ISSUE THREAD

**Issue by tmanallen** [MonoGame/MonoGame#3186] opened 2014-11-19 23:33 UTC
If this is not an issue than forgive me but I have been trying to get this to work for the last week to no avail......but I have converted all my Xml's to Xnb's and for the life of me can't understand why when I import to a straight Monogame WinPhone 8 project they are being seen as non-content files, I have the set the properties and I have the latest build of Monogame. 

Thanks

**Comment by tgjones** [comment] 2015-02-16 14:32
@tmanallen Is this still an issue? Without more to go on (i.e. the exception message / stack trace that @tomspilman mentioned above), it's impossible to know what the problem is here.

**Comment by tmanallen** [comment] 2015-02-16 14:38
HI tgjones,
    yes sir it is, but I figured it out and was waiting to see if you guys could update this, I have a custom content processor and importer, I don't know how to make the monogame pipeline read it, so that is the issue that is plaguing me, any suggestions?

**Comment by tgjones** [comment] 2015-02-16 14:43
Do you mean the new content pipeline?

If so, and if you're using the Pipeline GUI tool, have a look at this page, specifically the "Custom Content Processors" section:
http://www.monogame.net/documentation/?page=Using_The_Pipeline_Tool

If you're not using the Pipeline GUI tool, then you can pass custom references on the command line to `mgcb.exe`.

**Comment by tmanallen** [comment] 2015-02-16 15:17
Ok, I see now, to test my theory I used the old XNA tutorial game Ninja academy and tried to build it in Mongame to make sure I wasn't missing anything, so like they have a custom content pipeline project for their animations I would need to call in the command line correct?

**Comment by tgjones** [comment] 2015-02-16 15:20
Apart from the docs I linked to above, there's a good article on CodeProject explaining how the new MonoGame Content Pipeline GUI tool works:
http://www.codeproject.com/Articles/854400/All-Hail-the-Old-and-the-New-The-MonoGame-Content

**Comment by tgjones** [comment] 2015-02-16 15:21
(For general help, use the [MonoGame community forums](http://community.monogame.net) - you'll probably get a wider range of helpful responses there.)

**Comment by tomspilman** [comment] 2015-03-17 14:54
@tmanallen - FYI.  The second part of our MVA presentation happens next week...

http://www.microsoftvirtualacademy.com/liveevents/advanced-monogame-for-windows-phone-and-windows-store-games

In it I walk thru how to write pipeline extensions for MonoGame.  If you don't watch it live a recording will be up shortly after.

**Comment by Alturos** [comment] 2015-08-18 06:27
I had run into this exact issue when working on a PSM port and hacked my way around it. Now that I'm trying to port from XNA to MonoGame, I stumbled over it again, and decided to look into it for real.

If you've setup the Content build tool properly, pointed MGCB at 64 bit builds of your content processor, and your content builds but still fails to load, it could be because the ContentTypeReaderManager is failing to find the specific content type. I had problems where my XML content was a dictionary of custom processed types. I have a changeset built, cleaned up and tested (to a degree), and will be contributing it soon.

**Comment by Alturos** [comment] 2015-08-18 17:11
See Pull Request #4088

**Comment by Jjagg** [comment] 2018-12-10 10:38
Closing this and tracking the issue reported in the last comments in #6584.

**Closed by Jjagg** 2018-12-10 10:38 UTC
