### ISSUE TITLE
MGCB Editor Doesn't Launch On Mac

### ISSUE THREAD

**Issue by Tsspidermine** [MonoGame/MonoGame#7419] opened 2020-12-15 06:29 UTC
Whenever I launch the mgcb editor, from command line or from the app itself, the icon shows up in the dock for a split second, then crashes, I've even tried changing the name of the files in /MGCB Editor/Contents/MacOS/

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- MacOS

#### What MonoGame platform are you using:

- DesktopGL

**Comment by harry-cpp** [comment] 2020-12-15 07:48
Duplicate of https://github.com/MonoGame/MonoGame/issues/7418

**Closed by harry-cpp** 2020-12-15 07:48 UTC
