### ISSUE TITLE
Problem with effect parametrs

### ISSUE THREAD

**Issue by j303-27** [MonoGame/MonoGame#7151] opened 2020-05-22 15:19 UTC
effect.fx: 
```
float4x4 World;
float4x4 WorldViewProjection;
float a;
float b;

SamplerState Sampler : register(s0); 

Texture2D texture0;
Texture2D texture1;
Texture2D texture2;

struct VertexShaderInput
{
    float4 Position : POSITION;
	float3 Normal : NORMAL0;
	float2 TexCoord : TEXCOORD0;
};

struct VertexShaderOutput
{
	float4 Position : POSITION;
	float2 TexCoord : TEXCOORD0;
	float3 Normal : TEXCOORD2;
};

VertexShaderOutput MainVS(VertexShaderInput input)
{
	VertexShaderOutput output;

	output.Position = mul(input.Position, WorldViewProjection);

	output.Normal = normalize(mul(input.Normal, World));

	output.TexCoord = input.TexCoord;

	return output;
}

float4 MainPS(VertexShaderOutput input) : COLOR0
{
	float4 color0 = texture0.Sample(Sampler, input.TexCoord);
	float4 color1 = texture1.Sample(Sampler, input.TexCoord);
	float4 color2 = texture2.Sample(Sampler, input.TexCoord);

	float4 result = {1, 0, 0, 1};

	return saturate(result);	
}

technique BasicColorDrawing
{
	pass P0
	{
		VertexShader = compile vs_5_0 MainVS();
		PixelShader = compile ps_5_0 MainPS();
	}
};
```

Code: 
```  
Effect effect = this.effects[0];

foreach(EffectParameter p in effect.Parameters)
 {
	Log.Add(p.Name);
 }
```

Result:
```
World
WorldViewProjection
a
b
```

Why doesn't it exist texture0, texture1, texture2?

**Comment by Jjagg** [comment] 2020-05-22 16:23
MonoGame compiles effects with the highest optimization settings. This removes unused shader parameters. This is noted in our [documentation](https://docs.monogame.net/articles/content/custom_effects.html#effect-writing-tips):

> The effect compiler is aggressive about removing unused parameters, be sure the parameters you are setting are actually used.

This is something people frequently run into however and maybe we should lower the optimization level or at least make it configurable.

**Comment by harry-cpp** [comment] 2020-05-22 17:43
Duplicate of https://github.com/MonoGame/MonoGame/issues/911 then.

**Closed by harry-cpp** 2020-05-22 17:43 UTC
Labels: MGFX, Question
