### ISSUE TITLE
Mouse move generates garbage under Windows OpenGL

### ISSUE THREAD

**Issue by ala53** [MonoGame/MonoGame#3662] opened 2015-03-26 04:31 UTC
Using MonoGame 3.3, moving the mouse generates a fair amount of garbage; I'm not sure if it is related to low level OpenTK implementation or to the MonoGame layer.

In this example, the screen flashes red during every generation 0 collection and the memory allocation is shown in the title bar. Just move the mouse and watch.

```
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
using Microsoft.Xna.Framework.Input;
using System;

namespace OpenTKTest
{
    public class Game1 : Game
    {
        GraphicsDeviceManager graphics;

        public Game1()
            : base()
        {
            graphics = new GraphicsDeviceManager(this);
            Content.RootDirectory = "Content";
        }
        private int lastG0CollCT = 0;
        protected override void Draw(GameTime gameTime)
        {
            Window.Title = "Mem: " + (GC.GetTotalMemory(false) / (1024d * 1024)).ToString("N2");
            GraphicsDevice.Clear(GC.CollectionCount(0) == lastG0CollCT ? Color.CornflowerBlue : Color.Red);
            lastG0CollCT = GC.CollectionCount(0);
            base.Draw(gameTime);
        }
    }
}
```

**Comment by thefiddler** [comment] 2015-03-26 11:15
I am not seeing any allocations when testing on Linux using the develop branch. On which operating system are you seeing this?

Note that the Draw() method in your repro is allocating every frame. Are you seeing the same behavior if you remove the `Window.Title = ...` line?

**Comment by Shqrdx** [comment] 2015-03-26 17:47
Strange, the code above is really fast increments(when mouse moved) but not with WindowsGL assembly but with WindowsDX assembly.

**Comment by ala53** [comment] 2015-03-26 17:59
There's a bit of allocation going on because of the `Window.Title...` but (a) it stays pretty constant and (b) I can't remove it because it is the most garbage free way to show the memory usage (aside from printing to console).

Below is a GIF of what happens on my screen. When the mouse isn't moving, it's maybe 5-10kb/sec allocated (presumably the `GC.GetTotalMemory`, string concat, and the set title call). When it is, it's maybe 1/2 mb/sec to 1 mb/sec.
http://i.imgur.com/jSeNfGq.gif

**Comment by ala53** [comment] 2015-03-26 18:02
@Shqrdx So, you're having the memory allocations on the DX version but not the OpenGL version? What OS (Windows XP/Vista/7/8/10)?

**Comment by Shqrdx** [comment] 2015-03-26 18:09
Windows 8.1

**Comment by thefiddler** [comment] 2015-03-26 22:06
WinDX is using WinForms internally, which allocates memory on every event. There is no way around that.

WinGL is using OpenTK which is designed to not allocate memory at runtime. My testing shows flat memory usage on the OpenGL back ends.

Just to make this clear, are you seeing memory allocations in the DX or the GL backend?

**Comment by tomspilman** [comment] 2015-03-26 22:16
> WinDX is using WinForms internally

Specifically the Windows desktop version of MonoGame.  Which is the is really the fastest platform where MonoGame runs...  if some garbage generation is allowable...  it is on the Windows desktop builds.

I would be much more concerned if this was on a Mono platform or on any of the mobile platforms.

**Comment by ala53** [comment] 2015-03-26 22:22
@thefiddler Yes, this is on the Windows GL version. Strangely, the I didn't notice any extraneous allocations on the Windows DX platform (or at least, not as much as on Windows GL).

A bit of further testing indicates that any sort of mouse move / click event generates garbage. Is OpenTK allocating new EventArgs objects on every mouse event but not on every keyboard event?

@tomspilman It's not a big issue in terms of performace. All the events are generation 0 GC's which probably add mere nanoseconds to the frame render time but it seems like a bug somewhere in the code of MonoGame or OpenTK that should be fixed.

**Comment by ala53** [comment] 2015-03-26 22:57
On the left is Windows GL, right is Windows DX. I removed all memory allocations (SpriteBatch immediate mode, no strings, fixed size array, etc) and there's still a big issue.
![bug](https://cloud.githubusercontent.com/assets/8086191/6858926/8a8b6f22-d3d0-11e4-8615-9761ee9292ea.gif)

**Comment by ala53** [comment] 2015-03-26 22:57
The code is here https://gist.github.com/ala53/16059d6c4f7aa87e12fd

**Comment by cra0zy** [comment] 2017-04-29 15:09
@tomspilman Duplicate of #2717, should be closed.

**Closed** 2017-04-30 01:38 UTC
Labels: OpenGL, OpenTK
