### ISSUE TITLE
HLSL buffers incorrectly calculated?

### ISSUE THREAD

**Issue by ed022** [MonoGame/MonoGame#4828] opened 2016-05-08 20:38 UTC
I have a shader that causes an ArgumentException, "Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection."

The stack trace is as follows:
   at System.Buffer.BlockCopy(Array src, Int32 srcOffset, Array dst, Int32 dstOffset, Int32 count)
   at Microsoft.Xna.Framework.Graphics.ConstantBuffer.SetData(Int32 offset, Int32 rows, Int32 columns, Object data)
   at Microsoft.Xna.Framework.Graphics.ConstantBuffer.SetParameter(Int32 offset, EffectParameter param)
   at Microsoft.Xna.Framework.Graphics.ConstantBuffer.Update(EffectParameterCollection parameters)
   at Microsoft.Xna.Framework.Graphics.EffectPass.Apply()

After some really low-level probing, I was able to determine that the effect's ConstantBuffer(s) seems to have been incorrectly allocated. My vertex shader has four float4x4 parameters, and as such, the offsets are correctly set as 0, 64, 128, 192. However, the ConstantBuffer's buffer is only 240 bytes, rather than the necessary 256. It looks as though it's reading that sizeInBytes figure from the compiled shader effect code, so does that mean the HLSL compiler is doing something wrong? Or is there something else that I'm overlooking?

**Comment by ed022** [comment] 2016-05-08 21:19
Looks like this is the same issue as #911 and #2054. As such, I see where in my HLSL code the issue arises. However, there is an additional complication: The offending matrix - the fourth of four - is _in most techniques_ used in its full 4x4 dimensions, however, in the one running at the time of the crash, it's only using 3 of its four rows. Therefore, it's not a simple matter of changing the matrix parameter size.

**Comment by tomspilman** [comment] 2016-05-10 03:11
@ed022 - If you can share this shader it will help us be able to debug and resolve this.

I assume you are running on Windows in this case?  Are you using the DirectX or OpenGL version of MonoGame?

In the past when we ran into this issue it was that the HLSL optimizer noticed the last row of the shader isn't used and optimized it away.  We then didn't account for it correctly and you end up with more data to set than the constant buffer holds.

A work around can be chaning the matrix in question to a float3x3 in your shader.

**Comment by Jjagg** [comment] 2018-12-11 10:02
Closing as duplicate of #911.

**Closed by Jjagg** 2018-12-11 10:02 UTC
