### ISSUE TITLE
IndexBuffer causes graphic glitch

### ISSUE THREAD

**Issue by DrGurka** [MonoGame/MonoGame#7546] opened 2021-08-10 22:25 UTC
Hey, when i try to create an IndexBuffer to create a 3d object the first frame creates this weird artifact 
![bild](https://user-images.githubusercontent.com/8782054/128941732-31e510c4-1bc2-47dd-a71b-f28d10eab8d8.png)
I've tried the same code on multiple computers and the same problem occurs, i've also tried both OpenGL and DirectX and neither works. Here is the project files if you wanna test it yourself, press F to create a cube and G to remove all cubes.

[ArtifiactGlitch.zip](https://drive.google.com/file/d/1gyx0rvFNkojvkt2woK47YE11lrcaV9ct/view?usp=sharing)

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- DesktopGL

**Comment by mrhelmut** [comment] 2021-08-16 08:32
Hey, this looks like a Nez issue, or a Nez/MonoGame version mismatch. I'll be closing this issue here. If you can verify more in depth what the problem is after checking versions and still think it's a MonoGame issue, feel free to reopen with more details.

**Closed by mrhelmut** 2021-08-16 08:32 UTC
