### ISSUE TITLE
NoAudioHardwareException

### ISSUE THREAD

**Issue by gktval** [MonoGame/MonoGame#6909] opened 2019-10-18 17:46 UTC
Exception on Android phone when the game starts. This is not every phone, but a significant number of them.

android.runtime.JavaProxyThrowable: Microsoft.Xna.Framework.Audio.NoAudioHardwareException (0x80004005): OpenAL device could not be initialized. ---> System.NullReferenceException: Object reference not set to an instance of an object
  at Microsoft.Xna.Framework.Audio.OpenALSoundController.OpenSoundController () [0x00000] in <03b9f832711c4c6f9c98f98173bda512>:0
  at Microsoft.Xna.Framework.Audio.OpenALSoundController.OpenSoundController () [0x00031] in <03b9f832711c4c6f9c98f98173bda512>:0
  at Microsoft.Xna.Framework.Audio.OpenALSoundController..ctor () [0x00011] in <03b9f832711c4c6f9c98f98173bda512>:0
  at Microsoft.Xna.Framework.Audio.OpenALSoundController.get_GetInstance () [0x00007] in <03b9f832711c4c6f9c98f98173bda512>:0
  at Microsoft.Xna.Framework.AndroidGamePlatform..ctor (Microsoft.Xna.Framework.Game game) [0x00060] in <03b9f832711c4c6f9c98f98173bda512>:0
  at Microsoft.Xna.Framework.GamePlatform.PlatformCreate (Microsoft.Xna.Framework.Game game) [0x00000] in <03b9f832711c4c6f9c98f98173bda512>:0
  at Microsoft.Xna.Framework.Game..ctor () [0x001fb] in <03b9f832711c4c6f9c98f98173bda512>:0
  at Pereger.PeregerGame..ctor () [0x00000] in <601637514e4a4dcdbf07082d6f07de43>:0
  at Pereger.Droid.Game1..ctor () [0x00000] in <c990f010d0a74aada959b9d84ee904e7>:0
  at Pereger.Droid.Activity1.OnCreate (Android.OS.Bundle bundle) [0x0000e] in <c990f010d0a74aada959b9d84ee904e7>:0
  at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x00011] in <4a69c4acd2f94ccbb38f5dedd74c0b87>:0
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.3(intptr,intptr,intptr)
    at md528ab7f9ad30718a6c7f6f5d125304566.Activity1.n_onCreate(Native Method)
    at md528ab7f9ad30718a6c7f6f5d125304566.Activity1.onCreate(Activity1.java:35)
    at android.app.Activity.performCreate(Activity.java:6868)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2676)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2784)
    at android.app.ActivityThread.-wrap12(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1523)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:163)
    at android.app.ActivityThread.main(ActivityThread.java:6238)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7.1

#### What operating system are you using:
- Android
![image](https://user-images.githubusercontent.com/7605046/67116015-c42d3500-f19c-11e9-86a6-861eb090d5bf.png)

**Comment by Jjagg** [comment] 2019-10-24 10:26
This is a duplicate of #6558.

**Closed** 2019-10-24 10:26 UTC
Labels: Android, Audio
