### ISSUE TITLE
Builds now crashing on startup on Android 6 & 7?

### ISSUE THREAD

**Issue by shimfish** [MonoGame/MonoGame#6831] opened 2019-07-30 15:27 UTC
I tried building stable and dev builds of monogame myself and then finding the app crashes on Android versions 6 & 7 when it tries to load dlls. 

I then tried using the dev builds from nuget and they are showing similar behaviour.

It appears to be fine on other versions of Android as do the stable nuget builds of monogame.

`07-30 11:19:50.880 E/AndroidRuntime(23660): android.runtime.JavaProxyThrowable: System.TypeInitializationException: The type initializer for 'MonoGame.OpenGL.GL' threw an exception. ---> System.DllNotFoundException: dl
07-30 11:19:50.880 E/AndroidRuntime(23660):   at (wrapper managed-to-native) MonoGame.Utilities.FuncLoader.dlopen(string,int)
07-30 11:19:50.880 E/AndroidRuntime(23660):   at MonoGame.Utilities.FuncLoader.LoadLibrary (System.String libname) [0x00000] in <1cdd20a6d5654884ade8e071ffccae4d>:0 `

I'm using the latest stable Xamarin and Visual Studio Mac versions.

Is it possible that the new version of Xamarin.Android is causing this?

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.0.648 nuget

#### What operating system are you using:
- Mac

#### What MonoGame platform are you using:

- Android

**Comment by shimfish** [comment] 2019-07-31 08:47
It seems this has more or less been confirmed as a problem with the latest Xamarin.Android.

It's not a monogame bug but I guess you should be aware of it as I think it's present in the monogame dev nuget builds.

**Comment by dmanning23** [comment] 2019-08-03 13:03
I'm able to reproduce this bug on a Nexus9 device.
I have a Pixel3 which works fine though.

**Comment by nkast** [comment] 2019-08-03 14:52
Is that a problem only with VS2019?
How about xamarin.Android that comes with VS2017? Does it still work or it's broken too?

**Comment by shimfish** [comment] 2019-08-03 19:37
It appears to be an issue with Xamarin.Android 9.4.0.51

**Comment by cra0zy** [comment] 2019-08-09 13:44
So turns out https://github.com/xamarin/xamarin-android/issues/3311 was a bigger bug than I thought it was :/

**Comment by anthonyhan** [comment] 2019-08-31 10:33
I had the same issue.

**What version of MonoGame does the bug occur on:**

- MonoGame 3.7.1

**What operating system are you using:**

- Windows 10
- VS2019 16.2.2
- Xamarin.Android 9.4.1.0

**What MonoGame platform are you using:**

- Android

**Devices**

- Redmi Note 2 (Cortex-A53) Android 5.0
- OPPO A33 (Cortex-A53) Android 5.1

I used the method provided by @zeno32167 in https://github.com/MonoGame/MonoGame/issues/4161#issuecomment-281846228_ . 
It only works when both **armeabi-v7a** and **x86** are checked. Weird...

**Comment by cra0zy** [comment] 2019-10-17 19:31
Closing as the issue was on xamarin-android side and it is fixed.

**Closed by cra0zy** 2019-10-17 19:31 UTC
Labels: Android
