### ISSUE TITLE
Add FromUri method to other types of assets than Song

### ISSUE THREAD

**Issue by darkhog** [MonoGame/MonoGame#5917] opened 2017-09-01 23:03 UTC
Song.FromUri is a very nice and easy way to load a music file directly from a specified path, without worrying of all glue code you'd need to put if you'd wanted to load it from stream. Could similar method be added for other types of resources such as Texture2D, SoundEffect, etc.? Basically everywhere the developer may want to load it from specific path. This would make things easy when you want to make highly moddable game that can be modded without using any sort of XNB stripper/editor.

For anyone still unconvinced:

``` C#
//code with fromstream:
//Let's load some textures
FileStream texturestream = new FileStream("Content/backgrounds/titlebg.png", FileMode.Open);
Texture2D titlebgtexture = Texture2D.FromStream(graphicsDevice,texturestream);
texturestream.Close();
texturestream = new FileStream("Content/logos/logo.png", FileMode.Open);
Texture2D titlelogo = Texture2D.FromStream(graphicsDevice,texturestream);
texturestream.Close();
texturestream = new FileStream("Content/ui/uiatlas.png", FileMode.Open);
Texture2D uiatlas = Texture2D.FromStream(graphicsDevice,texturestream);
texturestream.Close();

//and now as if FromUri was implemented:

Texture2D titlebgtexture = Texture2D.FromUri(graphicsDevice,new System.Uri("Content/backgrounds/titlebg.png",System.UriKind.Relative);
Texture2D titlelogo = Texture2D.FromUri(graphicsDevice,new System.Uri("Content/logos/logo.png",System.UriKind.Relative);
Texture2D uiatlas = Texture2D.FromUri(graphicsDevice,new System.Uri("Content/ui/uiatlas.png",System.UriKind.Relative);
```

Less lines of code makes coders happy 😄. 
I could probably add this as extension methods and probably I will, but it would be good to have it in the core.

**Comment by Jjagg** [comment] 2017-09-01 23:56
Somewhat related to #5761.

IMO this is not necessary. The `FromStream` methods are the analog to `Song.FromUri` for `Texture2D` and `SoundEffect`. It's just more general because `Song` is streamed from disk, while a texture/sfx is loaded into memory, so it can be loaded from any kind of stream. 

That said, we certainly could add `FromFile` or `FromUri`, it's not like it's hard to implement or maintain :p

**Comment by darkhog** [comment] 2017-09-02 00:05
Yeah, it would be great if added, for API consistency if nothing else. As I've said, I'd probably do it as an extension method (or rather bunch of them) but it'd be nice if implemented in the core.

**Comment by darkhog** [comment] 2017-09-02 21:15
That's kinda embarrassing, but how do you do pull requests? I'm about to implement it via extension methods (decided on "from file" variant just so I won't need to mess with System.Uri) and I've though you could benefit from a resulting file.

**Comment by Jjagg** [comment] 2018-10-08 08:51
Closing as duplicate of #5761.

**Closed by Jjagg** 2018-10-08 08:51 UTC
