### ISSUE TITLE
Just running the template causes Nuget exited with code 1

### ISSUE THREAD

**Issue by Tricky1975** [MonoGame/MonoGame#7317] opened 2020-08-18 10:11 UTC
![image](https://user-images.githubusercontent.com/11202073/90500399-1a675d80-e14b-11ea-8df0-00ad2e9ebcaa.png)
Just running the sample code, NO MODIFICATIONS (I need to stress that as I did get the notice "learn to code" before when I was trying to run unmodified code without much success), just created the template with the new project wizard, and run, and this is what I got... 

Interesting to note are the two warning triangles in the dependencies tree, which looks to me like the source of all evil here. Now all information I got is exit code 1, and what that means (Okay, Googling that code says "path not found"... which path and why that path is needed I do not know) is guessing work.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- DesktopDX

**Comment by aaronlego2** [comment] 2020-08-25 09:45
Duplicate of #7303 

Looks like the issue has already been fixed!

**Closed** 2020-08-25 10:05 UTC
