### ISSUE TITLE
ContentReader's internal GraphicsDevice

### ISSUE THREAD

**Issue by JoaoBaptMG** [MonoGame/MonoGame#6438] opened 2018-09-24 22:23 UTC
Delving in the MonoGame's source code, I discovered that the `ContentReader`'s `GraphicsDevice` property is internal:

            // Should it REALLY be internal?
            internal GraphicsDevice GraphicsDevice
            {
                get
                {
                    return this.graphicsDevice;
                }
            }

It also seems that there is no other way to get a `GraphicsDevice` in a content type reader, which might be problematic to custom graphics contents (for example, a preprocessed path primitive using the Kilgard–Bolz technique). Is it the intended code? If so, how can I get a `GraphicsDevice` inside a content type reader?

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- WindowsDX

**Comment by nkast** [comment] 2018-09-25 05:09
>  If so, how can I get a GraphicsDevice inside a content type reader?

You get it through a IGraphicsDeviceService.

```
protected override DynamicVertexBuffer Read(ContentReader input, DynamicVertexBuffer buffer)
        {  
            IGraphicsDeviceService graphicsDeviceService = (IGraphicsDeviceService)input.ContentManager.ServiceProvider.GetService(typeof(IGraphicsDeviceService));
            GraphicsDevice device = graphicsDeviceService.GraphicsDevice;

           // create buffer resource here...
            return buffer;
        }
```

**Comment by cra0zy** [comment] 2018-09-30 12:59
Closing as this is not a bug.

**Closed by cra0zy** 2018-09-30 12:59 UTC
