### ISSUE TITLE
IME popup window does not show when type chinese characters with default Microsoft Pinyin IME.

### ISSUE THREAD

**Issue by ryancheung** [MonoGame/MonoGame#6667] opened 2019-02-17 10:46 UTC
In windows, IME window does not show when type Chinese characters with default Microsoft Pinyin IME.

Sample Code:
```csharp
using System;
using System.Linq;
using System.IO;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
using Microsoft.Xna.Framework.Input;
using SpriteFontPlus;

namespace Game1
{
    public class Game1 : Game
    {
        // ReSharper disable once NotAccessedField.Local
        private readonly GraphicsDeviceManager _graphicsDeviceManager;
        private SpriteBatch _spriteBatch;

        String text = "hello";

        private DynamicSpriteFont _font;

        public Game1()
        {
            _graphicsDeviceManager = new GraphicsDeviceManager(this);
            Content.RootDirectory = "Content";
            IsMouseVisible = true;
            Window.AllowUserResizing = true;

            this.Window.TextInput += TextInputReceived;
        }

        private void TextInputReceived(object sender, TextInputEventArgs e)
        {
            text += e.Character.ToString();
        }

        protected override void Initialize()
        {
            base.Initialize();
        }

        protected override void LoadContent()
        {
            _spriteBatch = new SpriteBatch(GraphicsDevice);
            _font = DynamicSpriteFont.FromTtf(File.ReadAllBytes(@"Fonts/simsun.ttf"), 20);
  
            
            GC.Collect();
        }

        protected override void UnloadContent()
        {
        }

        protected override void Update(GameTime gameTime)
        {
            var deltaTime = (float)gameTime.ElapsedGameTime.TotalSeconds;
            var keyboardState = Keyboard.GetState();

            if (keyboardState.IsKeyDown(Keys.Escape))
                Exit();


            base.Update(gameTime);
        }

        protected override void Draw(GameTime gameTime)
        {
            GraphicsDevice.Clear(Color.Blue);

            _spriteBatch.Begin();
            Vector2 textMiddlePoint = _font.MeasureString(text) / 2;
            // Places text in center of the screen
            Vector2 position = new Vector2(Window.ClientBounds.Width / 2, Window.ClientBounds.Height / 2);
            _spriteBatch.DrawString(_font, text, position, Color.Gold);
            _spriteBatch.End();

            base.Draw(gameTime);
        }
    }
}
```

The unicode characters displays correctly with SpriteFontPlus, but the IME window does not show up.

#### What version of MonoGame does the bug occur on:
MonoGame 3.7

#### What operating system are you using:
Windows 10

#### What MonoGame platform are you using:
DesktopGL

**Comment by ryancheung** [comment] 2019-02-17 10:49
SDL can do this with the method `SDL_StartTextInput();`
SDL sample code: https://thenumbat.github.io/cpp-course/sdl2/07/07.html

**Comment by ryancheung** [comment] 2019-02-17 10:52
MonoGame is great, except the poor dynamic font support, the poor IME support in desktop.

godotengine and libgdx do these really well.

**Comment by Jjagg** [comment] 2019-02-17 11:59
I'm closing this as a duplicate of #6347. Yes, font and text definitely needs some work.

**Closed by Jjagg** 2019-02-17 11:59 UTC
