### ISSUE TITLE
"B" button triggers "BACK" button on UWP (xbox controller)

### ISSUE THREAD

**Issue by mhughson** [MonoGame/MonoGame#6404] opened 2018-08-05 04:38 UTC
UWP builds of MonoGame report that "BACK" is being pressed when the "B" button is pressed on an X1 controller.

This doesn't seem to be an issue for any other platforms, and seems to be somewhat intentional (UWP implements a generic "Back" event which gets mapped to the "B" button at the OS level, I believe).

More details here: http://community.monogame.net/t/xbox-one-back-vs-b-button-possible-bug/8862/6

I think that the issue is on line 312 of https://github.com/MonoGame/MonoGame/blob/157bdd9b3313be47eeebb882dfc8038f05b1c807/MonoGame.Framework/WindowsUniversal/UAPGameWindow.cs

```
        private void BackRequested(object sender, BackRequestedEventArgs e)
        {
            // We need to manually hide the keyboard input UI when the back button is pressed
            if (KeyboardInput.IsVisible)
                KeyboardInput.Cancel(null);
            else
                _backPressed = true;

            e.Handled = true;
        }
```

You are registering for the "BackRequested" event (see line 133 of the same file) and treating that to mean that the back button has been pressed, but that is mapped to the "B" button on PC.

Committed here: https://github.com/MonoGame/MonoGame/pull/5810 by @atomgott (who may have more insight into this issue).

#### What version of MonoGame does the bug occur on:
- MonoGame 3.6

#### What operating system are you using:
- Windows 10

#### What MonoGame platform are you using:

- WindowsUWP

**Comment by atomgott** [comment] 2018-08-08 18:32
I don't think my PR is the reason for that behaviour. If I remember correctly, all it did was add a temporary variable to avoid a race condition and move the code into a different place (that's probably why you think I introduced that bug). The PR was merged after 3.6 release, as far as I know, anyway. 

So I don't know why the B button is mapped to the back button, but I can confirm that it happens.
Maybe you could try a recent development build?

**Comment by mhughson** [comment] 2018-08-08 22:58
It's not that your change did the mapping of B to BACK. You mapped the event "BackRequested" to the physical BACK button (which on desktop, is triggered by the B button- not the VIEW/BACK button as you might assume).

**Comment by atomgott** [comment] 2018-08-09 04:56
No, you don't understand. It mapped the event before, but in a different class! That's why git blame shows me as author of that code, but I just copied and pasted it. If you see the issue in 3.6 that's exactly because it has been that way before.
BTW I am aware that you are talking about the B button on a game pad.

**Comment by mhughson** [comment] 2018-08-09 17:50
Ah yes, I see what you mean (and sorry, I missed your comment about 3.6 before- which is the version I am using).

So yah, it still seems like a bug to me, but not from your change.

**Comment by cra0zy** [comment] 2018-09-30 12:03
Can't reproduce this issue on 3.7, closing...

**Comment by atomgott** [comment] 2018-10-07 21:04
The problem is that the "B" button (not only the "back" button) at all triggers GamePad.Back. UWP Platform is designed to work with game pads and probably binds the B button to the BackRequested event because not every controller has a back button. A game might want to use the B button for something different than going back.

**Comment by cra0zy** [comment] 2018-10-07 21:27
Oh, I see now why I did not reproduce it, it can't occur on Desktop.

On a related note, we should change the phone back button handling as using a gamepad for it is really really bad way of handling it. I mean what if I connect a controller to my phone, how will I figure out when the controller B button is pressed, and when the phone back button is pressed. There is a huge difference in actions between the two of them.

**Comment by nkast** [comment] 2018-11-08 16:30
about the issue with duplicate input, it's still a problem in Android which reports  the back as Keys.Back and MG fires gamepad's Buttons.Back.
If you hold the back button (you need to remove the boilerplate exit code of course..) , then the gamepad will 'auto-fire' Botton.Back as PRESSED/RELEASED continuously on every frame.

This is bad when you have code that checks both Buttons.Back and Keys.Back. For example if the user is at 2-3 levels in a menu and press back will find himself in the main menu or exiting.

This can be fixed by clearing the GamePad.Back on onKeyUp event, although I can't tell if the bug won't reappear when you are not running the gameloop on  the UIThread.
I think it's best to remove this, even if it will break some project the fix is easy, -check for the native Keys.Back.  We don't really need to emulate WindowsPhone7 anymore.

**Comment by Jjagg** [comment] 2018-11-08 16:59
I actually agree that we should just get rid of the hack and not modify keyboard or gamepad state.

**Comment by Brett208** [comment] 2019-02-23 16:18
I'm testing a game on Xbox One and am encountering this issue. When pressing the 'B' button on the Xbox One controller, my game will suspend and the console will go to the menu. I think this should qualify as a bug.

I'm Using a current development version of MonoGame 3.8.0.320. x64, release configuration using an Xbox controller on an Xbox 1.

If this issue doesn't get fixed, I will be forced to add some sort of hack to prevent the 'B' button from registering as return to menu. 

Any chance we can reopen this issue?

Thanks,
Brett

**Comment by kamehouseorbust** [comment] 2019-02-28 18:06
Using UWP right now and this issue persists for me. Is there at least a hack right now for stopping it?

**Comment by nkast** [comment] 2019-02-28 21:10
@kamehouseorbust

Are you using the latest develop build?
The fix was merged recently. It's not part of 3.7.
You need MonoGame 3.8.

**Comment by kamehouseorbust** [comment] 2019-02-28 21:27
@nkast apologies, I'm going through this thread because it's a wider problem with UWPs themselves. I'm not actually using Monogame, but I'm interested in the work arounds that subvert typical UWP back behavior.

Sorry for the confusion, I was just here to see a solution I could possibly use outside of Monogame myself.

**Comment by nkast** [comment] 2019-03-01 15:28
@kamehouseorbust 
See #6520. What we have done was to remove the BackRequested. Instead we subscribe to HardwareButtons.BackPressed for getting the Back button on Phones.

@Brett208 
Can you build you app as UWP and test it on Windows 10 ?

**Comment by Halofreak1990** [comment] 2019-04-07 17:29
I second what @Brett208 said. I'm using the latest monogame development NuGet package (3.8.0.341) with the CoreApp template, and I'm seeing the same issue. Pressing either Back or B will suspend the application (and for some reason, the Xbox doesn't allow me to resume).

**Comment by onodera-sf** [comment] 2019-04-08 12:16
The same phenomenon has occurred to me. The version of MonoGame is 3.8.0.341. I asked another user to play the game, but the B button ends the game. Below is a reference video. (it's Japanese)
https://twitter.com/Tim_SOURIS/status/1115202987599650816

**Comment by onodera-sf** [comment] 2019-04-08 12:27
Template : Windows 10 Universal (Core Application)
MonoGame.Framework Version : 3.8.0.341
Input Device : XInput

Windows 10 1809 : No problem
Xbox One              : There is a problem

reference video : https://twitter.com/Tim_SOURIS/status/1115202987599650816
I use the B button to close the menu, but with Xbox One the game is interrupted.

**Comment by onodera-sf** [comment] 2019-04-09 04:03
additional information
The DLL and the version to refer to are slightly different depending on the way of creating a project.

■Pattern 1

・Project creation procedure
1.Create MonoGame UWP CoreApp 3.7.1 (Minimum Version : Windows 10 Novenber Update (build 10586)) 
2.Install MonoGame 3.8.0.341

・Reference runtime Version
MonoGame.Framework : 3.8.0.341
Universal Windows : UAP,Version=10.0.17134.0

・Result
Windows 10 1809 : No problem
Xbox One : There is a problem

■Pattern 2

・Project creation procedure
1.Install MonoGame 3.8.0.341
2.Create MonoGame UWP CoreApp 3.8 (Minimum Version : Windows 10 Novenber Update (build 10586)) 

・Reference runtime Version
MonoGame.Framework : 3.8.0.341
Universal Windows : UAP,Version=10.0.17763.0

・Result
Windows 10 1809 : ???
Xbox One : ???

■Pattern 3

・Project creation procedure
1.Install MonoGame 3.8.0.341
2.Create MonoGame UWP CoreApp 3.8 (Minimum Version : Windows 10 Creators Update (build 15063)) 

・Reference runtime Version
MonoGame.Framework : 3.8.0.341
Universal Windows : UAP,Version=10.0.17763.0
Microsoft.UI.Xaml.Markup : 10.0.0.0

・Result
Windows 10 1809 : ???
Xbox One : ???

**Comment by Romans-I-XVI** [comment] 2019-07-27 19:05
So first off, I believe this B button suspending the app issue is a separate issue than the original "B" triggers "Back" issue.

To start, here's the fix. In App.xaml.cs you can place this bit of code in your OnLaunced method.
```
Windows.UI.Core.SystemNavigationManager.GetForCurrentView().BackRequested += (object sender, Windows.UI.Core.BackRequestedEventArgs args) => { args.Handled = true; };
```
As to why this is happening, apparently as of Universal Windows version 10.0.15063 if you don't handle the [BackRequested](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Core.SystemNavigationManager.BackRequested) event the app will automatically suspend on the Xbox. The usage of BackRequested is sort of documented [here](https://docs.microsoft.com/en-us/windows/uwp/design/input/gamepad-and-remote-interactions#gamepad-and-remote-control) but doesn't say anything about suspending your app on the Xbox if not handled. I'm not sure where, if anywhere, the behavior is documented, I found the info from [this post](https://social.msdn.microsoft.com/Forums/SECURITY/en-US/0318799e-1ced-4714-9e6a-740cbb7a1372/xbox-livefall-creators-sdkxbox-onepressing-the-b-red-button-suspends-game-and-goes-back-to?forum=xboxlivedev).

Note: If your target version is Windows 10 Anniversary Edition (Build 14393) you won't experience this issue as the auto-suspend on B press "feature" wasn't implemented yet. Which is probably why some people are experiencing this issue and others aren't.

**Comment by Romans-I-XVI** [comment] 2019-08-08 03:05
So I just realized I was using XAML where most people here are using CoreApp. The solution is the same bit of code but as to where it should be placed I'm not certain. I put mine at the end of my Game constructor and it seems to work.

**Comment by Brett208** [comment] 2020-01-20 20:40
@nkast, I know this is super late and apologize for not following up many months ago. 

@Romans-I-XVI is correct that this behaviour still exists. I just retested using MonoGame 3.8.0.1010 and Windows 10 SDK 1903 (build 18362). 

If using the CoreApp template to use UWP, you can add something roughly similar to the code below to work around the issue. 

```CSharp
using Windows.UI.Core;

public class Game1 : Game
{
    public Game1()
    {
        // Prevent the XBOX controller B button from automatically closing the game
        SystemNavigationManager.GetForCurrentView().BackRequested += App_BackRequested;   
    }

    private void App_BackRequested(object sender, BackRequestedEventArgs e)
    {
        e.Handled = true;
    }
}
```

I'm not an expert on UWP. Maybe something similar to this portion of code could be added to the CoreApp template? I don't feel knowledgeable enough about UWP to push a fork unless someone with more experience could comment that this looks like an acceptable way to handle the back request and others thought it actually belonged in the template.

**Comment by nkast** [comment] 2020-01-20 21:18
Thanks @Brett208 
I come up with the same fix. https://github.com/nkast/MonoGame/commit/c96c220802fbe59d79a3addc51620334dd4146c9

**Comment by ET3D-ET3D** [comment] 2020-07-06 08:53
Just wanted to say thanks to Romans-I-XVI. You're a lifesaver. I was losing my hair over that 'B kills the game' problem.

**Comment by Eversor** [comment] 2021-05-14 09:28
Shouldn't this fix go into the Monogame game.cs ? I see quite some noob being discouraged by a similar behaviour out of the box.

**Comment by mrhelmut** [comment] 2021-05-14 10:33
nkast's proposed fix looks just fine to me.

**Comment by Eversor** [comment] 2021-05-14 10:37
Ok sorry, looks like i was using some older template as i still had the problem in my last month build.

**Comment by mrhelmut** [comment] 2021-05-14 13:23
It's not merged, it's only on nkast's personal branch.  If anyone is up to make it into a PR, I'll look into it for merging.

**Comment by nkast** [comment] 2021-05-14 14:24
I'll make a PR within the day.

**Closed** 2021-05-15 10:07 UTC
