### ISSUE TITLE
Pipeline: create new folder, first letter stripped - empty folder not saved to project file

### ISSUE THREAD

**Issue by InfiniteProductions** [MonoGame/MonoGame#5079] opened 2016-08-06 07:52 UTC
Launch the pipeline tool
create a new project
create a new folder "folder1"
=> folder called: older1
- save project at this stage = folder not added to content file (load project after closing it = need to create the folder again)

Windows 7 64b, pipeline rebuild today with latest dev source at this time (08/06/16 9h46 GMT+2).

**Comment by cra0zy** [comment] 2016-08-06 13:03
First letter stripped was fixed in the newest devel version, you probably didn't update to the latest source properly.

**Comment by InfiniteProductions** [comment] 2016-08-06 16:44
> First letter stripped was fixed in the newest devel version, you probably didn't update to the latest source properly.

weird, I have most of the source files matching this [commit](https://github.com/MonoGame/MonoGame/commit/035780798b321685738609644d5e25563e470a0a), which looks like to be the last relevant one.

Could you check and give which commit hold the fix please ?

**Comment by cra0zy** [comment] 2016-08-06 16:47
> Could you check and give which commit hold the fix please ?

Can't, I would need to search through a bunch of commits.

Also I can't reproduce the problem with the newest devel branch, neither on Windows or Linux.

**Comment by InfiniteProductions** [comment] 2016-08-07 09:13
> Can't, I would need to search through a bunch of commits.

that's not very good, a meaningful version number would be a lot better than just 1.0.0.0, it would allow at least to void such "fuzziness" on what is the current version tested against last merged PR, etc

> Also I can't reproduce the problem with the newest devel branch, neither on Windows or Linux.

newest ? What does this mean ? Again, I don't know which version I exactly have, and which version do you use (yours with some not yet committed/accepted PR ?)

As I wrote before, I've a MG source tree update yesterday morning (western Europe TZ), and looking at MG main branch, nothing is newer in pipeline tree than what I've got (as the last relevant commit was with "General Fixes" 4 days ago from now).

**Comment by KonajuGames** [comment] 2016-08-07 09:59
There is no facility in the MGCB file to store the name and location of an empty folder.  The folder structure is created from the relative paths of the files it is told to process.

**Comment by InfiniteProductions** [comment] 2016-08-08 08:36
@cra0zy : the (little, a few hours) time gap between my issues report and when your PR has been merged may explain the misunderstanding, my report, so I guess your "newest devel branch" is not the genuine MG branch.

I'll do the tests again.

**Comment by InfiniteProductions** [comment] 2016-08-09 09:23
The issue still happened with the newest dev build.

**Comment by cra0zy** [comment] 2016-08-09 10:20
#5080 is a false issue, because it happens because of this.

**Closed** 2017-05-02 18:52 UTC
