### ISSUE TITLE
Black Textures on IOS. (Related to #541)

### ISSUE THREAD

**Issue by User7711** [MonoGame/MonoGame#6551] opened 2018-11-20 18:37 UTC
After preprocessing png images and using RenderTarget2D to to scale them, all textures of my Game in IOS turn black. My other target: Win32(Dx), WinStore(Dx), Android(GL), Mac(GL), do not show this problem.

This seems to be a regression of [#541](https://github.com/MonoGame/MonoGame/issues/541)

Is there any way I or we can fix this?

Thanks!

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7 And Also newest Development Builds. (3.8.0.142)

#### What operating system are you using:
- MacOS 

#### What MonoGame platform are you using:

- IOS

**Comment by Alias-777** [comment] 2018-11-24 14:05
I've found a workaround which suits me for now. If I use SetRenderTarget on a later frame then when processing all my images to a new RenderTarget2D, the problem is solved. 

Hopefully this get fixed in the future, but until then this example fixes it!

**Example:**
```
private void iosFix() {
    GraphicsDevice.SetRenderTarget(new RenderTarget2D(GraphicsDevice, 1, 1));
    GraphicsDevice.SetRenderTarget(null):
}

private int fixCount = 0;
protected override void Update(GameTime gameTime) {
    if (++fixCount==2) {
        iosFix();
    }
}
```

**Comment by AidanMcK** [comment] 2019-02-11 12:29
This problem was discussed back in 2014 in relation to problems running on Android and apparently fixed, some mention of problems in ESTexture2D.cs - see a post in StackOverflow [here](https://stackoverflow.com/a/11765540).

**Comment by harry-cpp** [comment] 2020-04-13 21:09
There was a race condition on iOS, this should be fixed.

**Closed by harry-cpp** 2020-04-13 21:09 UTC
Labels: iOS
