### ISSUE TITLE
WinForms

### ISSUE THREAD

**Issue by StealthKill** [MonoGame/MonoGame#3686] opened 2015-03-31 12:33 UTC
MonoGame 3.3 isn't working with WinForms anymore.

It crashes While creating a new GraphicsDevice.

**Comment by lllAlexlll** [comment] 2015-03-31 13:12
Hello @StealthKill,

I have ported my Xna WinForms application to MonoGame recently without any issues and it works just as with Xna.

**Comment by StealthKill** [comment] 2015-03-31 13:24
Had no problems with 3.2 too. Can create an example?

**Comment by lllAlexlll** [comment] 2015-03-31 13:55
I use MonoGame 3.3 in WinForms with no issues (Map Editor application). I will be able to create an example probably today or tomorrow.

**Comment by lllAlexlll** [comment] 2015-03-31 13:56
What kind of exception is thrown in your case?

**Comment by StealthKill** [comment] 2015-03-31 14:23
I'm getting an argument Null exception while trying to create a GraphicsDevice

        GraphicsDeviceService(IntPtr windowHandle, int width, int height)
        {
            parameters = new PresentationParameters();

            parameters.BackBufferWidth = Math.Max(width, 1);
            parameters.BackBufferHeight = Math.Max(height, 1);
            parameters.BackBufferFormat = SurfaceFormat.Color;
            parameters.DepthStencilFormat = DepthFormat.Depth24;
            parameters.DeviceWindowHandle = windowHandle;
            parameters.PresentationInterval = PresentInterval.Immediate;
            parameters.IsFullScreen = false;

             //Error in this line.
            graphicsDevice = new GraphicsDevice(GraphicsAdapter.DefaultAdapter,
                                                    GraphicsProfile.Reach,
                                                    parameters);

        }

None of the parameters are null.

**Comment by lllAlexlll** [comment] 2015-03-31 14:39
I have very similar code but a bit different parameters. Changed my parameters yours and still no exception. Do you use latest stable build?

**Comment by lllAlexlll** [comment] 2015-03-31 14:56
I assume you are implementing GraphicsDeviceService: IGraphicsDeviceService. Try my version of GraphicsDeviceService if it will work for you: 
https://www.dropbox.com/s/owf85smlzjzowmb/GraphicsDeviceService.cs?dl=0

**Comment by StealthKill** [comment] 2015-03-31 15:23
Same Error :(
I'm using the MG 3.3 dll , OpenTK.dll
and  OpenTK.GLControl.dll maybe this one is outdated. It's from 2013 I don't know where i got this from.

**Comment by lllAlexlll** [comment] 2015-03-31 15:27
Then try installing latest MG 3.3 using installer: http://www.monogame.net/releases/v3.3/MonoGameSetup.exe

**Comment by StealthKill** [comment] 2015-03-31 15:50
I reinstalled monogame and took this example.
http://xbox.create.msdn.com/en-US/education/catalog/sample/winforms_series_1
Replaced the XNA dlls with Monogame.Framework.dll
getting same error.
If I use the 3.2 dll everything works :(

**Comment by lllAlexlll** [comment] 2015-03-31 16:16
Try installing latest DirectX runtime and Video Card driver.

**Comment by StealthKill** [comment] 2015-03-31 16:29
Are You using GLControl.dll? Can you upload me your dlls?

**Comment by lllAlexlll** [comment] 2015-03-31 16:40
Downloaded http://xbox.create.msdn.com/en-US/education/catalog/sample/winforms_series_1 example, changed references to MonoGame and everything is working.
Only had to remove parameters from the GraphicsDevice.Present(sourceRectangle, null, this.Handle) call since there are no such method overload in MonoGame.

Looks like issues with your system!

**Comment by StealthKill** [comment] 2015-03-31 16:48
Ok Thank you for your time and help :+1: 
Strange thing is my game is working fine with 3.3 only have this problems with my Editor and OpenTK.GLControl.dll.
I don't know if a Windows/Visual studio reinstall would work :(

**Comment by lllAlexlll** [comment] 2015-03-31 17:29
You are welcome!

I think the best thing you can do now is to try step into MonoGame code and see what actually is null. Download source code or use decompilation with debugging.

If Xna WinForms sample works for me then it is only time question to fix it on your system.

**Comment by StealthKill** [comment] 2015-03-31 18:49
I debugged the Monogame code and the error is occurs in GraphicsDevice.OpenGL.cs

        private void PlatformSetup()
        {
#if WINDOWS || LINUX || ANGLE
            GraphicsMode mode = GraphicsMode.Default;

            //ERROR HERE
            var wnd = (Game.Instance.Window as OpenTKGameWindow).Window.WindowInfo;
..
..
         

I don't know how to fix this

**Comment by StealthKill** [comment] 2015-03-31 19:24
Seems like you cant use this anymore without creating a Game instance.

**Comment by tomspilman** [comment] 2015-03-31 19:27
@StealthKill - We should be able to fix that.  There should be a better way to get the game window than `Game.Instance.Window`.

@thefiddler  @cra0zy ?

**Comment by lllAlexlll** [comment] 2015-03-31 19:52
Actually I do have the Game instance in my WinForms Map Editor application. If you do not have one then your case is different from mine.

Then my question is: 
how http://xbox.create.msdn.com/enUS/education/catalog/sample/winforms_series_1 example works for me with MG 3.3 if there is no Game instance in this example (which should cause an exception)?

**Comment by StealthKill** [comment] 2015-03-31 20:06
You are probably using MG DirectX. Works for me too with DirectX.
But I don't want to use 2 different DLLs.

**Comment by cra0zy** [comment] 2015-03-31 20:06
I have installed Windows 10 this morning and I have yet to install anything on it, so I'll check this out tomorrow.

Did you use MonoGame WindowsGL before monogame 3.3?

**Comment by lllAlexlll** [comment] 2015-03-31 20:16
@StealthKill 
> You are probably using MG DirectX. Works for me too with DirectX.
You are right. Sorry for confision!

**Comment by StealthKill** [comment] 2015-03-31 20:21
I'm using Monogame GL since 3.0 and never had problems with it until 3.3.

**Comment by Jjagg** [comment] 2018-12-09 00:48
Caused by #2586.

**Comment by Jjagg** [comment] 2018-12-09 00:51
Closing in favor of #4730.

**Closed by Jjagg** 2018-12-09 00:51 UTC
