### ISSUE TITLE
MonoGame StarterKits link in README.md is invalid.

### ISSUE THREAD

**Issue by Lywx** [MonoGame/MonoGame#4137] opened 2015-09-15 20:13 UTC
Copied from README.md.

```
Samples
=======
Once you have MonoGame, grab the [MonoGame StarterKits]
(https://github.com/kungfubanana/MonoGame-StarterKits) or [MonoGame Samples](https://github.com/Mono-Game/MonoGame.Samples) to help get you started on your first project.
```

**Comment by cra0zy** [comment] 2015-09-16 13:29
Technically, duplicate of #3846

**Comment by Lywx** [comment] 2015-09-16 13:35
True.

**Comment by cra0zy** [comment] 2017-05-01 18:07
@tomspilman This can be closed.

**Closed** 2017-05-01 18:26 UTC
