### ISSUE TITLE
Visual Studio Templates Not Being Installed

### ISSUE THREAD

**Issue by snaidamast** [MonoGame/MonoGame#5645] opened 2017-04-06 15:44 UTC
Hello...

When I moved over my game development projects to Visual Studio 2015 with Monogame 3.5 I noticed that the project templates were not installed and subsequently not showing up in the C# templates selection.  However, since my projects were correctly referencing the Monogame assemblies I had no issues running my work.  I only noticed this when I wanted to test out a new Monogame extension.

I uninstalled Monogame 3.5 believing it was an issue with my current installation and performed a re-install.  However, during the re-install process all of the available template selections were grayed out and not selectable as a result.

I cancelled the installation and tried the Monogame 3.6 installation finding the same issue.

This appears to be a rather substantial issue on the forums.  Can you supply either good documentation on how to work around this issue or correct the installation application so that we can select our VS templates and get them installed in the proper VS template directories.

I have gone through a number of forum postings and there is a lot of confusion as to what to actually do and only a few of them have the proper link to the templates download on DropBox.

I got mine working as a result but lesser experienced people will have terrible issues with this.

Thank you...

Steve Naidamast
Sr. Software Engineer
blackfalconsoftware@outlook.com

**Comment by Jjagg** [comment] 2017-04-06 16:14
3.5 had working templates, so not sure what went wrong there. 3.6 templates for VS2017 were broken, but it's fixed in the develop version and a 3.6.1 version will be released to get the fix out.

**Comment by snaidamast** [comment] 2017-04-06 16:20
Jesse...

Thanks for your quick reply but neither the 3.5 or 3.6 installs of Monogame have selectable templates.  I just did these installations this morning at around 11:00am EST.

I also ensured that I was running the installation as "Administrator".  I tried the 3.5 install several times before attempting the 3.6 install.  

I eventually found enough information to implement the Windows project template correctly from the DropBox download.

**Comment by Jjagg** [comment] 2017-04-06 18:15
Did you install Visual Studio at the default location? The 3.5 installer did not check the registry key and only looked for the template folder in the default location. 3.6 should work for VS 2015 though, but I don't know enough about it to troubleshoot.
I'm glad you managed to work around the issue.

**Comment by snaidamast** [comment] 2017-04-06 20:27
I installed Visual Studio 2015 using all of the standard default installation settings.  And none of my project efforts have shown any issues to date.

**Comment by Jjagg** [comment] 2018-11-16 16:54
Closing this as it's likely a duplicate of either #4838 (registry key doesn't point to the right place) or the issue described and fixed in #6544 and we don't have any more information.

**Closed by Jjagg** 2018-11-16 16:54 UTC
