### ISSUE TITLE
TouchLocationState on windows error

### ISSUE THREAD

**Issue by gamedevboy** [MonoGame/MonoGame#3288] opened 2014-12-18 03:43 UTC
when drag the cursor in the game window and the window lost the fouce, then I only receive the TouchLocationState.Move, and it always be ...

**Comment by Jjagg** [comment] 2018-12-11 17:18
I can't really make much sense of this, but I think it's a duplicate of #3657 and I don't think we're gonna get anymore information about this so I'm closing it.

**Closed by Jjagg** 2018-12-11 17:18 UTC
