### ISSUE TITLE
Pipeline tool cannot import fonts

### ISSUE THREAD

**Issue by fatcatz888** [MonoGame/MonoGame#4705] opened 2016-04-02 08:14 UTC
Just used Pipeline tool 3.5.1.1679 to build content for my WP8.0 game. Before I was using XNA to build content without any problems.

The Pipeline tool does not seem to import fonts. The font loads in the game but is just displaying the same (I think Ariel) font regardless of font used. Checked the generated xnb file sizes and all the font file sizes are the same.

**Comment by tomspilman** [comment] 2016-04-02 08:22
Hi @fatcatz888 .

I suspect I know what the issue is.  Can you share one of the failing .spritefont files with us so we can verify?

**Comment by fatcatz888** [comment] 2016-04-02 08:56
Sure no problem, I'll supply 3, that's all the spritefont my game is using.

I think the MG Pipeline is just using segoe wp for all 3 font outputs (I guess this because the output file sizes are the same size as the segoe wp file generated from the XNA Pipeline tool.

**franchise.spritefont**
```
<?xml version="1.0" encoding="utf-8"?>

<XnaContent xmlns:Graphics="Microsoft.Xna.Framework.Content.Pipeline.Graphics">
  <Asset Type="Graphics:FontDescription">
    <FontName>Franchise</FontName>
    <Size>26</Size>
    <Spacing>0</Spacing>
    <UseKerning>true</UseKerning>
    <Style>Regular</Style>
     <DefaultCharacter>*</DefaultCharacter>
    <CharacterRegions>
      <CharacterRegion>
        <Start>&#32;</Start>
        <End>&#126;</End>
      </CharacterRegion>
    </CharacterRegions>
  </Asset>
</XnaContent>
```

**segoe-wp.spritefont**
```
<?xml version="1.0" encoding="utf-8"?>
<XnaContent xmlns:Graphics="Microsoft.Xna.Framework.Content.Pipeline.Graphics">
  <Asset Type="Graphics:FontDescription">
    <FontName>Segoe WP</FontName>
    <Size>18</Size>
    <Spacing>0</Spacing>
    <UseKerning>true</UseKerning>
    <Style>Regular</Style>
    <CharacterRegions>
      <CharacterRegion>
        <Start>&#32;</Start>
        <End>&#126;</End>
      </CharacterRegion>
    </CharacterRegions>
  </Asset>
</XnaContent>
```

**segoe-wp-bold.spritefont**
```
<?xml version="1.0" encoding="utf-8"?>
<XnaContent xmlns:Graphics="Microsoft.Xna.Framework.Content.Pipeline.Graphics">
  <Asset Type="Graphics:FontDescription">
    <FontName>Segoe WP</FontName>
    <Size>18</Size>
    <Spacing>0</Spacing>
    <UseKerning>true</UseKerning>
    <Style>Bold</Style>
    <CharacterRegions>
      <CharacterRegion>
        <Start>&#32;</Start>
        <End>&#126;</End>
      </CharacterRegion>
    </CharacterRegions>
  </Asset>
</XnaContent>

```

**Comment by tomspilman** [comment] 2016-04-06 00:52
@fatcatz888 - Is this the `Franchise` font?  http://fontpro.com/franchise-font-518

**Comment by fatcatz888** [comment] 2016-04-06 06:46
Yes

**Comment by repstyle** [comment] 2016-05-02 19:07
I have the same issue, anyone can explain and solve this ?
I'm going nutz because of it :).
Thx.

**Comment by repstyle** [comment] 2016-05-02 20:35
OMG i found my issue, it's really stupid, i'm ashamed.
I have written the path to my fonts in the wrong order.

To explain a bit, i have a class font handling the variables getting the spritefonts and somewhere else, i give the path to the spritefonts.: 


In the class Font : 
SpriteFont my_font_12_bold
SpriteFont my_font_18_bold

And in the other class FontGiver (where i give the path of the spritefont file) : 
"FontsFolder/18_bold"
"FontsFolder/12_bold"

Here you can see my error because the fonts are not set in the same order in the 2 files, that's why it wasn't working.

**Comment by tomspilman** [comment] 2016-05-03 16:00
@repstyle - That happens... glad to see you solved your issue.

**Comment by martingronlund** [comment] 2016-11-09 07:18
@tomspilman can we close this issue?

**Comment by tomspilman** [comment] 2016-11-09 09:08
Thanks @martingronlund !

**Closed by tomspilman** 2016-11-09 09:08 UTC
Labels: Help Wanted
