### ISSUE TITLE
Massive wait between draw calls

### ISSUE THREAD

**Issue by stupidrat** [MonoGame/MonoGame#3660] opened 2015-03-26 02:00 UTC
Here is what I did, I got the latest stable release of mono game.
I then created a basic window project.  

All I changed from the base project is this

```
protected override void Draw(GameTime gameTime)
    {
        drawStopwatch.Stop();
        if (drawStopwatch.ElapsedMilliseconds > 100)
        {
            delegateConsole.BeginInvoke("PARENT draw time:  " + drawStopwatch.ElapsedMilliseconds, null, null);
        }

        GraphicsDevice.Clear(Color.CornflowerBlue);

        // TODO: Add your drawing code here

        base.Draw(gameTime);

        drawStopwatch.Reset();
        drawStopwatch.Start();
    }
```

The only other thing is that I declared the stopwatch.

So what happens here, is that the program runs and FPS remain high, but every once in a while it will take 100+ms to call draw.

This is a massive pause in drawing.  The fps remain at close to 60fps because it seems that the machine makes up for the loss by bunching more frames together.

I also tried the exact same thing with the stopwatch in update, and the same thing happens there too.  This is not good at all for a game as it does cause large gaps in time where things glitch and look terrible.

**Comment by stupidrat** [comment] 2015-03-26 09:52
Had my nvidia software tell me to upgrade drivers this morning, that forced a reboot.  Now the problem seems to be gone.

Either this is a driver issue, or Windows can get into a state where it runs correctly but causes terrible things with MonoGame.  So a consumer could have their machine in whatever state my computer was in and MonoGame would run the product terribly, not sure if there could be a MonoGame fix, or if this is OS related junk.  I'm running windows 8.1 if that makes a difference.

**Comment by tomspilman** [comment] 2015-03-26 14:47
I recommend testing with a game that actually does "stuff" over an empty test project.

**Comment by stupidrat** [comment] 2015-03-27 09:25
I've done both, that drove me to create the empty project.  Not sure how we find what happens, but this  "state" has been entered several times for me and I am trying to narrow down where it is coming from.  It does not seem to be complexity, Garbage Collection, or anything like that.  

I do have two Nvidia cards working using SLI, maybe that has something to do with it.  But it seems to a a rare state that we get into that causes very bad runs or builds.  If it happens again.  I am going to try and copy the exe onto a different machine and see if it is the build or not.

**Comment by ala53** [comment] 2015-03-28 22:45
@stupidrat Are you by chance on the Windows 10 TP? It has some major issues somewhere down the line that seem to stall the graphics card drivers for anywhere from 10 to 500 ms randomly.

**Comment by xposure** [comment] 2015-04-14 19:16
I just came back here and stumbled across this while I was looking for my old issue from last month. Information can be found here with my results. I posted the same exact thing, after driver updates the problem was seemingly "solved". Today the problem is once again back and I just did another driver update and still have the same issue.

https://github.com/mono/MonoGame/issues/3553

**Comment by xposure** [comment] 2015-04-14 19:55
To make sure everyone understands the magnitude of this problem (3 different machines, 15fps) I decided to record the issue and got some interesting results.

* Simply moving my mouse over the tab on chrome at the top took the draw calls up to about 66ms which results in 15fps. 
* Starting up fraps changed this to 33ms as a max draw call giving a minimum of 30 fps (not allowing me to effectively record it)
* Closing fraps kept the maximum drawcall to 33ms for about 5 minutes until the problem resurfaced. I did not close or launch or touch anything else, I simply watched my average draw time (not the time to draw, the time between each draw)
* Opening fraps back up gave me 30 fps again, after waiting, the problem resurfaced and fraps dropped to 15fps
* Telling fraps to start recording got me back up to 30fps and locked it there for another 5 minutes or so after stopping the recording

- These tests were all either done by moving the mouse of the tab header of the chrome window or by just letting my cursor have focus in this input field for this issue.

Since this all seems to be tied to how chrome renders (I would imagine its not specific to chrome, its just where I noticed it), it is acting like chrome is "stealing" the vsync which forces SharpDX to wait for another one causing a 33ms spike and so on.

@tomspilman I get the same exact results with an empty project or rendering 2000 sprites. The issue is in SharpDX and this function.

    _swapChain.Present(syncInterval, PresentFlags.None);

**Comment by tomspilman** [comment] 2015-04-14 20:13
> The issue is in SharpDX and this function.

There is no "issue" in SharpDX...  it is normal for that function to block if the GPU is busy.

The question is what is making your GPU too busy to render.

**Comment by KonajuGames** [comment] 2015-04-15 00:02
I have similar render performance problems associated with Google Chrome.
It comes and goes with various Chrome versions and video driver versions.
It is a known issue with Google Chrome (many users have reported it in
various forums and Chrome's bug tracker), but I don't think there has been
a firm fix for it yet.

There is nothing that MonoGame or SharpDX can do about it.

**Comment by xposure** [comment] 2015-04-15 20:24
@tomspilman @KonajuGames  I disagree, its something in SharpDX looking for some sort of exclusive access during a vsync. This is nothing to do with the GPU being busy, we are talking less than 1% cpu utilization. To prove it, launch 4 versions of the test projects given in either issue here and watch the delay between draw calls sky rocket. With 4 instances running the delay to return from Present on the the SharpDX swapChain takes 66ms.

I'd be very curious if you guys get the same results running the test projects given. The only thing I can think of that isn't generally standard on most machines is that I have SLI on all of them.

Chrome was simply just a means for me to identify this oddity.

Hardware specs and sample project: https://gist.github.com/xposure/bff23116b9e8a2e00644

**Comment by tomspilman** [comment] 2015-04-15 21:00
> SharpDX looking for some sort of exclusive access during a vsync.

SharpDX is just a wrapper for DX11 and there is no concept as "exclusive access" to vsync in DX11 or any other graphics API.

> I'd be very curious if you guys get the same results running the test projects given.

It runs fine on my machine and I have a fairly mid-range machine (i7 2.6Ghz 8GB and a single Radeon HD 6900):

![desktop](https://cloud.githubusercontent.com/assets/103522/7169089/e58162c6-e387-11e4-913b-5d6000f67ff0.jpg)

As you can see I had 6 copies of your test running, one in the debugger showing the output, 2 copies of Chrome playing 2 different videos, and a copy of IE playing another video.  A pretty solid 60hz except when I start dragging windows around and stuff.

>  I have SLI on all of them.

That could be the trigger, but there is nothing to fix in MonoGame for that.

**Comment by xposure** [comment] 2015-04-15 23:53
@tomspilman Since you had no issues with ATI, I wanted to test the SLI theory and managed to find a laptop with Nvidia to test and I had the same results as you, with 4 instances I was getting 16ms draw calls.

So I focused my attention on SLI and came across [this nvidia article](http://nvidia.custhelp.com/app/answers/detail/a_id/3283/~/what-is-smooth-vsync%3F) this would explain why my tests above we're "fixing" themselves over time. Tomorrow I'll run some different tests on my SLI machine.

**Closed** 2017-05-02 20:02 UTC
