### ISSUE TITLE
EffectParameter names vary because of build target

### ISSUE THREAD

**Issue by guFalcon** [MonoGame/MonoGame#6172] opened 2018-01-30 22:33 UTC
As mentioned in PR #6146 the name of an `EffectParameter` may be different for OpenGL builds than for all others, if it's a `TextureSampler`.
But that is a problem, as @tomspilman already mentioned since the name of a parameter should be the primary way to fetch it, not the index in the `EffectParameter[]` in the `EffectParameterCollection`.

I've prepared a GitHub repo that should demonstrate this issue and can be a point where to start debugging. I've not added a .gitignore file, so everyting's in  there.
https://github.com/UnterrainerInformatik/MonoGame_names_of_effect_parameters

I've tested it with:
MonoGame 3.7.0.1232
MonoGame 3.7.0.960
MonoGame 3.6.0.1598
It's the same everywhere.

Disclaimer :)
Maybe I'm doing something wrong here. There are many ways to declare a `TextureSampler`, but I think the shader is alright.
It definitely is connected to the sampler declaration, since if you declare it like this:
`sampler2D FirstSampler : register(s0);` it works!
But you can't use the new notation to fetch texels and you're stuck with `tex2D`.
Sure is an option, but the bug is there nevertheless.

BTW... When passing two textures, there is some odd behavior that I have documented in this repository (including images). Maybe someone can take a look and decide whether it's worth pursuing or not.
https://github.com/UnterrainerInformatik/MonoGame_multi_texture_shader

**Comment by Jjagg** [comment] 2018-01-31 02:36
This is because modern HLSL lets you sample with one sampler from different textures. So texture is no longer a part of the sampler state. Old opengl doesn't have that separation, so to make sure things work out MojoShader maps each used sampler + texture combination to an OpenGL sampler. If you implicitly declare a texture in HLSL with the dx9 syntax, the texture is a part of the sampler state, so no mapping is needed to fix things up for GLSL. 

I remember writing something more involved on this topic, but don't recall where. Anyway, it's possible to abstract the differences out.

**Comment by guFalcon** [comment] 2018-01-31 08:55
But that means that the current state is basically broken.
You cannot rely on the order of `EffectParameters` and you cannot use the name either because it will differ if you compile for OpenGL.
I think we have a genuine bug here.
Any thoughts?

**Comment by nkast** [comment] 2018-01-31 18:44
@guFalcon 
>> It definitely is connected to the sampler declaration, since if you declare it like this:
>> sampler2D FirstSampler : register(s0); it works!
>> But you can't use the new notation to fetch texels and you're stuck with tex2D.

@Jjagg 
>>  If you implicitly declare a texture in HLSL with the dx9 syntax, the texture is a part of the sampler state, so no mapping is needed to fix things up for GLSL.

So names also vary by the version of Shader model?

**Comment by nkast** [comment] 2018-01-31 18:57
Another question, 
When you target 9_1 or, 9_3 the DX compiler will create two shaders, 
one compatible with old SM2,SM3 cards, and a faster version for SM4 cards (uses branching and other  new features). The driver uses the best version for your card.
How does this work with setting TextureSampler paprameters?

**Comment by Jjagg** [comment] 2018-01-31 19:07
> But that means that the current state is basically broken.

Yes, that's true. I was just trying to explain why this issue occurs. The workaround would be for MG to set all samplers that sample from texture x when texture x is set. MG would only expose 1 texture (like what's exposed in DX), even though it maps to multiple GLSL samplers.

> So names also vary by the version of Shader model?

No, not by shader model AFAIK, but by syntax used. I think the old syntax generates different bytecode, so MojoShader knows that it's a sampler with texture included in its state (so no separation of samplers and textures).

> When you target 9_1 or, 9_3 the DX compiler will create two shaders,
one compatible with old SM2,SM3 cards, and a faster version for SM4 cards

I didn't know this. We'd have to try this, look at MojoShaders source code or ask Ryan "icculus" Gordon.

**Comment by guFalcon** [comment] 2018-01-31 21:58
Ok.
Obviously between the two of you I'm way out of my league here 😄 
So if you tell me what to test, I'm happy to do that and spare you the time of cloning and fiddling with my repo.
I suppose it's about this line in the shader:
```hlsl
PixelShader = compile ps_4_0_level_9_1 PixelShaderFunction();
```

**Comment by Jjagg** [comment] 2018-10-07 17:32
Duplicate of #6120.

**Closed by Jjagg** 2018-10-07 17:32 UTC
