### ISSUE TITLE
Microsoft.Xna.Framework.Content.ContentLoadException when loading fonts(Spritefont) - other content types seem to be fine

### ISSUE THREAD

**Issue by DeanLaw14** [MonoGame/MonoGame#7174] opened 2020-05-30 15:40 UTC
**Full exception Details:**
Microsoft.Xna.Framework.Content.ContentLoadException:
`Could not find ContentTypeReader Type. Please ensure the name of the Assembly that contains the Type matches the assembly in the full type name: Microsoft.Xna.Framework.Content.ListReader 1[[System.Char, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]] (Microsoft.Xna.Framework.Content.ListReader 1[[System.Char, System.Private.CoreLib]])`

**Platform details****Versions:** 3.8.0.1375-develop
**OS**: Windows
**MonoGame platform:** Both Android and iOS

**Comment by harry-cpp** [comment] 2020-06-02 19:54
Can you provide a sample project?

**Comment by DeanLaw14** [comment] 2020-06-03 00:16
[https://github.com/DeanLaw14/Sample](url)

**Comment by DeanLaw14** [comment] 2020-06-03 00:18
[](https://github.com/DeanLaw14/Sample)

**Comment by DeanLaw14** [comment] 2020-06-03 00:19
https://github.com/DeanLaw14/Sample

**Comment by harry-cpp** [comment] 2020-06-03 15:39
Looking into it, found 2 bugs in your project setup:
- Delete this line: https://github.com/DeanLaw14/Sample/blob/master/MGIphone/MGNamespace.csproj#L3
- Change the action of this item to `MonoGameContentReference`: https://github.com/DeanLaw14/Sample/blob/master/MGIphone/MGNamespace.csproj#L115
- Change the action of this item to `None`: https://github.com/DeanLaw14/Sample/blob/master/Sample.Shared/Sample.Shared.csproj#L21

I did however find an unrelated bug regarding font building from Mac.

**Comment by DeanLaw14** [comment] 2020-06-03 21:00
![image](https://user-images.githubusercontent.com/40341387/83688608-95f24d80-a5e5-11ea-8816-d616147f8b1e.png)

I'm still experiencing the same issue - even after applying the changes you pointed out :(

**Note:** Im assuming you saw my commented out line in the **Game1** class line 32 :O 
Otherwise my bad if you missed that  - in the mean time im going to try and get someone else to run that sample just to see if its specific to my machine (I highly doubt)

**Comment by harry-cpp** [comment] 2020-06-03 21:22
Oh, this might have something to do with compiling from Windows.

**Comment by harry-cpp** [comment] 2020-06-03 21:22
(Also didn't mean to close this before, pressed the wrong button)

**Comment by DeanLaw14** [comment] 2020-06-04 02:01
Ahh cool no probs. PS - Im sure it gets said enough but you and the rest of the devs have done an awesome job!

**Comment by YTN0** [comment] 2020-06-11 04:07
I am running into the same issue with the latest 3.8 dev nugets. Is there a solution for this?

**Comment by harry-cpp** [comment] 2020-06-11 07:40
Are you also compiling iOS game from Windows?

**Comment by YTN0** [comment] 2020-06-11 07:48
@harry-cpp No, I am compiling on Windows (DirectX).

**Comment by harry-cpp** [comment] 2020-06-11 07:50
Can you give me a repro project?

**Comment by YTN0** [comment] 2020-06-12 01:11
@harry-cpp will try and put something together to illustrate the problem...

**Comment by YTN0** [comment] 2020-06-13 05:42
@harry-cpp I created a brand new project on windows and added a spritefont. Note, I deleted the packages folder since it was making the zip file too big (>200mb). Visual Studio will re-download the packages. If you need to manually add the nuget packages, just add the Monogame DirectX, Content Pipeline and content builder task nugets.

[FontTest.zip](https://github.com/MonoGame/MonoGame/files/4774122/FontTest.zip)

**Comment by harry-cpp** [comment] 2020-06-13 11:29
Okey, I think I see what the problem is!

**Comment by YTN0** [comment] 2020-06-13 17:32
@harry-cpp I tried your build with the fixes (build 1405) and I now get the following error:

D:/Dev/csharp/game/Test/fonts/arial.xml : error : Processor 'FontDescriptionProcessor' had unexpected failure!
1>  System.DllNotFoundException: Unable to load DLL 'freetype6' or one of its dependencies: The specified module could not be found. (0x8007007E)
1>     at SharpFont.FT.FT_Init_FreeType(IntPtr& alibrary)

Do I need both changes from 1405 and 1406 for this to work correctly?

**Comment by harry-cpp** [comment] 2020-06-13 17:38
> Do I need both changes from 1405 and 1406 for this to work correctly?

I've only submitted a PR: https://github.com/MonoGame/MonoGame/pull/7199, build 1405 is the one that run for it.

> D:/Dev/csharp/game/Test/fonts/arial.xml : error : Processor 'FontDescriptionProcessor' had unexpected failure!
1> System.DllNotFoundException: Unable to load DLL 'freetype6' or one of its dependencies: The specified module could not be found. (0x8007007E)
1> at SharpFont.FT.FT_Init_FreeType(IntPtr& alibrary)

Thats a content build failure, it has nothing to do with all of this, you are missing "vs c++ 2012 redist" stuff, tho I personally just quickly grabbed a newer freetype6 as even with "vs c++ 2012 redist" I couldn't get it to work.

**Comment by YTN0** [comment] 2020-06-13 19:26
@harry-cpp I have the runtimes installed and don't have an issue compiling fonts on projects which use the standard monogame installer or when I was running build 1403. The only issue I had then was the font loading issue when trying to run.

This problem only started occurring when trying build 1405 with the changes you submitted. 

I'll try re-installing my VC runtimes, but I don't think that's the issue.

**Comment by harry-cpp** [comment] 2020-06-13 19:30
My changes do not touch content compilation. I know what I'm talking about.

**Comment by YTN0** [comment] 2020-06-13 20:08
Seems like something got messed up on my laptop. I can't get past the freetype6 issue now. I have installed the VC runtimes (2012, 2013, 2015-2019) multiple times and it still doesn't fix it.

I may have to re-install VS to see if that solves it.

**Comment by harry-cpp** [comment] 2020-06-13 20:19
You can just grab a newer version of the lib from: https://github.com/Robmaister/SharpFont.Dependencies/blob/f8b032e132b7319099c916b78ec131866997f643/freetype2/2.6/msvc12/x64/freetype6.dll and replace the one found in packages/.nuget/.dotnet folders, and it will work.

**Comment by YTN0** [comment] 2020-06-13 22:30
@harry-cpp that freetype6.dll fixes the problem. Also, build 1405 with your fixe resolves the font loading issue at runtime. Thanks for fixing this!

**Closed** 2020-06-14 17:50 UTC

**Comment by MauriceButler** [comment] 2020-07-04 15:20
Is there anywhere I can grab the `MonoGame.Framework.Android` build 1405 or greater?

I cant find it in the artefacts on the Team City server but facing the same issue.

I am assuming the android builds happen somewhere else?
