### ISSUE TITLE
Constant Buffer overrun on DesktopGL

### ISSUE THREAD

**Issue by dellis1972** [MonoGame/MonoGame#5628] opened 2017-03-28 18:52 UTC
When using a shader under DesktopGL we get the following exception 

```Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.```

The error occurs at [1].

For this shader the offset is 64 the length of the _buffer is 112 bit the size of the data is 4*4*4. Which override the end of the buffer.  the sample shader is over at [2].

@tomspilman @Jjagg any idea which the shade compiler is not creating a buffer of the correct length?

[1] https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Graphics/Shader/ConstantBuffer.cs#L87
[2] https://github.com/infinitespace-studios/RacingGame/blob/master/Content/Shaders/PreScreenSkyCubeMapping.fx

**Comment by dellis1972** [comment] 2017-03-28 19:03
I have a feeling that the compiler is turning one of the float4x4 into a float3x4 which would explain why its short.

**Comment by tomspilman** [comment] 2017-03-28 19:05
> I have a feeling that the compiler is turning one of the float4x4 into a float3x4 

Yeah it certainly reduces the size of the uniform if you don't use it all... in particular with matrix stuff.

**Comment by dellis1972** [comment] 2017-03-28 19:11
I can put in a length check and only write the data that will fit. But that doesn't feel right

**Comment by Jjagg** [comment] 2017-03-28 21:48
I think this is the same problem as #4828, #911 and #2054 (the last one accidentally got closed, but it's the same issue). I'm not familiar with the MojoShader API, but I would expect that there's some way to detect optimizations like this or to disable them.

**Comment by tomspilman** [comment] 2017-03-28 22:15
> I would expect that there's some way to detect optimizations like this or to disable them.

Well the optimization actually happens in the HLSL side and not MojoShader.  MojoShader is just reacting to the optimization the HLSL compiler did.  The output from HLSL compiler has the information needed to account for the optimization, but MojoShader doesn't use that or pass the info along to you.

**Comment by Jjagg** [comment] 2018-12-11 10:03
Closing as duplicate of #911.

**Closed by Jjagg** 2018-12-11 10:03 UTC
Labels: Linux, OpenGL
