### ISSUE TITLE
ElementCount is not the right size

### ISSUE THREAD

**Issue by kibblebits** [MonoGame/MonoGame#6311] opened 2018-05-09 00:03 UTC
This is a little hard to explain...

In the old monogame version - my game would copy the color from one texture to another texture. My transfer_color array was not an exact match and was oversized. Visually I would copy a section of a texture and paste it into a new texture but slide it to the top left as possible. I would essentially not set a value into rest of the array.

I used this technique to copy two different sized textures but I started the array at the same size for both.

In the newest version of monogame I get an error message stating my array isn't the correct size. Was this intended to be changed to where I need an exact array now? 

System.ArgumentException: 'elementCount is not the right size, elementCount * sizeof(T) is 266928, but data size is 66464.'

Sample code (tried to simplify my code to make it understandable outside my game):

transfer_Color = new Color[layout.Width * layout.Height];

copy_color(transfer_Color);

final_piece = new Piece(new Texture2D(Game1._graphics.GraphicsDevice, offsetEnd - offset, (int)(piece_width * **2.1f**)), color));

final_piece.texture.SetData<Color>(transfer_Color);

transfer_Color = new Color[layout.Width * layout.Height];

copy_color_version2(transfer_Color);

final_piece2 = new Piece(new Texture2D(Game1._graphics.GraphicsDevice, offsetEnd - offset, (int)(piece_width * **2.5f**)), color));

final_piece2.texture.SetData<Color>(transfer_Color);

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- WindowsUWP

**Comment by Jjagg** [comment] 2018-05-09 15:52
`SetData` was made more strict to help with debugging. The array size does not have to be the same size as the texture, but you need to specify the number of elements to copy over and the area explicitly. The `SetData(T[])` overload only works if the size of the array matches the size of the texture, because it tries to copy over data the size of the whole texture. That does not work when the array is smaller than the size of the texture. You'll want to use the [`SetData(int, Rectangle?, T[], int, int)`](https://msdn.microsoft.com/en-us/library/ff434430(v=xnagamestudio.40).aspx) overload instead.

I'm going to close this because it's not a bug, but if anything is still unclear please open a topic on the [community forum](http://community.monogame.net/).

**Closed by Jjagg** 2018-05-09 15:52 UTC
