### ISSUE TITLE
Visual Studio extension doesn't build anymore

### ISSUE THREAD

**Issue by mrhelmut** [MonoGame/MonoGame#8300] opened 2024-05-08 08:08 UTC
It seems that building the Visual Studio Extension for VS2022 fails, likely due to recent changes within the ```Microsoft.VisualStudio.SDK``` package which tries to resolve a sub package of the same version that doesn't exist ```Microsoft.VisualStudio.SDK.Analyzers```.

> D:\a\MonoGame\MonoGame\Templates\MonoGame.Templates.VSExtension\MonoGame.Templates.VSExtension.csproj : error NU1102: Unable to find package Microsoft.VisualStudio.SDK.Analyzers with version (>= 17.7.20)
D:\a\MonoGame\MonoGame\Templates\MonoGame.Templates.VSExtension\MonoGame.Templates.VSExtension.csproj : error NU1102:   - Found 26 version(s) in nuget.org [ Nearest version: 16.10.10 ]
D:\a\MonoGame\MonoGame\Templates\MonoGame.Templates.VSExtension\MonoGame.Templates.VSExtension.csproj : error NU1102:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages

Investigations would be welcome to fix the build script.

**Comment by JakeLegendXIII** [comment] 2024-05-11 05:15
Hey @mrhelmut I have a couple solutions to get the builds working again. Neither are "perfect", but they do allow the CakeFrosting builds to complete and output all the normal things again. I have a PR open #8302  for option 1 (the simplest fix), but I am open to suggestions or changes.

1. Change the package reference wildcard versioning for Microsoft.VSSDK.BuildTools to be Version="17.9.*"   
2.  Override the version of the child dependency Microsoft.VisualStudio.SDK.Analyzers specifically using the 16.* wildcard. The latest version is 16.10.10 which is in the dependency tree for both correctly. This was last released in 2021 and does not change much, but does add an extra dependency to the csproj file. The upside to this change is we can keep both the other SDK packages on "17.*".

Microsoft.VSSDK.BuildTools seems to be the problem package in my testing. There are some 17.10.* pre-release packages that when pulled in as a wildcard introduce the error (seems odd since it should use stable versions with the wildcard but I can easily reproduce this problem over and over again). If you reference them explicitly they work, but whenever BuildTools is set to 17.* or 17.10.* right now it breaks. 

It might make sense to update both SDK packages to 17.9 if option 1 is the way forward. Hopefully though 17.10's rc or actual release won't have this issue though and then it could be set back to the wildcard.

**Comment by mrhelmut** [comment] 2024-05-12 07:26
1. Seems cleaner and likely all we can do for the time being.

Thanks for looking into it! I'll go ahead and merge your PR. 🙌

**Closed** 2024-05-12 07:25 UTC
Labels: Maintenance, Help Wanted
