### ISSUE TITLE
Flickering when using the DesktopGL Library w/windows 10.

### ISSUE THREAD

**Issue by longjoel** [MonoGame/MonoGame#4899] opened 2016-06-04 03:00 UTC
Getting a weird constant flicker with basic spritebatch stuff when using the DesktopGL backend. Issue ceases when using the DirectX backend.

**Comment by mrhelmut** [comment] 2016-06-04 10:56
Could you provide a sample? My first guess would be to think that it is related to the graphics driver, I've already seen Intel GPU having strange glitch on Win10, but beside this everything should be fine.

**Comment by nkast** [comment] 2016-06-04 13:26
Are you drawing anything besides `SpriteBatch`, like a 3D model? 
Can you test the same executable on another machine/GPU?

**Comment by RHY3756547** [comment] 2016-06-05 02:47
Laptop Switchable Intel GPU on Windows 10 is doing this here (at least what I think the issue is talking about), but only in fullscreen with vsync. It's not limited to spritebatch - getting it on 3d directly drawn to the backbuffer.

Vsync mostly works, it's just some of the scanlines randomly appear gray (my clear colour) for some reason. Can't get a clear screenshot for obvious reasons... Started happening when I switched to a recent version using the SDL frontend.

**Comment by mrhelmut** [comment] 2016-06-05 10:49
I have a very similar issue on a Surface Pro 4 (Intel GPU, Win10, but without dedicated GPU). From times to times, it shows random white/gray noise scanlines. When lowering the resolution, it dampens the effect. If it's the very same problem, I believe it's a driver bug that has direct link to fillrate.

**Comment by longjoel** [comment] 2016-06-06 17:16
It happens on my desktop. I have an AMD card R9 280x with Windows 10. When
I get home from work tonight I'll make a video.

**Comment by Jjagg** [comment] 2020-07-30 22:39
@mrhelmut Do you happen to know if this still happens? There's very little information to go on here and with how old this report is I'm considering closing this issue.

**Comment by mrhelmut** [comment] 2020-07-31 08:01
@Jjagg I still have that very device (a Surface Pro 4) and can't say I've seen anything fishy recently. I assume it definitely was a driver issue that got fixed.

**Comment by Jjagg** [comment] 2020-07-31 08:16
Great, thanks!

**Closed by Jjagg** 2020-07-31 08:16 UTC
Labels: Need Info, Needs Testing, OpenGL
