### ISSUE TITLE
Visual Studio 2019 MacOS support

### ISSUE THREAD

**Issue by jensuenk** [MonoGame/MonoGame#6887] opened 2019-09-30 14:27 UTC
MonoGame is not compatible with the latest version of Visual Studio 2019 for Mac. The templates don't show up when installed. It works on the 2017 version but not on the 2019 version.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7.1

#### What operating system are you using:
- MacOS

#### What MonoGame platform are you using:

- DesktopGL

**Comment by harry-cpp** [comment] 2020-03-25 23:23
Duplicate of https://github.com/MonoGame/MonoGame/issues/6695

**Closed by harry-cpp** 2020-03-25 23:23 UTC
