### ISSUE TITLE
Could not find ContentTypeReader Type. Please ensure the name of the Assembly that contains the Type matches the assembly in the full type name: 

### ISSUE THREAD

**Issue by V8275** [MonoGame/MonoGame#7534] opened 2021-07-17 08:42 UTC
I don't understand why this error appears when i add a model .dae

Microsoft.Xna.Framework.Content.ContentLoadException: "Could not find ContentTypeReader Type. Please ensure the name of the Assembly that contains the Type matches the assembly in the full type name: Microsoft.Xna.Framework.Content.ReflectiveReader`1[[Microsoft.Xna.Framework.Content.Pipeline.Graphics.MaterialContent, MonoGame.Framework.Content.Pipeline, Version=3.8.0.1641, Culture=neutral, PublicKeyToken=null]] (Microsoft.Xna.Framework.Content.ReflectiveReader`1[[Microsoft.Xna.Framework.Content.Pipeline.Graphics.MaterialContent, MonoGame.Framework.Content.Pipeline]])"

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8/0/1641

#### What operating system are you using:
- Windows 10

#### What MonoGame platform are you using:

- DesktopGL

**Comment by mrhelmut** [comment] 2021-07-17 09:40
Do you happen to have enabled .NET trimming?

**Comment by vladik8275** [comment] 2021-07-17 13:44
> Do you happen to have enabled .NET trimming?

How can I check this?

**Comment by akghasemi** [comment] 2023-01-23 21:09
I had the same issue with 3.8.1 , and I disabled .NET trimming and it worked, should it be disabled in monogame?

**Comment by Ragath** [comment] 2023-01-23 21:54
> I had the same issue with 3.8.1 , and I disabled .NET trimming and it worked, should it be disabled in monogame?

no you just need to tell it not to trim types you're actually using, like the readers. https://devblogs.microsoft.com/dotnet/customizing-trimming-in-net-core-5/

**Comment by mrhelmut** [comment] 2023-12-16 10:09
Duplicate of #8104

**Closed by mrhelmut** 2023-12-16 10:09 UTC
