### ISSUE TITLE
Upgrade from 3.7.1 to develop build throws System.DllNotFoundException: dl on some devices

### ISSUE THREAD

**Issue by AndreCL** [MonoGame/MonoGame#6840] opened 2019-08-08 19:04 UTC
Issue didn't occur on 3.7.1
After upgrading to latest develop branch, some devices are throwing the following exception on startup:
```
android.runtime.JavaProxyThrowable: System.TypeInitializationException: The type initializer for 'MonoGame.OpenGL.GL' threw an exception. ---> System.DllNotFoundException: dl
at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.19(intptr,intptr)
```

Full stacktrace

```
android.runtime.JavaProxyThrowable: System.TypeInitializationException: The type initializer for 'MonoGame.OpenGL.GL' threw an exception. ---> System.DllNotFoundException: dl
  at (wrapper managed-to-native) MonoGame.Utilities.FuncLoader.dlopen(string,int)
  at MonoGame.Utilities.FuncLoader.LoadLibrary (System.String libname) [0x00000] in <92a9d18dd90142039ec69d2f56460a81>:0 
  at MonoGame.OpenGL.GL..cctor () [0x00014] in <92a9d18dd90142039ec69d2f56460a81>:0 
   --- End of inner exception stack trace ---
  at Microsoft.Xna.Framework.MonoGameAndroidGameView.CreateGLContext () [0x00541] in <92a9d18dd90142039ec69d2f56460a81>:0 
  at Microsoft.Xna.Framework.MonoGameAndroidGameView.processStateResuming () [0x000b9] in <92a9d18dd90142039ec69d2f56460a81>:0 
  at Microsoft.Xna.Framework.MonoGameAndroidGameView.RunIteration (System.Threading.CancellationToken token) [0x000af] in <92a9d18dd90142039ec69d2f56460a81>:0 
  at Microsoft.Xna.Framework.MonoGameAndroidGameView+<>c__DisplayClasse.<WorkerThreadFrameDispatcher>b__c (System.Object s) [0x00017] in <92a9d18dd90142039ec69d2f56460a81>:0 
  at Android.App.SyncContext+<>c__DisplayClass3_0.<Send>b__0 () [0x00000] in <1386cc0eb0ab4744b0b71c0574958672>:0 
  at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <1386cc0eb0ab4744b0b71c0574958672>:0 
  at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in <1386cc0eb0ab4744b0b71c0574958672>:0 
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.19(intptr,intptr)
	at mono.java.lang.RunnableImplementor.n_run(Native Method)
	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
	at android.os.Handler.handleCallback(Handler.java:746)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5459)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
```

Occurs on following devices:
Motorola Moto G4 Play w. Android 6.0
LGE K3 2017 w. Android 6.0
Motorola Moto Z w. Android 7.0
Huawei Mate 9 w. Android 7.0

**Doesn't** occur on following devices:
Samsung Galaxy S9 w. Android 8.0
Google Pixel 2 w. Android 8.1
Sony Xperia XZ1 Compact w. Android 8.0
Nokia 1 w. Android 8.1 (Go edition)
Google Pixel 3 w. Android 9
Google Pixel 2 w. Android 9
Samsung Galaxy S9 w. Android 9.0

#### What version of MonoGame does the bug occur on:
- MonoGame develop branch

#### What operating system are you using:
Android

#### What MonoGame platform are you using:

- Android

**Comment by mrhelmut** [comment] 2019-08-09 08:18
Possible duplicate of #6452

**Comment by KakCAT** [comment] 2019-08-09 09:01
> Possible duplicate of #6452, though it should have been fixed by #6454. Hmm.

I think it's not related to audio but a bug of Xamarin, duplicate of https://github.com/MonoGame/MonoGame/issues/6831

**Comment by mrhelmut** [comment] 2019-08-09 12:04
Looks like you're right.

**Comment by cra0zy** [comment] 2019-08-09 13:43
Closing as this is a duplicate of: #6831

**Closed by cra0zy** 2019-08-09 13:43 UTC
Labels: Android
