### ISSUE TITLE
Fixed incorrect glyph position in FontDescriptionProcessor.cs

### ISSUE THREAD

**Issue by zsmolnar** [MonoGame/MonoGame#5098] opened 2016-08-10 22:47 UTC
Hi guys,

I believe I fixed a bug in the FontDescriptionProcessor.cs. 

line 120 original:
var cropping = new Rectangle(0, (int)(glyph.YOffset - yOffsetMin), (int)glyph.XAdvance, output.VerticalLineSpacing);

fixed:
var cropping = new Rectangle((int)(glyph.XAdvance + glyph.XOffset), (int)(glyph.YOffset - yOffsetMin), (int)glyph.XAdvance, output.VerticalLineSpacing);

In our case, using https://www.fontsquirrel.com/fonts/kingthings-petrock font, the 'c' character was positioned incorrectly. See the attached image.

![image](https://cloud.githubusercontent.com/assets/1948647/17573784/973315ca-5f54-11e6-91a6-f44b5989403a.png)

Sorry I'm not submitting a PR, I'm not a git user.

**Comment by dellis1972** [comment] 2016-08-13 15:46
@zsmolnar Thanks for the bug report.

**Comment by stromkos** [comment] 2021-03-21 20:00
This is caused by the GlyphCropper.Crop() method not adjusting the kerning values for the trimmed glyph.

This problem only happens for certain fonts. From the freetype2 code comments:

> The control box encloses all the outline’s points, including Bezier control points. Though it coincides with the exact bounding box for most glyphs, it can be slightly larger in some situations (like when rotating an outline which contains Bezier outside arcs).

>Computing the control box is very fast, while getting the bounding box can take much more time as it needs to walk over all segments and arcs in the outline. To get the latter, you can use the ‘ftbbox’ component which is dedicated to this single task.

**Comment by nkast** [comment] 2021-05-15 13:20
I've made a mistake in my first commit 87dfc7d. This issue is closed by #7501, not #7502.

**Closed** 2021-07-02 20:31 UTC
Labels: Font, Good First Issue
