### ISSUE TITLE
VertexBuffer - unexplainable memory leak

### ISSUE THREAD

**Issue by MatthiasKloepperQC** [MonoGame/MonoGame#6861] opened 2019-08-15 14:24 UTC
In a project where I create new VertexBuffers very frequently I recently experienced an OutOfMemory-Exception. After digging in a little bit further I can reproduce the problem with minimum test code:

```c#
for (int i = 0; i < 1000000; i++)
            {
                // Create a new VertexBuffer.
                VertexBuffer v = new VertexBuffer(this.GraphicsDevice, typeof(VertexPositionNormalTexture), 1000, BufferUsage.WriteOnly);

                // Dispose the new VertexBuffer without ever using it.
                v.Dispose();
            }
```
After about 250.000 iterations of the loop the size of my heap has not increased but the used memory (private bytes) for my process has reached around 1 GB. More iterations inevitable lead to an OutOfMemory (System.OutOfMemoryException) situation due to reaching the 2GB barrier for 32Bit processes.

If I increase the vertexCount for the creatio of the Buffer I am able to produce an SharpDXException referencing ApiCode "E_OUTOFMEMORY" before running into the System.OutOfMemoryException.

If I reset the GraphicsDevice all "leaked" memory is reclaimed:

```c#
for (int i = 0; i < 1000000; i++)
            {
                // Create a new VertexBuffer.
                VertexBuffer v = new VertexBuffer(this.GraphicsDevice, typeof(VertexPositionNormalTexture), 1000, BufferUsage.WriteOnly);

                // Dispose the new VertexBuffer without ever using it.
                v.Dispose();

                // Resetting the device reclaims memory.
                if (i % 10000 == 0) this.GraphicsDevice.Reset();
            }
```

Probably I'm doing yomething wrong. Which is the correct way to completely free an assigned VertexBuffer?

Greetings and thanks for your help,
Matti

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.0.402

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- WindowsDX

**Comment by MattiKloepper** [comment] 2019-08-15 14:42
Just upgrade to 3.8.0.682. Issue is still there.

**Comment by KakCAT** [comment] 2019-10-09 08:40
I did some tests about this some time ago but for some reason it seems I forgot to post them. Now linking the issue made me see that.

There's something weird about this test. I've reproduced what @MattiKloepper says and found the same results. However I modified the experiment a bit:
```

protected override void Draw(GameTime gameTime)
{
    GraphicsDevice.Clear(Color.CornflowerBlue);

    for (int i = 0; i < 10000; i++)
    {
        // Create a new VertexBuffer.
        VertexBuffer v = new VertexBuffer(this.GraphicsDevice, typeof(VertexPositionNormalTexture), 1000, BufferUsage.WriteOnly);

        // Dispose the new VertexBuffer without ever using it.
        v.Dispose();

    }

	base.Draw(gameTime);
}

```

I reduce the number of iterations by 100 and put them in the Draw. If there was a leak, the program should crash after 100 iterations of Draw, however the amount of memory used is kept at bay.

My bet is that Dispose really disposes the GPU resources, but GraphicsDevice clings to the VertexBuffer reference, and it's not after Draw ends that clears all the internal references to the allocated "v"s. That allows the garbage collector to delete the memory used by "v".

**Comment by Jjagg** [comment] 2020-07-30 23:39
Based on the last comment seems like a driver thing implementation detail (or maybe according to spec). Either way, I don't think we can do anything to improve this. And if you're running into this, you're already doing something very wrong.

Don't allocate vertex buffers every frame and reuse them where possible.

Closing this :)

**Closed by Jjagg** 2020-07-30 23:39 UTC
Labels: DirectX

**Comment by willmotil** [comment] 2020-08-01 01:47
Number of things wrong with this test and a number of bad assumptions in case anyone ever takes a look at this again.

Here are a few things to think about first.

1) Who owns the gpu's memory are we assuming that calling dispose is like calling some c++ free memory.
2) Do you think you can control the disposal and reclaimation of the gpu's resources by simply calling dispose.
3) How fast and how much memory have you told the gpu to allocate in that loop.
4) How much memory does your gpu have ?

5)  IsDisposing() just cause you call dispose on a vertex buffer or even a texture doesn't mean the gpu or the os can just insta re-claim that memory or will or that its ok to just drop or reassign to that reference.

**This code works perfectly** it simply instructs the gpu to flood itself with memory allocations until it runs out of memory.
That is the behavior i would **expect** and the outcome i would expect, because that is what this code says to do.
A out of memory exception ... congratulations you found out how to cause one on the GPU itself and that is were its being thrown from you can bet on it.

**Comment by MatthiasKloepperQC** [comment] 2020-08-01 23:30
Thanks for deleting the last sentence from your original post @willmotil. Sounds much more objective now ;-) and gives me the chance to thank you for the concrete food for thought 👍 But I suspect there is a slight misunderstanding about the scope of the "problem" I originally posted. This is the only reason why I continue this thread with another comment ;-)

Of course, the test code is far from a real world szenario, but boils down a "problem" that I had observed: The process memory reserved for a VertexBuffer seemed to not be released again, although the memory on the graphics card was handled fine. Maybe the original description was not precise enough. The comment on "E_OUTOFMEMORY" was just meant to show that the problem was *not* GPU memory, but that I thought Monogame internal references might be the cause of my observations. By running the first loop I can force the memory consumption of the process to climb to around 20 GB before it throws while my GPU supports just 1 GB.
This "problem" was also observed when explicitly forcing the garbage collector to clean up, leaving more time between reservations, or allowing the system to track other execution threads in the meantime. So I suspected a possible memory leak within Monogame itself here.

The observation of @KakCAT that the process memory for the disposed vertex buffers is actually freed after a Draw() call, seems to be correct and actually solves the "problem". I hadn't noticed that at the time.

Ergo: No memory leak here. Keep up the good work. It's really appreciated.

**Comment by willmotil** [comment] 2020-08-02 01:53
`The comment on "E_OUTOFMEMORY" was just meant to show that the problem was not GPU memory`
How do you know it is not? How do you know that oom exception isn't thrown back from the gpu thru the driver to the os and from there to your application?

Doesn't it seem much more likely that the Gpu will run out of memory before the applications allotted virtual memory space (ram) does.

Think about this from the opposite way around consider how many applications you can have open at once all using enough resources that all there texture and vertex buffer memory can't possibly be in the gpu at the same time.  So the gpu has mechanisms for shifting memory off to the ram and even to virtual memory.

Lets say you wanted to prove that you could cause your gpu to run out of memory and you wanted to show exactly how to do it. 
Aka you want to prove you can cause a OOM exception on the gpu. 
You are going to fill up the memory of the gpu but you can't control the gpu or stop it from unloading data and putting it off to the ram.  How do you do it?

This is why i say your example isn't a real world problem it's not even a valid test.

Doing this ... `Resetting the device reclaims memory.`   
Is that what this does ?  
Shouldn't it be called Reclaim memory then ?

Can you describe were and how that memory is reclaimed by the gc the driver or the gpu.
Is it reclaimed immediately by all three.

The test itself is cheating by calling reset anyways it makes the test pointless and invalid and no one would do this every frame and for plenty of good reasons all that is really doing is basically disconnecting the references between the ram and gpu's memory so the gpu doesn't have to throw memory back to the system as it runs out of space.

The assumption here is that it is expected or there is some guarantee that you somehow control the gpu's memory management 
You are sending a loop of hundreds of thousand of allocations each frame which aren't dynamic using reset and not using dynamic vertex buffers. 

None of that makes any sense to do in a real situation none of it. 
So what does it possibly prove.

for (int i = 0; i < **1000000**; i++)
            {
                // Create a million new VertexBuffers then reset the device.
                VertexBuffer v = **new VertexBuffer**(this.GraphicsDevice, typeof(VertexPositionNormalTexture), 1000, BufferUsage.WriteOnly);

Seriously ?

**Comment by MatthiasKloepperQC** [comment] 2020-08-02 08:24
Actually I had already tried to end this discussion with my last post ;-)
Not sure where the attitude how are showing in your unedited posts comes from. Just wanted to help a little bit. That the behaviour I observed is no problem has already been made clear by @Jjagg with a friendly close. Your additional background insights are enlightening as I'm keen to learn a little of your obviously much deeper insight into this project and graphics programming in general. But somehow your tone of voice does not work well to motivate people to contribute.

Since there is no added value in continuing this discussion I really think we should let it die. No offence but I hope we will get along better on any future issues ;-)

**Comment by willmotil** [comment] 2020-08-03 05:04
Don't take offense im only trying to point out that this particular code itself is potientially dangerous beyond the assumptions made. As well as that if you or someone else in the future is trying to do something like this in reality it needs to be rethought.
