### ISSUE TITLE
Dead area in landscape mode Windows Phone 10

### ISSUE THREAD

**Issue by HeshamMeneisi** [MonoGame/MonoGame#4100] opened 2015-08-25 19:03 UTC
There's a considerably large area on the right part of the screen that is touch insensitive.

Even weirder that area when tapped actually produces multiple taps on the edge of the working area.

This seems like some sort of scaling gone wrong.

**Comment by danzel** [comment] 2015-08-26 21:48
Maybe a duplicate of #4099 ?

**Comment by HeshamMeneisi** [comment] 2015-08-27 02:25
No this is a different problem here. This issue is exclusive to landscape mode and every touch inside that rectangle on the far right of the screen is considered 1-4 touches on its invisible border around 1/3 of the screen from right. I didn't have #4099 happen with me maybe it is only observable on FHD screens, I have yet to try debugging in FHD. 
I have also found some random video on youtube that had a description of this same issue on WP8 and states the reason being that some code somewhere renders the graphics to a RenderTarget then rotates which makes the touch coordinates wrong and changing that fixes the issue. I have, however not found that code and the owner of that video didn't say any details. This actually looks like the problem since I noticed the touch locations are on that invisible border because they are all less than 1px apart.

**Comment by KakCAT** [comment] 2015-08-27 09:19
Hi,

I can confirm this bug too. Just take the example code from #4099 and rotate the phone to make it landscape (it's happenning on both emulator and 630 with latest windows 10 mobile preview). Also, sometimes the time it takes to rotate the display is very big ( probably related to #3948 )

**Comment by nkast** [comment] 2015-08-28 23:21
@kakCAT just an idea for Edit2, perhaps orientation lock affects the behavior of the bug?

**Comment by KakCAT** [comment] 2015-08-29 09:12
I don't think so, I'm positive I didn't use the orientation lock while doing the tests :(

**Comment by gverkade** [comment] 2015-11-04 08:55
I can confirm this problem. About half of the right hand side of the screen produces produces false coordinates.

**Comment by mrhelmut** [comment] 2024-07-03 15:07
Cleaning this as UWP is getting deprecated #8406

**Closed by mrhelmut** 2024-07-03 15:07 UTC
Labels: Windows 10 UWP, Needs Testing, Input
