### ISSUE TITLE
SharpDX.RawInput.dll

### ISSUE THREAD

**Issue by MarvinCZ** [MonoGame/MonoGame#2110] opened 2013-10-27 15:56 UTC
Hello guys I just install monogame, create new project and run and i get tis error:
Could not load type 'SharpDX.Win32­.MessageFilter­Hook' from assembly 'SharpDX, Version=2.5.0.0, Culture=neutral, PublicKeyToken=nu­ll'
Can you tell me what to do?
btw XNA works fine in this way

**Comment by nkast** [comment] 2016-11-08 08:56
Same issue with sharpDX 2.6.3 and latest MG develop 3.6.1089
http://community.monogame.net/t/could-not-load-messagefilterhook/1311/2

**Comment by robintheilade** [comment] 2017-05-18 14:35
I realize this issue is old but I have an issue that looks like the same.

![image](https://cloud.githubusercontent.com/assets/1859029/26207377/a0867f98-3be7-11e7-894d-5541204380a4.png)

I just installed MonoGame 3.6.01625 and I use Visual Studio 2015.

I can confirm that by adding a reference to SharpDX.RawInput.dll the exception does not reappear.

Is there a reason the reference is not part of the Windows template?

**Comment by nkast** [comment] 2017-05-18 14:48
@robintheilade Which platform is that? Windows desktop ?
Is that a new project from the VS2015 template or an old project? Do you have any libraries that also reference Monogame and or SharpDX?

**Comment by robintheilade** [comment] 2017-05-18 16:25
@nkast, I'm on Windows 10 Creators Edition.
The project was created from scratch using the Windows template without the use of nuget packages. Just to verify, the csproj file contains this element "&lt;MonoGamePlatform&gt;Windows&gt;/MonoGamePlatform&gt;".
I have not modified the project in any way after it creation so no other libraries are loaded into the project.

I've extracted the template zip file (Windows.zip) and the MonoGameWindowsApplication.csproj also does not reference the missing assembly. The reference is also missing the [the current github version](https://github.com/MonoGame/MonoGame/blob/1c09add4a7407cf14690614d5ec36666d6c2a8ea/ProjectTemplates/VisualStudio2010/Windows/MonoGameWindowsApplication.csproj).

**Comment by robintheilade** [comment] 2017-05-18 16:43
Just checked a project I have been working on for a long time. It worked when I used MonoGame 3.5 and back then it was not referencing SharpDX.RawInput. That said the assembly was found in the bin folder so maybe I copied it there myself. If I delete it, it does not show up again if I recompile.

**Comment by robintheilade** [comment] 2017-05-19 17:38
Another update, maybe it will help.

I reinstalled the previous version of MonoGame (3.5.1.1679) without uninstalling 3.6. That made the projects run just fine. Installing 3.6 again, made the projects throw the exception.

In both versions I only have SharpDX.RawInput.dll files in the following two folders (ignoring the project specific folders)
C:\Program Files (x86)\MonoGame\v3.0\Assemblies\Windows
C:\Program Files (x86)\MSBuild\MonoGame\v3.0\Tools

All the projects are x86 by the way.

**Comment by nkast** [comment] 2017-05-19 20:26
@robintheilade I don't think that's the same issue as the original.
Also you don't need to reference any of the SharpDX libraries, VS will make sure to copy all satellite libraries along with MonoGame.Framework.dll. 

I installed MG 3.6 and created a new Windows project from VS 2015, Windows 10. The project builds and run. Everything is fine. Can't reproduce. 

What's interesting is that the bin folder doesn't have the file SharpDX.RawInput.dll. And I was able to build and run the project after I deleted it from both "C:\Program Files (x86)\MonoGame\v3.0\Assemblies\Windows" & "C:\Program Files (x86)\MSBuild\MonoGame\v3.0\Tools".
Maybe the compiler know that it's not used although it's referenced by MonoGame.Framework.dll.

The one in "C:\Program Files (x86)\MonoGame\v3.0\Assemblies\Windows" is v2.6.3.0 
and the one in "C:\Program Files (x86)\MSBuild\MonoGame\v3.0\Tools" is v2.5.1.0  ?
I don't even know how v2.5.1.0 got in there! maybe a leftover from an older installation.

Also-also, I was able to build MonoGame.Framework.Windows.sln after I deleted RawInput from /ThirdParty/SharpDX/ and removed the reference from the project. MG doesn't really make use of it.

So, I guess your system tries to load all referenced assemblies (some .Net profiler/debugger perhaps?), that's why you need to ref the library in your project (to get it copied to /bin/)

**Comment by robintheilade** [comment] 2017-05-19 20:48
@nkast, spot on. I looked at the modules list when the exception occurred and found that the MonoGame.Framework.dll that was loaded was loaded from a .NET Reflector cache. The assembly had the 3.5 version number. Deleting that cache made the project work under 3.6 without the reference to SharpDX.

Just to answer your other question, though maybe irrelevant now; both assemblies located in C:\Program Files (x86)\MonoGame\v3.0\Assemblies\Windows and C:\Program Files (x86)\MSBuild\MonoGame\v3.0\Tools are 2.6.3.0 on my machine.

Thank you for helping me.

**Comment by nkast** [comment] 2017-05-19 20:56
@robintheilade Great!

**Comment by tomspilman** [comment] 2017-05-28 01:37
Closing this issue... thanks @nkast & @robintheilade !

**Closed by tomspilman** 2017-05-28 01:37 UTC
