### ISSUE TITLE
Pipeline tool/mgcb does not support asset renaming

### ISSUE THREAD

**Issue by theZMan** [MonoGame/MonoGame#2999] opened 2014-09-18 18:04 UTC
XNA allows an asset name to be specified in the content project which is used instead of the truncated filename for the asset

e.g. you can have a file called 
MyMusic (16-bit).mp3

With an asset name of 
ThemeSong

And the resultant file will be ThemeSong.xnb not My Music (16-bit).xnb

We've worked around it by renaming the file for now but it would be nice to support that feature.

**Comment by tomspilman** [comment] 2015-04-21 18:09
There is a PR for this...  I need to refresh and merge it.  https://github.com/mono/MonoGame/pull/3009

**Comment by cra0zy** [comment] 2018-03-03 00:11
This is a duplicate of: #5109

**Closed by cra0zy** 2018-03-03 00:11 UTC
