### ISSUE TITLE
Referencing MonoGame DesktopGL project from Content Pipeline Extension project breaks all references

### ISSUE THREAD

**Issue by Sarund9** [MonoGame/MonoGame#7411] opened 2020-11-29 19:05 UTC
How to Reproduce:
1. Create new MonoGame project (Cross Platform Desktop application)
2. Add new project to solution: Content Pipeline Extension
3. Content Pipeline Extension: Right click dependencies and add a Dependency to the Main Project
4. The reference should have a Warrning sign, and it will not work
5. Closing and Reopening visual studio results in the Pipeline project having the same error on ALL references. Including System; and Microsoft.CSharp; 
6. Removing the reference to the Main Project instantly fixes everything.

This also happens if you try to reference the Main Project with any C#.NET Framework Project Template (Tested Console Application and Class Library)

Possibly caused by the new .NET Core in 3.8, causing incompatibility with .NET Framework?

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8

#### What operating system are you using:
- Windows 7

#### What MonoGame platform are you using:

- DesktopGL

**Comment by harry-cpp** [comment] 2020-11-30 08:08
You seem to be doing something wrong, most likely:
> Content Pipeline Extension: Right click dependencies and add a Dependency to the Main Project

if you did not make a separate project for holding all the code in a shared / library project but instead only have the executable project, in which case you are trying to reference a .net core project from .net standard project, that will not work.

Either way, it not a bug or a feature request, but a question for the forums/discord, so closing.

**Closed by harry-cpp** 2020-11-30 08:08 UTC
