### ISSUE TITLE
mcgb-editor macOS

### ISSUE THREAD

**Issue by urcereal** [MonoGame/MonoGame#7513] opened 2021-05-25 11:54 UTC
Hi,

Not sure I'm doing something wrong here. Had to re-install macOS (11.4 broke may unsupported Mac Pro) and when I re-install mgcb-editor I get the below error. This was working prior to the re-installation of macOS so I'm not sure I've missed something. Get the same on macOS 11.2 and 11.4 (MacBook Pro). What am I missing?

?@? ~ % dotnet tool install --global dotnet-mgcb-editor --version 3.8.1.1971-develop
You can invoke the tool using the following command: mgcb-editor
Tool 'dotnet-mgcb-editor' (version '3.8.1.1971-develop') was successfully installed.
?@? ~ % mgcb-editor
Unhandled exception. System.IO.DirectoryNotFoundException: /Users/mjoiner/.dotnet/tools/.store/dotnet-mgcb-editor/3.8.1.1971-develop/dotnet-mgcb-editor/3.8.1.1971-develop/tools/net5.0/any/MGCB Editor.app
   at MonoGame.Content.Builder.Editor.Launcher.MacPlatform.get_LocalAppPath() in C:\BuildAgents\MonoGameWin1\work\f7381a85a626990\Tools\MonoGame.Content.Builder.Editor.Launcher\MacPlatform.cs:line 18
   at MonoGame.Content.Builder.Editor.Launcher.MacPlatform.Run(InvocationContext context, String project) in C:\BuildAgents\MonoGameWin1\work\f7381a85a626990\Tools\MonoGame.Content.Builder.Editor.Launcher\MacPlatform.cs:line 34
   at MonoGame.Content.Builder.Editor.Launcher.Program.<>c__DisplayClass0_1.<Main>b__1() in C:\BuildAgents\MonoGameWin1\work\f7381a85a626990\Tools\MonoGame.Content.Builder.Editor.Launcher\Program.cs:line 36
   at MonoGame.Content.Builder.Editor.Launcher.Program.Main(String[] args) in C:\BuildAgents\MonoGameWin1\work\f7381a85a626990\Tools\MonoGame.Content.Builder.Editor.Launcher\Program.cs:line 77
zsh: abort      mgcb-editor
?@? ~ % 

Cheers,
Martyn

**Comment by japhib** [comment] 2021-05-29 04:08
+1, MGCB-editor also does not work for me on macOS 11.4. I try to launch it from inside Visual Studio for Mac and I get this crash report. I can post a full dump if needed, but it doesn't seem like the logs are very useful (not a C# stack trace)

<img width="982" alt="image" src="https://user-images.githubusercontent.com/11890284/120057559-403a6080-c001-11eb-9a32-bef45d0c9995.png">

**Comment by dominickm** [comment] 2021-06-07 13:11
I am experiencing this issue as well. Why stack trace is the same as @japhib. Any guidance would be greatly appreciated :)

**Comment by rogvc** [comment] 2021-06-09 13:07
I'm on MacOS 11.4 as well and I'm getting the same error. However, thanks to `Owly()` on Discord I learned that there's a CLI version of MGCB that seems to work well for me (so far).

You can install it with: `dotnet tool install -g dotnet-mgcb` and then invoke it with `mgcb`.

However, since I'm not familiar with the CLI tool, I haven't tested it just yet.

**Comment by jnoyola** [comment] 2021-06-22 04:46
This seems related to the net5.0 update. It's looking for the `MGCB Editor.app` folder that's supposed to be added [here](https://github.com/MonoGame/MonoGame/blob/develop/Tools/MonoGame.Content.Builder.Editor.Launcher/MonoGame.Content.Builder.Editor.Launcher.csproj#L16-L31), but the nuget package only contains `mgcb-editor-linux` and `mgcb-editor-windows` folders.

@harry-cpp, any thoughts?

**Comment by mgkcorty** [comment] 2021-06-22 17:37
Same issue, MacOS 11.4.

**Comment by harry-cpp** [comment] 2021-06-23 10:01
The macos version of mgcb editor can't be generated from Windows, its still getting built by the macos buildbox but its artifacts are not getting published.

This will be fixed when we setup github actions for the building and publishing of artifacts.

**Comment by ChrisChou-freeman** [comment] 2021-07-01 02:26
+1

**Comment by zhengying** [comment] 2021-09-11 14:58
> The macos version of mgcb editor can't be generated from Windows, its still getting built by the macos buildbox but its artifacts are not getting published.
> 
> This will be fixed when we setup github actions for the building and publishing of artifacts.

Hi, when will release 3.8.1 to resolve this problem,  Almost all mac developers block by this problem.

**Comment by pixelomer** [comment] 2021-10-08 17:20
Compiling the editor and placing the output files inside the MacOS folder of the broken app bundle seems to work, so the problem is the build process as already mentioned.
![MGCB Editor on macOS Big Sur 11.6](https://user-images.githubusercontent.com/37103802/136597219-2c5fecfc-0156-4185-bdb6-d58d3b697b0b.png)

**Comment by mrhelmut** [comment] 2021-10-13 09:53
cc @harry-cpp

**Comment by japhib** [comment] 2021-11-05 18:10
@derekforeman that dump is absolutely massive, think you could move it to a pastebin or something? Took me half an hour just to scroll to the bottom so I could make this comment

**Comment by derekforeman** [comment] 2021-11-05 18:41
It is large, I doubt half an hour of scrolling. I'm not sure how pastebin eliminates the size or display but, I'm happy to copy and paste it somewhere else. The issue is self evident, it flat crashes. What can I do to help getting it to run?

**Comment by japhib** [comment] 2021-11-05 18:57
The point is just commenting etiquette - if you put it into a pastebin and then edit your comment to just have a link to the pastebin instead of the whole text of the dump, people reading the issue won’t have to scroll through 10k lines of a stack dump they’re most likely not interested in.

> The issue is self evident, it flat crashes. What can I do to help getting it to run?

a C# stack trace of the error would probably point you in the right direction of what needs to be fixed. Maybe you can run it in Debug mode, or from an editor, and see if you can reproduce the error along with a C# stack trace.

**Comment by derekforeman** [comment] 2021-11-05 19:19
I understand the etiquette, the counter etiquette consideration is. It looks like the issue is 7 months old. I'm assuming, not many people are scrolling and not many maintainers are interested in fixing. 

Instead of pedantry, I tend to lean toward, thanks for helping with more details, here is how you can help fix the issue with us and next time would you mind using paste bin.

**Comment by Lajbert** [comment] 2021-11-12 09:01
Hello guys, any update on this? I bought a macbook yesterday because I didn't realise that there are monogame issues.
Whatever fix I try to follow, nothing works.
Please, is there a fix upcoming any time soon? Or would it be possible to release some small patch, workaround or anything like that to unblock mac users?
I really, really would not like to throw 1 year of work into the trash can because of such a small issue that could be fixed so easily.

**Comment by jamesturk** [comment] 2021-11-12 20:38
I have a build that seems to work if others want to try it

[MGCB Editor.zip](https://github.com/MonoGame/MonoGame/files/7530284/MGCB.Editor.zip)

extract & run 

(Can't really provide support, but works for me on macOS 11.6 on a 2018 Macbook Pro)

**Comment by Lajbert** [comment] 2021-11-12 22:30
Thank you so much! When I just double click on it, it works fine, but how can I make the build command use this version instead of the one from nuget? Or how can you use it with existing project? I tried opening my content file with it, but when I say build, it says mgcb is not on the path (it is, mgcb-editor command pops up the nuget editor which exists with error)

**Comment by Apostolique** [comment] 2021-11-13 06:31
@Lajbert is it only the GUI editor that can't build or can you also not compile the game with the command line?

If it's only the GUI, you could use it to add the contents but leave the building to happen when you build your game. (`MonoGame.Content.Builder.Task` in your game's csproj)

**Comment by pixelomer** [comment] 2021-11-13 06:34
`mgcb` should work fine, only `mgcb-editor` is broken. And as others said, you shouldn't need to build it yourself anyway.

**Comment by Lajbert** [comment] 2021-11-13 19:57
@Apostolique 

actually, I also have problems with simply just building process as well.
I get the following error when trying to build my project:

/Users/lajos/.nuget/packages/monogame.content.builder.task/3.8.0.1641/build/MonoGame.Content.Builder.Task.targets(5,5): Error MSB3073: The command "dotnet /Users/lajos/.nuget/packages/monogame.content.builder.task/3.8.0.1641/build//../tools/netcoreapp3.1/any/mgcb.dll /quiet /@:"/Users/lajos/Documents/GameDev/MonolithEngine/Engine/Content/Content.mgcb" /platform:DesktopGL /outputDir:"/Users/lajos/Documents/GameDev/MonolithEngine/Engine/Content/bin/DesktopGL/Content" /intermediateDir:"/Users/lajos/Documents/GameDev/MonolithEngine/Engine/Content/obj/DesktopGL/Content" /workingDir:"/Users/lajos/Documents/GameDev/MonolithEngine/Engine/Content/"" exited with code 1. (MSB3073) (PlatformerNetStandard)

Is this familiar to anyone?

**Comment by gavrilyuc** [comment] 2021-11-19 12:03
I have the same problem.
I used this [Guide](https://docs.monogame.net/articles/getting_started/1_setting_up_your_development_environment_macos.html)

Installed Visual Studio Mac and mrcb-editor (before to github issue I was installed mgcb by `dotnet tool install -g dotnet-mgcb`) and created new project.

After that I was trying open `Content.mgcb` file but I get:
![image](https://user-images.githubusercontent.com/9469728/142619103-23979087-60a2-4fc1-a460-4c1d4ae0ffe5.png)

When I trying open `mgcb-editor` by terminal I saw opening shortcut icon then the icon was hided.

How can I using Visual Studio Mac with mgcb editor?


> I have a build that seems to work if others want to try it
> 
> [MGCB Editor.zip](https://github.com/MonoGame/MonoGame/files/7530284/MGCB.Editor.zip)
> 
> extract & run
> 
> (Can't really provide support, but works for me on macOS 11.6 on a 2018 Macbook Pro)
> 
> (if you don't have the .NET 5.0 SDK installed it will open & close without error, but installing the .NET 5.0 SDK made it work on a fresh OSX system)

It is works only when I using this app without visual studio (but I can't build Content project, mgcb does not found. But I was installed by [Guide](https://docs.monogame.net/articles/tools/mgcb.html) and it works in terminal).

**Comment by gavrilyuc** [comment] 2021-11-19 17:40
Have any idea how to fix this exception? macOS 11.6
```sh
An unhandled exception has occurred. Terminating Visual Studio? False
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentOutOfRangeException: Font Family specified is not supported by this system
Parameter name: familyName
Actual value was .AppleSystemUIFont.
```

**Comment by ayousuf23** [comment] 2021-12-17 15:44
@harry-cpp What’s the status on the issue? If anything needs to be done, let me know what I can do.

**Comment by JonasEmre** [comment] 2021-12-30 22:47
Still there is no update. Is there any full documentation? At least I want to try to add contents manual? do I have to use /build: command with file path?

**Comment by Lajbert** [comment] 2021-12-31 08:41
That is what I'm doing now, I'm using the zip from the above comment and use the content builder from command line to build it, it works fine.

**Comment by hoqqanen** [comment] 2022-01-16 02:00
+1 to fixing this.

I'm new to monogame and this made starting out on a mac a poor experience as it breaks the tutorial.

**Comment by seand88** [comment] 2022-01-17 21:02
same issue new to monogame can't get past beginning steps.

**Comment by Lajbert** [comment] 2022-01-18 09:53
> same issue new to monogame can't get past beginning steps.

Where are you stuck exactly? Maybe I can help, I'm doing MonoGame development on Mac.

**Comment by Lajbert** [comment] 2022-01-18 10:18
> same issue new to monogame can't get past beginning steps.

Actually I decided to do a quick write-up on the topic:
https://lajbert.github.io/blog/mac_os_issues/#/

Hope it helps!

**Comment by cpt-max** [comment] 2022-01-20 03:31
I built a custom version of the MGCB editor for the compute shader fork. It should become a nuget eventually, but for now here is the [zipped app bundle](https://www.dropbox.com/s/mjp2lopww4cbnlu/MGCB%20Editor.app.zip?dl=1). It can build content. Shaders are built for the compute fork, but everything else should be compatible with current MonoGame. 

I tested it on M1 and x64 (Big Sur in both cases). You need to have .Net 5 installed. On M1 that means installing the x64 runtime, as there is no .Net 5 SDK for Arm.

**Comment by ericlothspeich** [comment] 2022-02-04 06:01
Oh wow! It works! Thank you so much @cpt-max !

**Comment by 1971S** [comment] 2022-03-29 22:32
> I built a custom version of the MGCB editor for the compute shader fork. It should become a nuget eventually, but for now here is the [zipped app bundle](https://www.dropbox.com/s/h4448bafzyul49m/MGCB-Editor.tgz?dl=1). It can build content. Shaders are built for the compute fork, but everything else should be compatible with current MonoGame.
> 
> I tested it on M1 and x64 (Big Sur in both cases). You need to have .Net 5 installed. On M1 that means installing the x64 runtime, as there is no .Net 5 SDK for Arm.
> 
> This is not a signed app, so on newer OSX versions you need to remove the quarantine attribute after extracting, otherwise it won't launch and you get a message that the app is damaged.
> 
> ```
> xattr -d com.apple.quarantine /PathTo/MGCB-Editor.app 
> ```

Apologies for the bother, but I downloaded and followed your steps and the editor just won't open. For reference, It's a 2018 macbook pro with Monterey 12.3 and the app has been successfully unquarantined, but it just won't open when I right click content.mgcb and then Open with -> Your program.

Was wondering if I am maybe forgetting some other step.

Thanks in advance!

**Comment by cpt-max** [comment] 2022-03-30 01:23
@1971S Does it only fail when you do "open with", or also when you launch it normally?

**Comment by 1971S** [comment] 2022-03-30 09:12
> @1971S Does it only fail when you do "open with", or also when you launch it normally? What's your output when you do `dotnet --list-sdks` in a terminal?

First of all, thanks for the help.

When I try opening content.mgcb by double-clicking it inside VS, I see this:

<img width="260" alt="image" src="https://user-images.githubusercontent.com/39523503/160795798-251896a3-08cd-4ea5-b9a4-280d848182c2.png">

The output when running `dotnet --list-sdks` is:
<img width="408" alt="image" src="https://user-images.githubusercontent.com/39523503/160795945-a3aca23d-b7da-4a13-acf9-4623312f8dd0.png">

Thanks again.

**Comment by 1971S** [comment] 2022-03-30 10:00
> @1971S You need .NET 5, you only have 3 and 6 installed.

Brilliant, that worked. Apologies, assumed having .NET 6 would work retroactively for 5. Thanks!

**Closed** 2022-04-27 08:50 UTC

**Comment by BruceMcRooster** [comment] 2022-07-29 20:03
Hate to be that guy that reopens it, but I'm using a brand new M1 MacBook Air and I've been trying all afternoon to get this to work and I can't get the mgcb-editor to open. I've tried it from Visual Studio, VSCode using the extension, and from the command line, and the best I got at one point, and I can't remember what I did, was an error message saying it had quit unexpectedly. Otherwise, it has been completely silent, just not opening any windows or doing anything.

**Comment by harry-cpp** [comment] 2022-07-29 20:24
You need to install x64 version of .NET 6 for it to work on an M1 macOS: https://dotnet.microsoft.com/en-us/download/dotnet/6.0

Don't worry about installing x64 .NET runtimes/sdks breaking something, they get installed into their own folders.

**Comment by felixosth** [comment] 2022-08-03 21:13
> You need to install x64 version of .NET 6 for it to work on an M1 macOS: https://dotnet.microsoft.com/en-us/download/dotnet/6.0
> 
> Don't worry about installing x64 .NET runtimes/sdks breaking something, they get installed into their own folders.

I have the same problem as @BruceMcRooster but I'm using the M2 MacBook Air. I tried to download the x64 version and install it but it's never listed in my runtimes.

```
dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.302
 Commit:    c857713418

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.5
 OS Platform: Darwin
 RID:         osx.12-arm64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.302/

global.json file:
  Not found

Host:
  Version:      6.0.7
  Architecture: arm64
  Commit:       0ec02c8c96

.NET SDKs installed:
  6.0.302 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
```
