### ISSUE TITLE
Enter ? on german keyboard

### ISSUE THREAD

**Issue by regaaa** [MonoGame/MonoGame#5910] opened 2017-08-30 17:12 UTC
Hi all,

first of all: That is a really great framework. But there is one thing I stumbled upon: How am I supposed to type in for example the question mark on a german keyboard? 

`KeyboardState = Keyboard.GetState();
var pressedKeys = KeyboardState.GetPressedKeys();`

...give me nothing when pressed the question mark or other special char buttons on my keyboard. Cannot image I am the only one with such a problem.

But other than that I really need to find a workaround for that. Wasted all day to find sth., even more low-level. How do you accomplish such a task, if you are on a non US keyboard layout?

**Comment by Jjagg** [comment] 2017-08-30 18:15
Duplicate of #5715

**Comment by Scellow** [comment] 2017-08-30 19:01
I suppose you want that input for UI stuff, what i did was to use TextInput instead (from Window)

**Comment by Jjagg** [comment] 2017-08-30 19:18
Most core contributors are actually not from the US.
I'm from Belgium where most people have an AZERTY keyboard. Of course MG devs care, but we have only so much spare time to go around and there are other issues that have a higher priority. Any help to tackle this issue would be greatly appreciated :)

**Comment by Scellow** [comment] 2017-08-30 19:22
I tried to find a permanent solution last time but i couldn't figure out what to do, i might try again once i have time, you are right this is an open source project after all

**Comment by KonajuGames** [comment] 2017-08-30 21:50
If it is for text input, use the GameWindow.TextInput event. This reports
character input rather than key input. This should work for special
characters as it uses the output from the keyboard driver after modifier
keys have been taken into account.

**Comment by regaaa** [comment] 2017-08-30 23:05
@KonajuGames Thx buddy. That is a nice workaround, at least for me. Maybe I will dive into monogame source code to eliminate the bug.

**Closed** 2017-08-30 23:05 UTC
