### ISSUE TITLE
MonoGame Content Builder exits with 9009 error code if solution path contains spaces

### ISSUE THREAD

**Issue by AimedNuu** [MonoGame/MonoGame#6440] opened 2018-09-25 11:09 UTC
Issue: MonoGame Content Builder exits with 9009 error code if solution path contains spaces

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:
- DesktopGL

**Comment by cra0zy** [comment] 2018-09-30 13:15
Duplicate of: #6417

**Closed by cra0zy** 2018-09-30 13:15 UTC
Labels: Help Wanted
