### ISSUE TITLE
Game Crashes On Launch When No Audio Device Exists

### ISSUE THREAD

**Issue by runewake2** [MonoGame/MonoGame#2119] opened 2013-11-07 00:21 UTC
When you call game.Run(); to start your game a NullException is thrown when no audio devices exist. This might occur, for example, when you start your computer with no speakers plugged in.

Our game doesn't use any SoundEffects etc. This seems to occur regardless. Is there some way for us to fix this?

**Comment by tomspilman** [comment] 2016-04-03 21:27
We need someone to test this and make sure it doesn't still occur.  Should be reproducible by disabling the audio devices from the control panel.

**Comment by Tzenchor** [comment] 2016-04-03 21:48
I have tried my WindowsDX project after disabling the devices and it still runs. I can't unplug the speakers as they are part of the laptop

**Comment by mrhelmut** [comment] 2016-04-03 21:53
I believe the OpenAL implementation will crash. (see: https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Audio/OpenALSoundController.cs#L455)

I'll try to take a look at this.

**Comment by cra0zy** [comment] 2018-03-03 13:27
This is a duplicate of #4717

**Closed by cra0zy** 2018-03-03 13:27 UTC
Labels: Help Wanted
