### ISSUE TITLE
Can't hide mouse cursor

### ISSUE THREAD

**Issue by mikea314** [MonoGame/MonoGame#6180] opened 2018-02-10 18:21 UTC
Setting IsMouseVisible = false doesn't hide the mouse cursor

MonoGame.Framework.WindowsUniversal
3.7.0.1248-develop

**Comment by cra0zy** [comment] 2018-03-10 11:11
Hmm, I can't seem to reproduce this one.

**Comment by mikea314** [comment] 2018-03-10 12:31
Thanks for taking a look cra0zy.
It's still happening for me on the latest Dev build.
Initially, the mouse cursor is hidden, but the moment I move the mouse it re-appears.

**Comment by cra0zy** [comment] 2018-03-10 12:36
Can you make a minimal example that reproduces the issue?

**Comment by mikea314** [comment] 2018-03-10 12:55
Will do

**Comment by mikea314** [comment] 2018-03-10 13:21
Here's a link to the download.
https://www.dropbox.com/s/ke3vgkh6zs0ch8n/MouseTest.MG.zip?dl=1

**Comment by cra0zy** [comment] 2018-03-10 13:50
Oh, I see whats causing the bug...

**Comment by cra0zy** [comment] 2018-03-10 14:26
I don't have time to dig into this right now, but the bug is getting caused by the Xaml template, however it is not getting caused by the Core template.

**Comment by mikea314** [comment] 2018-03-10 14:56
No hassles, thanks for having a look

**Comment by Jjagg** [comment] 2020-04-13 20:49
Fixed in #6180.

**Closed by Jjagg** 2020-04-13 20:49 UTC
Labels: Windows 10 UWP
