### ISSUE TITLE
Installer does not install all needed dependencies

### ISSUE THREAD

**Issue by albertofustinoni** [MonoGame/MonoGame#5738] opened 2017-05-27 05:39 UTC
On the latest stable version, it is impossible to create SpriteFonts using the pipeline tool if `Microsoft Visual C++ 2012 redistributable (x86)` is not installed on the system already.

Creating a .spritefont definition file in a content project causes building to fail with the pipeline tool complaining about `freetype6.dll` missing.

This can be solved by manually installing the package mentioned above, however the installer should take care of it.

**Comment by mrhelmut** [comment] 2017-05-27 09:26
Duplicate of #5736 & #4485

Thanks for reporting it. Would you mind closing this one and following the discussion in #4485?

**Comment by albertofustinoni** [comment] 2017-05-27 09:41
Closed. Apologies for reporting a dupe

**Closed** 2017-05-27 09:40 UTC

**Comment by tomspilman** [comment] 2017-05-28 01:50
@albertofustinoni - Always report... and thanks for doing so.  We would rather have a bug reported multiple times than not at all which happens too often.
