### ISSUE TITLE
OpenGl 3.1 not creating graphic device.

### ISSUE THREAD

**Issue by shmellyorc** [MonoGame/MonoGame#5619] opened 2017-03-24 16:32 UTC
I am using the current developer monogame api. I got a customer that has openg 3.1 and isn't able to run the game. Error resolve around the user doesn't have opengl 3.0 or higher.

Does the current developer api require opengl greater than 3.0 or am I wrong and monogame uses a higher opengl version higher than 3.1?

The user has an intel HD graphics 3000 laptop pc.

ERROR log:
[2017-03-19 @ 16:36:43.238] [launch/native] err: 
[2017-03-19 @ 16:36:43.250] [launch/native] err: Unhandled Exception: **Microsoft.Xna.Framework.Graphics.NoSuitableGraphicsDeviceException: Failed to create graphics device! ---> System.PlatformNotSupportedException: MonoGame requires OpenGL 3.0 compatible drivers, or either ARB_framebuffer_object or EXT_framebuffer_object extensions.Try updating your graphics drivers.**
[2017-03-19 @ 16:36:43.251] [launch/native] err:    at OpenGL.GraphicsContext..ctor(IWindowInfo info)
[2017-03-19 @ 16:36:43.251] [launch/native] err:    at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformSetup()
[2017-03-19 @ 16:36:43.252] [launch/native] err:    at Microsoft.Xna.Framework.Graphics.GraphicsDevice.Setup()
[2017-03-19 @ 16:36:43.252] [launch/native] err:    at Microsoft.Xna.Framework.Graphics.GraphicsDevice..ctor(GraphicsAdapter adapter, GraphicsProfile graphicsProfile, PresentationParameters presentationParameters)
[2017-03-19 @ 16:36:43.255] [launch/native] err:    at Microsoft.Xna.Framework.GraphicsDeviceManager.CreateDevice(GraphicsDeviceInformation gdi)
[2017-03-19 @ 16:36:43.255] [launch/native] err:    at Microsoft.Xna.Framework.GraphicsDeviceManager.CreateDevice()
[2017-03-19 @ 16:36:43.255] [launch/native] err:    --- End of inner exception stack trace ---
[2017-03-19 @ 16:36:43.256] [launch/native] err:    at Microsoft.Xna.Framework.GraphicsDeviceManager.CreateDevice()
[2017-03-19 @ 16:36:43.256] [launch/native] err:    at Microsoft.Xna.Framework.GraphicsDeviceManager.ApplyChanges()
[2017-03-19 @ 16:36:43.258] [launch/native] err:    at SlashyDwarf.SlashyDwarfGame.ToggleFullScreen(Game game) in C:\Users\Owen\Dropbox\Monogame\SlashyDwarf\Client\SlashyDwarfGame.cs:line 43
[2017-03-19 @ 16:36:43.259] [launch/native] err:    at SlashyDwarf.SlashyDwarfGame..ctor() in C:\Users\Owen\Dropbox\Monogame\SlashyDwarf\Client\SlashyDwarfGame.cs:line 21
[2017-03-19 @ 16:36:43.259] [launch/native] err:    at SlashyDwarf.Program.Main() in C:\Users\Owen\Dropbox\Monogame\SlashyDwarf\Client\Program.cs:line 16
[2017-03-19 @ 16:36:43.387] [launch] error while launching 1a7a7060-7cef-4e1a-90af-423790cbe23e: application crashed. process exited with code 3762504530
[2017-03-19 @ 16:36:43.397] [launch] crashed with 
[2017-03-19 @ 16:36:43.397] [launch] application crashed. process exited with code 3762504530

**Comment by mrhelmut** [comment] 2017-03-24 17:07
You might be interested by this discussion #5580.

Intel HD3000 should support it, try updating your drivers.

MonoGame requires OpenGL 2.0 and the ARB_framebuffer_object extension (or OpenGL 3.0).

**Comment by mrhelmut** [comment] 2018-10-05 08:43
Duplicate of #6414. Can be closed (cc @cra0zy ).

**Closed** 2018-10-05 09:00 UTC
