### ISSUE TITLE
Each keystroke produces some garbage

### ISSUE THREAD

**Issue by s-m-k** [MonoGame/MonoGame#6360] opened 2018-07-04 02:34 UTC
#### Symptoms:
Each keystroke produces garbage. If you hold the key, the garbage will seem to be generated each time a repeated keystroke is reported by the OS.

#### How to reproduce:
Download the attached .NET Core 2.1 project that contains some diagnostic code: https://phobia.games/experiments/Game1Core.zip

1. Run the project.
2. It should report no allocations per frame.
3. Press (and hold) any alphanumeric key, the program should report some allocations.

#### Possible cause:
https://github.com/MonoGame/MonoGame/blob/b1a49e4ae60eaf62169d08c791d4f9a913b495b3/MonoGame.Framework/SDL/SDLGameWindow.cs#L302

That line creates an object each time a system's key stroke event is handled, regardless of whether the programmer actually utilizes the `Window.TextInput` event or not.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- Windows 10

#### What MonoGame platform are you using:

- DesktopGL

**Comment by tomspilman** [comment] 2018-07-04 02:37
That is pretty strange and bad.  @cra0zy @dellis1972 ?

**Comment by cra0zy** [comment] 2018-07-04 19:46
I can't repro it on Linux, I've tried holding it, I've tried pressing it like @cra0zy, nothing works :|

Also don't see any obvious suspects, tho we are doing some funky stuff with TextInput in SdlGamePlatform (and Window as well).

**Comment by cra0zy** [comment] 2018-07-04 19:48
Oh wait, not a memory leak, just garbage, nevermind, PR will be up in a moment.

**Comment by nkast** [comment] 2018-07-05 18:15
This is a problem on the WinForms/DesktopDX as well.

**Comment by tomspilman** [comment] 2018-07-05 18:17
Well maybe we should talk about breaking change and making `TextInputEventArgs` not a class?

**Comment by cra0zy** [comment] 2018-07-05 18:55
I have an even better solution... give me a moment I'm gonna cook up something.

**Comment by cra0zy** [comment] 2018-07-05 19:15
PS. Microsofts C# "guidelines" for making events basically tells you to do pointless allocation: https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/event

**Comment by cra0zy** [comment] 2018-07-05 19:35
scroll down:
```
✓ DO use System.EventArgs or its subclass as the type of the second parameter of the event handler, and call it e.
```

**Comment by tomspilman** [comment] 2018-07-05 19:42
The point is we are not the typical .NET application.   If we can use `struct` we should regardless of design guidelines written 10 years ago.

**Comment by cra0zy** [comment] 2018-07-05 19:52
Right now I'm playing around with the idea of adding `TextInput` as an extra field to the `KeyboardState`.

**Comment by tomspilman** [comment] 2018-07-05 19:58
> adding TextInput as an extra field to the KeyboardState.

Not sure about that path... but ok.

**Comment by cra0zy** [comment] 2018-07-05 20:01
Its equally as bad as making `TextInputEventArgs` a struct, isn't it?

**Comment by Halofreak1990** [comment] 2018-07-06 08:39
Wouldn't it be better to refactor the code to only create a TextInputEventArgs object when the event is actually used? Instead of a TextInputEventArgs object, pass the Char and Key to OnTextInput and let the base class handle the creation of the TextInputEventArgs for the event.

**Comment by tomspilman** [comment] 2018-07-09 20:31
>Its equally as bad as making TextInputEventArgs a struct, isn't it?

No i don't think that at all.  To me `KeyboardState` has nothing to do with `TextInputEventArgs`... it just doesn't make sense to me to merge them.

**Comment by cra0zy** [comment] 2018-07-09 20:42
Oh, I see, I was only thinking about performance wise.

**Comment by EnemyArea** [comment] 2018-07-10 16:30
@cra0zy could you explain why a struct type would be bad? If it is like tha CancelEventArgs I would understand it. Is there any technical issue I don't get?

**Comment by cra0zy** [comment] 2018-07-10 18:32
> @cra0zy could you explain why a struct type would be bad? If it is like tha CancelEventArgs I would understand it. Is there any technical issue I don't get?

Because C# should have an object of type `EventArgs` as an argument for an event. Look at MS C# guidelines above.

**Comment by gsfreema** [comment] 2018-07-11 12:33
I thought you guys might be interested in seeing that even Microsoft struggled with this question.
https://blogs.msdn.microsoft.com/kcwalina/2005/09/21/value-type-eventargs/

If you look at EventHandler<TEventArgs>, they did end up removing the EventArgs constraint on the generic parameter.  They must have found some value in using a struct in special cases though I can't say whether this was in a public API or only internal events.
https://referencesource.microsoft.com/#mscorlib/system/eventhandler.cs,96ed969784b9d510

**Comment by gsfreema** [comment] 2018-07-11 16:50
This might be of use as well.
https://docs.microsoft.com/en-us/dotnet/csharp/modern-events

**Comment by jessefreeman** [comment] 2018-08-01 12:07
Hi @tomspilman, I'm new here but have been porting over my fantasy console from Unity to MonoGame. I've been struggling with capturing text input. Currently, my engine relies on Unity's Input.inputString (https://docs.unity3d.com/ScriptReference/Input-inputString.html). This captures the current keyboard input text for that frame and is easy to access.

I agree with @cra0zy that TextInput should be part of the Keyboard state. I think it's strange Window.TextInput is an event when all other input in MonoGame is polling based. My 2 Cents is that I should be able to ask the Keyboard state what the char values of the inputted text for that frame are. I've lost 2 days to this since there is no clear solution online anywhere and this one change would make capturing text input on each frame a lot easier.

**Comment by tomspilman** [comment] 2018-08-01 13:45
> I think it's strange Window.TextInput is an event when all other input in MonoGame is polling based. 

It is the same as why Windows has both [GetKeyboardState](https://msdn.microsoft.com/en-us/library/windows/desktop/ms646299%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396) and the [WM_CHAR](https://docs.microsoft.com/en-us/windows/desktop/inputdev/wm-char) window message.  SDL is designed the same way with events and state methods (likely because it was designed around Windows).

Sometimes you just need to get the current state of the keyboard regardless of when a key was pressed.

Sometimes you need ordered events, key repetitions, and the key translated to a character one would expect when typing words.  For example if you are entering Japanese text... you want the katakana character and not the 3 or 4 keys typed to get that one character.

How i see it one is intended to be used for controller state and the other is intended for input of language.

**Comment by jessefreeman** [comment] 2018-08-01 14:26
Well, the number one struggle I've had is the lack of documentation and direction as to how text input should be handled. The keyboard state stuff is rather straightforward so that was easy to wire up a controller but capturing text input became a little more tedious. I've had to try several different approaches with no direction as to which is the best one. Coming from Unity where Input.inputString was already provided was like taking a big step backward. So something that could have taken me a few minutes to implement required me to create an entire solution around capturing this input text.

Since my fantasy console engine isn't event-based, I was going back and forth over how to approach capturing the text input. I was able to collect it on a frame, then read it on the next frame but I was having issues with lag and knowing when to clear the buffered text. My concern was that if the game dropped frames, would I be able to correctly clear the buffer. Also, the event does not have a time delay to it, so it fires for raw input as it happens so I was getting a lot of duplicated characters.

I agree with your points about needing to know the key order and that Windows supports two ways of capturing this but I think MonoGame could stand to use a little convenience for developers, especially if they are coming over from Unity. The fact that a simple google search for "how to capture text input in MonoGame" doesn't offer much help and even dates back to XNA leads me to believe this is an area that could use a little improvement. I haven't had many roadblocks in my port from Unity to MonoGame but I wasn't expecting to get stuck on capturing text input.

I would expect the game engine I use to consolidate all input into a single easy to access way and text captured during the frame should be part of that. If the developer doesn't want to use it, they can ignore it but for a large percentage of developers looking to just add a simple text input for a name or setting, this would save them writing out additional logic and open up easier ways to tie input field components into the existing controller input polling paradigm.

**Comment by tomspilman** [comment] 2018-08-01 17:06
> lack of documentation 

That has always been an issue with MG since the beginning.  We're working on it, but frankly no one helps with this.

It is my fault i allowed `GameWindow.TextInput` to be merged without better reference documentation. 
 What we have is barely passable:

![image](https://user-images.githubusercontent.com/103522/43533459-7b9bb9b2-957a-11e8-8c65-25e1f346f2cb.png)

https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/GameWindow.cs#L104

> I was able to collect it on a frame, then read it on the next frame but I was having issues with lag and knowing when to clear the buffered text. 

This sounds like something we should fix or at least make consistent.  I guess because the loop looks something like this:
```
while (running)
{
   ProcessEvents();
   while (timeElapsed > tickTime)
     update();
   draw();
}
```
So you might get one event and then 3 or 4 updates.  Maybe this should be fixed to be more like this?
```
while (running)
{
   ProcessEvents();
   var processEvents = false;
   while (timeElapsed > tickTime)
   {
      if(processEvents)
         ProcessEvents();
     update();
     processEvents = true;     
   }
   draw();
}
```

> even dates back to XNA

Yeah `GameWindow.TextInput` was our attempt to make the issue better on desktop.  Looks like we have more we can do to improve it.

> consolidate all input into a single easy to access way and text captured during the frame should be part of that.

I understand the sentiment here, but have concerns with the technical issues involved.  Mainly returning character input requires memory allocations that not everyone wants/needs.

To me `GameWindow.TextInput` is separate because it is something different from `KeyboardState` and one keypress does not equal one character.

**Comment by jessefreeman** [comment] 2018-08-01 17:27
This all makes sense. My only request is to have the input string available as a constant and not an event. But maybe if you fix the event I can capture it at the beginning of the update?

Looking forward to seeing what you come up with!

**Comment by D4v1ks** [comment] 2018-08-05 21:06
Why not just create a private TextInputEventArgs class and reuse it every time the event is fired?
It is 100% guaranteed that it will be reused next.

private TextInputEventArgs _textInputEventArgs = new TextInputEventArgs();

private void OnKeyPress(object sender, KeyPressEventArgs e) {
     _textInputEventArgs.Char = character;
    OnTextInput(sender, _textInputEventArgs);
}

**Comment by D4v1ks** [comment] 2018-08-06 11:15
I tried to replicate the issue above without success.
I think is precipitated to assume there is an issue with how TextInput works. It is pretty straightforward.
GameWindow also looks like the right place for it to be.
Anyway thanks for all the work on Monogame!

**Comment by cra0zy** [comment] 2018-08-06 11:25
> I tried to replicate the issue above without success.

Its not a memory leak, its just pointless allocation of deletion of memory.

**Comment by tamkcr** [comment] 2018-10-31 06:09
I noticed holding down a key (with no keyboard input involved in code) would cause jitter as once every few frames the game loop takes a tiny bit time more than my monitor's refresh rate and eventually have to update physics twice in a single Update() after it accumulates, this issue looks like the culprit.

**Comment by mrhelmut** [comment] 2019-02-07 09:59
I can 100% confirm this issue. It happens even on totally empty projects (not using any keyboard API).

I can also confirm that it is not entirely related to this (but this surely has an impact here as well):
https://github.com/MonoGame/MonoGame/blob/b1a49e4ae60eaf62169d08c791d4f9a913b495b3/MonoGame.Framework/SDL/SDLGameWindow.cs#L302

```new TextInputEventArgs``` sure generates some garbage, but the runtime pooling prevents to be a real issue. The problem is elsewhere.

From my tests, when keys are pressed, it builds about 8KB of garbage per second (this is framerate independent, the garbage depends on the repeating key settings in the OS).

I can see situations where this could be a problem and trigger unwanted garbage collections.

I have found the source of the garbage, it is this string marshalling:
https://github.com/MonoGame/MonoGame/blob/b1a49e4ae60eaf62169d08c791d4f9a913b495b3/MonoGame.Framework/SDL/SDLGamePlatform.cs#L160

Not sure if we can do much about it, but what could be cool to mitigate this, is to skip on handling ```Sdl.EventType.TextInput``` pumped events when there is no event handler attached to ```Game.TextInput```.

**Comment by s-m-k** [comment] 2019-02-07 13:06
Good find. Well, I see that the string in question is only used to generate a series of XNA events, so it would be possible to avoid C# string marshaling completely and generate single `char`s per XNA event as we read the input buffer. Since `String.Length` tells us about the count of `char`s, we probably need to know about only at most 2 bytes per XNA event to make it compliant with the old, wasteful solution.

Of course, we shouldn't trigger the event handler at all if there's no need to do that, since it will also save some CPU resources as well (plus the tiny amount of garbage generated by creating the object).

**Comment by mrhelmut** [comment] 2019-02-07 13:42
> it would be possible to avoid C# string marshaling completely and generate single `char`s per XNA event as we read the input buffer

I'm 100% for this. We'll only have to check how many UTF8 bytes there is, convert them back to individual ```char``` while directly throwing ```CallTextInput```.

**Comment by willmotil** [comment] 2019-02-11 01:33
Nice work.  

Yep right off the bat there is a new in the method block at 165 and a new string at 159 also declared in the block.

**Comment by mrhelmut** [comment] 2019-02-16 16:22
FYI, I've setup'd #6664 which should greatly help here.

**Closed** 2019-02-19 19:08 UTC
Labels: Help Wanted, Input
