### ISSUE TITLE
Add Template for Visual Studio Mac

### ISSUE THREAD

**Issue by Majirefy** [MonoGame/MonoGame#5647] opened 2017-04-07 04:08 UTC
After installation, there are no templates in Visual Studio Mac.

I seems VS Mac will take over Xamarin Studio, because it has all functionality of XS.

**Comment by lenin-interware** [comment] 2017-04-15 20:16
How can i add the Bot Framework Template in Visual Studio for MAC?
https://docs.botframework.com/en-us/downloads/

**Comment by Majirefy** [comment] 2017-04-22 11:33
@lenin-interware 
You mean we can just install it from NuGet?
Create an empty C# project and then install it from NuGet?

**Comment by ShineSmile** [comment] 2017-05-11 02:06
VS for Mac is released today.
I had tried to copy the content from `/Users/shine/Library/Application\ Support/XamarinStudio-6.0/LocalInstall/Addins` to `/Users/shine/Library/Application\ Support/VisualStudio/7.0/LocalInstall/Addins`. It doesn't works well.
The Extension Manager shows:
```
The Following dependencies required by this extension package are not available:
Required: MonoDevelop.Core v6.0, found v7.0
Required: MonoDevelop.Ide v6.0, found v7.0

MonoGame Addin for MonoDevelop
```

**Comment by gingerbeardman** [comment] 2017-10-09 23:10
As a new user I'm stuck at this point as Visual Studio was installed for me.

**Comment by gingerbeardman** [comment] 2017-10-09 23:28
I just found the solution...

- File > Extensions... > Gallery > Manage Repositories > (tick to enable Alpha channel)
- IDE extensions > MonoDevelop.MonoGame.Templates > Install
- enjoy!

ref: http://community.monogame.net/t/add-templates-for-visual-studio-mac/9027/2

![screen shot 2017-10-10 at 00 17 55](https://user-images.githubusercontent.com/49612/31362518-cf048272-ad50-11e7-8d1f-36ff27591236.png)

**Comment by cra0zy** [comment] 2017-10-10 00:28
http://community.monogame.net/t/add-templates-for-visual-studio-mac/9027

**Comment by gingerbeardman** [comment] 2017-10-10 00:31
@cra0zy I posted that link in my comment directly above yours?

**Comment by cra0zy** [comment] 2017-10-10 00:32
Ah, must have not seen it, sorry.

**Comment by eli-crow** [comment] 2017-11-11 21:23
The template seems to not be available anymore.

![screen shot 2017-11-11 at 4 22 17 pm](https://user-images.githubusercontent.com/19712894/32693656-84ecb662-c6fc-11e7-8038-6e3f0a954614.png)

At least one other is having the same problem:
http://community.monogame.net/t/add-templates-for-visual-studio-mac/9027/22

**Comment by gingerbeardman** [comment] 2017-11-11 22:26
My advice is to stick with the last version of Xamarin Studio.

**Comment by iSynth** [comment] 2018-01-08 05:14
It seems that MonoGame comunity/developers do not care about this problem.

**Comment by gingerbeardman** [comment] 2018-01-08 07:33
Thank Microsoft

**Comment by iSynth** [comment] 2018-01-08 09:54
I found a workaround. 

I installed MonoGame and VS on a virtual machine with Windows guest. All the necessary templates appeared in VS. Then I create a new cross-platform version of MonoGame project and saved to disk. Then I transferred the entire project folder to the Mac and opened it in VS for Mac.

**Comment by ColdHam** [comment] 2018-01-20 00:26
It'd be great if we could hear something back about this... was gonna check monogame out, as a mac user I followed the instructions on their documentation for setup, and nada no templates... Guess i'll have to try that workaround, unless anyone else knows a way to easily manually build the project without a template. Haven't used VS in ages myself, or do everything in windows I guess ... >.>

**Comment by p-brighenti** [comment] 2018-01-29 15:47
I'm having this problem as well. I could setup monogame with VS on my windows desktop at home, but I'm having trouble setting it up on my macbook.

**Comment by kurtcz** [comment] 2018-01-31 13:20
The workaround is to also install xamarin studio alongside of vs for mac and create an empty project from xamarin studio (monogame templates install fine in xs). Then open the created project in vs for mac and away you go. That is the only way I know of.

**Comment by itsash--** [comment] 2018-07-04 19:03
I’m not sure if people are struggling to find the templates or not?

It appears now that the templates have moved to **Game Development** and no longer requires the alpha repositories to be turned on.

![screen shot 2018-07-04 at 19 58 16](https://user-images.githubusercontent.com/1327452/42291672-2cda6a14-7fc5-11e8-8644-1a2cd6060774.png)
![screen shot 2018-07-04 at 20 00 28](https://user-images.githubusercontent.com/1327452/42291674-3107b718-7fc5-11e8-8150-9cbf21d4819d.png)

**Comment by gingerbeardman** [comment] 2018-07-04 19:19
@itsash-- seems to have been the case only since 9th Feb 2018 (so after the comment that precedes yours) http://addins.monodevelop.com/Project/Index/47

Good spot, though!

**Comment by harry-cpp** [comment] 2020-03-25 23:26
Duplicate of https://github.com/MonoGame/MonoGame/issues/6695

**Closed by harry-cpp** 2020-03-25 23:26 UTC
Labels: Installer, MacOS

**Comment by gingerbeardman** [comment] 2020-03-26 20:00
@harry-cpp surely #6695 (2 Apr 2019) is a duplicate of this issue, number #5647 (7 Apr 2017) ?
