### ISSUE TITLE
Ubuntu 18.10 Pipeline tool: Content build does not work

### ISSUE THREAD

**Issue by peon501** [MonoGame/MonoGame#6571] opened 2018-12-03 18:53 UTC
Pipeline does not work in Ubuntu :)

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- Ubuntu 18.10

#### What MonoGame platform are you using:
- DesktopGL

#### Tool version:
3.8.0.173

![screenshot from 2018-12-03 20-51-12](https://user-images.githubusercontent.com/1125765/49394919-c54ca380-f73d-11e8-8b26-86775bdc070c.png)

**Comment by Jjagg** [comment] 2018-12-04 11:52
@cra0zy Something to do with .NET Framework version or something?

@peon501 Did you install the mono-complete package with `apt-get`? (https://packages.ubuntu.com/cosmic/mono-complete)

**Comment by peon501** [comment] 2018-12-04 12:13
@Jjagg Ok I will try to install it, I am not a guru at Linux, but if it is a case we should get some kind of error of dependencies in the installation window or it is hard to do?

**Comment by peon501** [comment] 2018-12-04 12:18
@Jjagg Ok it works, now. Ty.

**Comment by Jjagg** [comment] 2018-12-04 14:41
@cra0zy  So seems like the mono check isn't good enough in this case.

**Comment by peon501** [comment] 2018-12-04 14:55
@Jjagg 
@cra0zy 
Ok, found 1 more bug.
building *.fbx file.

```
Unhandled Exception:
System.DllNotFoundException: nvtt
  at (wrapper managed-to-native) Nvidia.TextureTools.InputOptions.nvttDestroyInputOptions(intptr)
  at Nvidia.TextureTools.InputOptions.Finalize () [0x00000] in <e0f16b6afe60487d8c1afa894a77b547>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.DllNotFoundException: nvtt
  at (wrapper managed-to-native) Nvidia.TextureTools.InputOptions.nvttDestroyInputOptions(intptr)
  at Nvidia.TextureTools.InputOptions.Finalize () [0x00000] in <e0f16b6afe60487d8c1afa894a77b547>:0 

```

**Comment by peon501** [comment] 2018-12-04 14:57
looks like I need more dependencies... probably related to nvidia.

**Comment by Jjagg** [comment] 2018-12-04 16:02
@peon501 Please don't post about unrelated issues here, but the cause might be #5866. Try installing libpng12. If that's not it, please open a new issue.

**Comment by cra0zy** [comment] 2018-12-04 17:36
> @cra0zy Something to do with .NET Framework version or something?

Whenever you see a missing .NET Framework, you know they did not install C# stuff properly.

Gonna close this as original issue has been resolved.

**Closed by cra0zy** 2018-12-04 17:36 UTC
