### ISSUE TITLE
NullReferenceException in Game.get_IsActive on iOS with F#

### ISSUE THREAD

**Issue by torbonde** [MonoGame/MonoGame#6007] opened 2017-10-13 15:12 UTC
This was first raised as a question on StackOverflow, but it was suggested that I created an issue here instead.

I'm trying to build a simple MonoGame app for iOS using F#. I have done this by manually cooking up a fsproj file, on the basis of project files for

F# iOS Single Page Application (template),
F# console application (template) and
C# iOS MonoGame (template).
My code looks like this:

```
namespace MonoGameFSharpTemplate

module Game =
    open Microsoft.Xna.Framework
    open Microsoft.Xna.Framework.Graphics
    open Microsoft.Xna.Framework.Input
    open Microsoft.Devices.Sensors

    type Game1 () as x =
        inherit Game()

        do x.Content.RootDirectory <- "Content"
        member val graphics = new GraphicsDeviceManager(x) with get, set

        override x.Initialize() =
            do base.Initialize()

        override x.LoadContent() = ()

        override x.Update (gameTime) =
            do base.Update(gameTime)

        override x.Draw (gameTime) =
            do base.Draw(gameTime)

module App =
    open UIKit
    open Foundation
    open Game

    [<Register("AppDelegate")>]
    type AppDelegate() =
        inherit UIApplicationDelegate()

        override val Window = null with get, set

        override this.FinishedLaunching(app, options) =
            use game = new Game1()
            game.Run()
            true

module Main =
    open UIKit

    [<EntryPoint>]
    let main argv = 
        UIApplication.Main(argv, null, "AppDelegate")
        0
```

It should be pretty much equivalent to the code provided in the C# template (which runs just fine, by the way).

When running this code in the iOS simulator, I get a `NullReferenceException` with the following stack trace
```
  at Microsoft.Xna.Framework.Game.get_IsActive () [0x00000] in <d3066bb8224f42c4ab3ae66d66329856>:0 
  at Microsoft.Xna.Framework.iOSGamePlatform.Tick () [0x00006] in <d3066bb8224f42c4ab3ae66d66329856>:0 
  at Microsoft.Xna.Framework.iOSGameView.DoTick () [0x00000] in <d3066bb8224f42c4ab3ae66d66329856>:0 
  at (wrapper managed-to-native) UIKit.UIApplication:UIApplicationMain (int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Users/builder/data/lanes/5024/152b654a/source/xamarin-macios/src/UIKit/UIApplication.cs:79 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x00038] in /Users/builder/data/lanes/5024/152b654a/source/xamarin-macios/src/UIKit/UIApplication.cs:63 
  at MonoGameFSharpTemplate.Main.main (System.String[] argv) [0x00000] in /Users/torbonde/Projects/MonoGameFSharpTemplate/MonoGameFSharpTemplate/Program.fs:47 
```

I'm running MonoGame build, v3.7.0.937, but I had the same issue using v3.6.

Is this a known issue, and is there a fix/workaround? I have had a look at the code here in this repo, where the exception seems to occur, but I can't seem to locate the issue.

**Comment by Jjagg** [comment] 2018-12-10 16:48
I'm gonna close this since the issue is because of the implementation of the template. Tracking F# templates in #6590.

**Closed by Jjagg** 2018-12-10 16:48 UTC
