### ISSUE TITLE
ContentManager GC unloads its loaded content

### ISSUE THREAD

**Issue by Grimston** [MonoGame/MonoGame#2208] opened 2014-01-22 04:03 UTC
Copying the issue from CodePlex here

if you load content using a ResourceContentManager (From a DLL in my case, for my UI) and load normal content, the usual way. The ResourceContentManager loaded items disappear, such as fonts, and textures.

This can be reproduced, by taking a sample with the Game Debug Tools and loading the font from a ResourceContentManager. Takes about 20-30 seconds before issue occurs, or force GC and you will have the issue.

**Comment by Jjagg** [comment] 2018-12-11 22:10
This behavior is by design. The fact that XNA did this differently might point to a different finalizer implemenation. Perhaps XNA does not unload assets if the `ContentManager` is finalized. MG behavior makes sense in this case to prevent unmanaged assets not getting cleaned up.

Anyway, since this is by design I'm closing this issue. Since a `ContentManager` manages your content you should not let it go out of scope if you need your content.

**Closed by Jjagg** 2018-12-11 22:10 UTC
