### ISSUE TITLE
[dev/Pipeline] add existing item (with missing item from project) => invalid URI exception

### ISSUE THREAD

**Issue by InfiniteProductions** [MonoGame/MonoGame#4859] opened 2016-05-16 07:21 UTC
Existing item cannot be added to a project in pipeline tool (new item, new folder, add folder works):

> System.UriFormatException: URI non valide : Impossible de déterminer le format de l'URI.
>    à System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
>    à MonoGame.Tools.Pipeline.MainWindow.ChooseContentFile(String initialDirectory, List`1& files) dans C:\MonoGame\Tools\Pipeline\MainWindow.cs:ligne 204
>    à MonoGame.Tools.Pipeline.PipelineController.Include() dans C:\MonoGame\Tools\Pipeline\Common\PipelineController.cs:ligne 610
>    à MonoGame.Tools.Pipeline.MainWindow.CmdExistingItem_Executed(Object sender, EventArgs e) dans C:\MonoGame\Tools\Pipeline\MainWindow.cs:ligne 527
>    à Eto.Forms.Command.OnExecuted(EventArgs e)
>    à Eto.Forms.Command.System.Windows.Input.ICommand.Execute(Object parameter)
>    à Eto.Forms.ToolItem.OnClick(EventArgs e)
>    à System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
>    à System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
>    à System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
>    à System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
>    à System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
>    à System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>    à System.Windows.Forms.Control.WndProc(Message& m)
>    à System.Windows.Forms.ToolStrip.WndProc(Message& m)
>    à Eto.WinForms.Forms.ToolBar.ToolStripEx.WndProc(Message& m)
>    à System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

MonoGame and Pipeline build today from a git dev repository sync'ed just yesterday, on windows 7 64b, using windows platform build.

I've also do the same as given in issue #4851 regarding submodule, just in case and rebuild all, same results.

Update: it's happened with an old dummy project, creating a new one, clean, is ok.
Here is the file: [badproject.zip](https://github.com/mono/MonoGame/files/265795/badproject.zip)

Some items are missing, they have been deleted since, so the steps to get the issue are:
- create a project, 
- add an asset from a given location,
- close the project,
- delete the asset in project folder
- open the project file
- click on "add an existing item"

**Comment by Tzenchor** [comment] 2016-05-16 08:00
> Existing item cannot be added to a project in pipeline tool (new item, new folder, add folder works):

What were you trying to add? I have just tryed to add an existing file and an existing folder and both worked

**Comment by InfiniteProductions** [comment] 2016-05-16 08:12
> What were you trying to add? I have just tryed to add an existing file and an existing folder and both worked

it's irrelevant, as the exception occurred when clicking on "add existing item", but I figured out it was with an old project file which may have something "broken" in it, anyway, such exception shouldn't happened at all, I guess some check are missing here or there.

I'll update the title and desc.

**Comment by cra0zy** [comment] 2016-05-17 17:42
I am not able to reproduce it on Linux, will try on Windows in 15 mins.

**Comment by Tzenchor** [comment] 2016-05-17 17:58
I couldn't reproduce it on Windows also

**Comment by InfiniteProductions** [comment] 2016-05-20 09:26
I cannot either reproduce the issue I've got before, I'll continue to dig to be sure and let you know if I find something, if not, this issue will be good to be closed.

**Comment by cra0zy** [comment] 2018-10-02 19:38
Gonna assume this was fixed and close it.

**Closed by cra0zy** 2018-10-02 19:38 UTC
