### ISSUE TITLE
Include Content Pipeline Tool in NuGet Packages

### ISSUE THREAD

**Issue by trommlbomml** [MonoGame/MonoGame#3985] opened 2015-07-06 12:12 UTC
As I have my monogame projects in git I woul prefer to use Nuget-Packages instead of installations for better dependecy handling. Unfortunatly the NuGet-Package for MonoGame does not provide the content pipeline tool, so I needed to install MonoGame from the installer too. This is bad because now I have MonoGame twice installed + probably some issues when I switch to a different MonoGame Version in NuGet.

**Comment by tomspilman** [comment] 2015-07-06 15:24
Is that even something you do with NuGet?  Distribute GUI apps?

**Comment by trommlbomml** [comment] 2015-07-07 08:25
Why not? As I see the Nuget-Packages are per platform this seems to me no problem. A compromise for me would to have a separate command line only tool provided by nuget. Don't you think installing and having nuget-packages is a bit weird?

**Comment by craftworkgames** [comment] 2015-08-07 03:22
Doesn't [Chocolatey](https://chocolatey.org/) do something like this? 

> Chocolatey NuGet is a Machine Package Manager, somewhat like apt-get, but built with Windows in mind.

**Comment by mattleibow** [comment] 2015-12-16 22:40
I would maybe create a separate package "MonoGame.Content.Pipeline.Build" or something. All the bits can go in there from the two installers

**Comment by craftworkgames** [comment] 2015-12-17 00:01
@mattleibow Yeah I agree with you on that one.

I've been thinking about this a bit lately because we've experienced [a related issue with MonoGame.Extended](https://github.com/craftworkgames/Samples.Extended/issues/5). 

The problem really boils down to using a different version of the Pipeline tool compared to the version of MonoGame referenced in your project. In this case referencing 3.4 and using Pipeline 3.5 or visa-versa. 

It stands to reason that the Pipeline tool is just another dependency of your project and should be treated that way. If the Pipeline tool was kept in the `packages` folder, or somehow otherwise kept with the project it belongs to then the problem would go away.

For people using the NuGet packages the solution seems relatively simple on the surface. We just store the Pipeline tool in the packages folder. However, there's another piece to the puzzle.

In a MonoGame project file there's a reference to the content builder targets file which is used to build content at compile time.

    <Import Project="$(MSBuildExtensionsPath)\MonoGame\v3.0\MonoGame.Content.Builder.targets" />

On my machine this path resolves to

    C:\Program Files (x86)\MSBuild\MonoGame\v3.0\MonoGame.Content.Builder.targets

This file is also stored next to where the Pipeline tool is installed.

So if we where to put the Pipeline tool in the packages folder we'd also have to figure out how to deal with the targets file so that it points to the correct copy of the Pipeline.

**Comment by trommlbomml** [comment] 2015-12-17 10:03
@mattleibow I agree with that. it also seems a windows (and linux?) only problem as I can install the pipeline tool or mac separately from the monogame on the website.

**Comment by mattleibow** [comment] 2015-12-17 17:28
@craftworkgames If we add a .targets file to the build/ folder, then it will automatically be managed by NuGet and add it to the project file. No actual work is needed on our side. I am busy testing things here and will see if I can get a PR that does this all.

**Comment by mattleibow** [comment] 2015-12-17 17:29
@trommlbomml We can let the user know that it is either or. If we use the NuGet, then it will use the NuGet. If they want to use the main install, then they will have to do the work manually. It should be no problem as the one is in the packages/ folder and the other is somewhere else.

**Comment by mattleibow** [comment] 2015-12-17 19:51
I created a PR to show the current working: #4332

**Comment by craftworkgames** [comment] 2015-12-22 00:32
Looks great.

**Comment by craftworkgames** [comment] 2018-04-17 23:55
What ever happened with this? I can see the issue is still open but the related PR is closed with no explanation.

**Comment by cra0zy** [comment] 2018-04-18 11:33
What PR? Also NuGet is no place to include Pipeline Tool in so I don't think anybody will set it up.

**Comment by cra0zy** [comment] 2018-04-18 12:33
> The main issue with a CP Tool NuGet was the size as I recall, it was almost a 100mb package due to the dependencies required.

No, that was MGCB nuget. Also I fixed the size issue:
- https://www.nuget.org/packages/MonoGame.Content.Builder/
- https://www.nuget.org/packages/MonoGame.Content.Builder.Windows/
- https://www.nuget.org/packages/MonoGame.Content.Builder.Linux/
- https://www.nuget.org/packages/MonoGame.Content.Builder.Mac/

**Comment by SimonDarksideJ** [comment] 2018-04-18 13:28
Ahh, wasn't aware of that update, thanks @cra0zy :D 
I guess we need more announcements / detail on that availability now.

SO is it, "done"?

**Comment by cra0zy** [comment] 2018-04-18 13:35
> I guess we need more announcements / detail on that availability now.
> 
> SO is it, "done"?

Nope, they are still unofficial ones, I didn't make a PR for it (mostly waiting for Protobuild removal which is scheduled for 3.8).

**Comment by craftworkgames** [comment] 2018-04-19 04:47
> What PR?

PR #4332 was the last one mentioned in this issue (before I made the comment). I mean, I really have no other context other than what's written on this issue so..

>Also NuGet is no place to include Pipeline Tool in so I don't think anybody will set it up.

Why do you say that? 
I mean, maybe NuGet is not the right solution to this problem. 
Ultimately though, having some way to install a particular version of the Pipeline Tool into your project would be useful and have it versioned with your source code is important.
It's quite annoying to grab the source code of a project and not have it build because it used to use a different version of the Content Pipeline tool.
An alternative approach is to have a some sort of build script the user can run or at worst it's just instructions in your readme. 
Either way though, last time I checked having 2 different versions of the Content Pipeline installed on the same machine wasn't possible. Maybe this has been fixed now, I don't know.

> No, that was MGCB nuget. Also I fixed the size issue:

Thanks for publishing those NuGet packages. That's the kind of thing I was looking for when I posted here the other day. I had a look on nuget.org but I didn't notice these. I'll take a closer look at them later.

> Nope, they are still unofficial ones

"Official" or "unofficial" doesn't really matter if it solves a problem. We appreciate it all the same @cra0zy

**Comment by cra0zy** [comment] 2018-04-19 08:31
> Why do you say that?
> I mean, maybe NuGet is not the right solution to this problem.
> Ultimately though, having some way to install a particular version of the Pipeline Tool into your project would be useful and have it versioned with your source code is important.
> It's quite annoying to grab the source code of a project and not have it build because it used to use a different version of the Content Pipeline tool.
> An alternative approach is to have a some sort of build script the user can run or at worst it's just instructions in your readme.
> Either way though, last time I checked having 2 different versions of the Content Pipeline installed on the same machine wasn't possible. Maybe this has been fixed now, I don't know.

That mostly gets solved with the MGCB nuget (since you only want to use the Pipeline Tool to edit .mgcb files anyways).

> Thanks for publishing those NuGet packages. That's the kind of thing I was looking for when I posted here the other day. I had a look on nuget.org but I didn't notice these. I'll take a closer look at them later.

Reference only the main one, to see it in action check out .NET Core template I did:
```
dotnet new --install MonoGame.Template.CSharp
dotnet new mgdesktopgl
```

**Comment by craftworkgames** [comment] 2018-05-14 04:47
> dotnet new --install MonoGame.Template.CSharp
dotnet new mgdesktopgl

I used this on the weekend when I was converting MonoGame.Extended to .NET Standard. It works really well, thanks for your efforts @cra0zy.

**Comment by cra0zy** [comment] 2018-10-02 19:43
Content Pipeline Tool will never be available as a nuget, however maybe as a `dotnet tool` in the future. Anyway if anyone is interested feel free to open a feature request about it.

**Closed by cra0zy** 2018-10-02 19:43 UTC
