### ISSUE TITLE
WP8.1 Multitouch slowdown

### ISSUE THREAD

**Issue by MaxPirat** [MonoGame/MonoGame#3316] opened 2014-12-27 12:50 UTC
Hi! I'm trying to port my games on WP8.1 with Monogame 3.2.3 (via NuGet -pre version).

But I notice in one of my game (which is based on multitouch gameplay 4+ touches at once) that if I touch screen with 3 fingers and move them I get fps drop and if I touch it and move with 7+ finger it's drop even more and can even freeze until I go back in WP menu and back again. Even if I have no touch code at all. 

It can be reproduce in empty WP8.1 project with monogame template (with 3d cube in it), touch it with 5-10 fingers and frame will freeze. Here is the video: http://youtu.be/gSrUaaTeFFk

**Comment by MaxPirat** [comment] 2015-01-07 20:07
Really glad this issue got attention! Any news on it?

**Comment by KakCAT** [comment] 2015-03-07 10:56
Hi,

same problem is being discussed here with an easy way to reproduce it and some interesting findings by nkast

http://community.monogame.net/t/wp8-1-game-freezes-sporadically/1865/18

**Comment by nkast** [comment] 2015-03-07 16:26
Not a fix, just some testing for now. 
https://github.com/nkast/MonoGame/tree/wp81TouchInputAndRenderLoop
Fix: total freeze of  CompositionTarget.Rendering  
Fix: slowdown when moving fingers on the touch screen (although it's still visible when you call .WriteLine() from a touch event).
Fix: apply Orientation delay reported by @katCat

problems 
1) we can no longer capture events. 
2) We have to handle TouchEnter and TouchLeave event as well.
3) What's the best practice to stop those tasks/threads?

**Comment by nkast** [comment] 2015-03-08 19:21
Some more on this,
I move this code to a win8.1 project. The  render thread looks ok, except you can no longer call some functions from your game, like `Windows.UI.Input.EdgeGesture.GetForCurrentView()`.
The touch input has serious issues, besides handling of PointerExited/PointerEntered, I notices that touch visual feedback is still enabled dispite the fact that i disabled it from code. This dropes frame rate <30fps. Upgrading to SwapChainPanel didn't solve this. 
Another issue is that i am getting assertion fails  from monogame after some time.
  ---- DEBUG ASSERTION FAILED ----
---- Assert Short Message ----
The touch event is older than our timestamp!
---- Assert Long Message ----

   at Microsoft.Xna.Framework.Input.Touch.TouchLocation.UpdateState(TouchLocation touchEvent)
   at Microsoft.Xna.Framework.Input.Touch.TouchPanelState.Refresh(Boolean consumeState, List`1 state, List`1 events)
   at Microsoft.Xna.Framework.Input.Touch.TouchPanelState.get_IsGestureAvailable()
   at Microsoft.Xna.Framework.Input.Touch.TouchPanel.get_IsGestureAvailable()
   at tainicom.XNA.PageManager.InputState.Update(Boolean isActive)
   at tainicom.XNA.PageManager.PageManager.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.<.cctor>b__19(IUpdateable updateable, GameTime gameTime)
   at Microsoft.Xna.Framework.Game.SortingFilteringCollection`1.ForEachFilteredItem[TUserData](Action`2 action, TUserData userData)
   at Microsoft.Xna.Framework.Game.Update(GameTime gameTime)

**Comment by KakCAT** [comment] 2015-03-10 11:37
Hi,

I tried nkast's test on N920 8.1 and the problems disappear. The pointer position is offseted however, as if you would be receiving coordinates from a different coordinate system now (no problem, as it's just a test)

Curiously changing only the CompositionTarget.Rendering bit makes the game not to freeze but being unable to receive inputs after mashing the touchscreen, which is congruent with a bug several WP8.1-only games on the store have (like Beach Buggy Racing, which AFAIK is not using MonoGame)

**Comment by nkast** [comment] 2015-03-10 15:46
@KakCAT Perhaps you are getting portrait cordinates, the touch are not translated by the XAML element. This behavior is similar to Win8.X, we have to translate touch the same we do our 2D drawing.

Probably the rendering thread takes up all the time and XAML events get lower priority. MSDN suggests to use CoreProcessEvents to grab touch with low latency detached from XAML UI thread. It's possible to have a single thread for Tick & coreIndependentInputSource.Dispatcher.ProcessEvents() but so far I don't see any benefit from doing so, it will just complicate the code. 

We can pobably work the problems with touch on the phone, some more handling is required on the desktop when touch move from window to window, but the  biggest issue is the one about visual touch feedback on Win8, still can't figure this one out.

**Comment by EdvinM** [comment] 2015-03-10 17:43
In my case I do not need to put two/three or more fingers and tap on screen to freeze. It just does spontaneously when I tap on the screen and it unfreezes when I change orientation... I will try later with @nkast solution, I'm hoping it will fix the problem ...

**Comment by nkast** [comment] 2015-03-10 19:31
Another option is to listen to window events (CoreWindow), same thing as when inputElement == null. 
In other words, remove the first block of `if (inputElement != null)`.
Since MG has only one SwapChainBackgroundPanel - and in the future support a single fullscreen SwapChainPanel - i don't see why we need to create a CoreIndependentInputSource.
So far it seems to perform well and there is no problem with touch visual feedback on Win8.

**Comment by EdvinM** [comment] 2015-03-10 20:36
Confirmed. Like @KakCAT the game doesn't freeze anymore, I tapped with all my fingers (Lumia 520) :) but the touch positions are not correct.

**Comment by nkast** [comment] 2015-04-13 18:47
I didn't have the time to work on a PR for this. The issues so far:
A) Issue #3727   Dispatch SizeChange events to the renderthread.
B) Using a high priority thread for rendering makes input lag even worst, Input must be solved alongside the CompositionTarget.Rendering freeze. So far CoreIndependentInputSource  has a bug and can't be used because it makes performance worst on devices with touch. Subscribing to the CoreWindow removes the WPF lag but @EdvinM reported that touch  positions are not correct (depenting on rotation?), I have yet to verify this. 

None of this is currently an issue for me because I lock the backbuffer to the native rotation/resolution to avoid perf hit, similar to SwapChainBackgroundPanel on WP8.0 and rotate graphics/input.

**Comment by jakepoz** [comment] 2015-08-14 23:07
Just FYI, there is now a $1,000 USD bounty on this bug:
https://www.bountysource.com/issues/7309032-wp8-1-multitouch-slowdown

**Comment by danzel** [comment] 2015-08-30 10:13
Okay, have done a bit of research in to this.

If you run the current code and remove the input event listeners (Comment out [this block](https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Windows8/InputEvents.cs#L35-L52)) you still get the lockup (it can take a while of bashing 10 fingers). When this occurs, changing the device orientation fixes it.
This makes me think it probably isn't our touch code.

The Direct3D examples [over here](https://code.msdn.microsoft.com/windowsapps/Direct3D-Tutorial-Sample-08667fb0), [here](https://code.msdn.microsoft.com/windowsapps/Metro-style-DirectX-18f98448) and [here](https://code.msdn.microsoft.com/windowsapps/XAML-SwapChainPanel-00cb688b) all use run loops rather than the ```CompositionTarget.Rendering``` event.
I haven't found any that use the event when searching for "WP8.1 DirectX WPF" (and related terms).
The ones that use ```CompositionTarget.Rendering``` that I have found are generally targeted at Silverlight or WP7/8 users coming from Silverlight.

Will prod a bit more in the week.

**Comment by nkast** [comment] 2015-08-30 13:10
@danzel The source of the problem is indeed  CompositionTarget.Rendering. WP8.1 & 10 stops firing it, probably a failsave when there are too many events, it's not supposed to be used for intensive work. 
A hacky workaround is to keep it alive by invalidating the xaml layout on every frame.
The right way is to have a separate thread for game loop.
This unfortunately push touch events to a lower priority so we have to run them on a separate thread too. See also my comment above about the bug on W8.1 with touch.
And we have only test this on phones, I'm afraid we have to sync a wide range of events when we move this to W8.1/10.

**Comment by birbilis** [comment] 2016-08-27 21:59
maybe useful for the future (problem is original Win10 didn't have that API):

> In the initial release of Windows 10, significant work was done to create a new unified compositor and rendering engine for all UWP applications running on Windows 10 devices .Now with the first update of Windows 10, Build 10586, we are releasing this public API and Windows.UI.Composition.

Read more at https://blogs.windows.com/buildingapps/2015/12/08/awaken-your-creativity-with-the-new-windows-ui-composition/

> Windows.UI.Composition first debuted in the Windows 10 November 2015 update. With the Anniversary edition, it is getting a whole host of new effects, such as the blur effect, as well as new animation capabilities

Read more at https://blogs.windows.com/buildingapps/2016/08/23/beautiful-apps-made-possible-and-easy-with-windows-ui/

**Comment by nkast** [comment] 2016-10-08 13:00
I opened a uservoice to get CoreIndependentInputSource fixed. That whould be the first step to get input lag fixed and then move rendering to its own thread as well. Please vote if you have the time.
https://wpdev.uservoice.com/forums/110705-universal-windows-platform/suggestions/16521550-fix-coreindependentinputsource

**Comment by birbilis** [comment] 2016-10-08 13:55
do they allow one to customize the touch visual feedback (preferably programmatically AND at the app level, not at user level)? that could be a sideways approach to make it disappear or at least consume less resources

**Comment by tomspilman** [comment] 2017-03-28 14:14
Fixed in #5520.

**Closed by tomspilman** 2017-03-28 14:14 UTC
