### ISSUE TITLE
2MGFX, warnings, optimizations and ConstantBuffer

### ISSUE THREAD

**Issue by lucasassislar** [MonoGame/MonoGame#5035] opened 2016-07-27 12:59 UTC
**Platform**: OpenGL
**Version**: Latest commit and Release 3.5.1
**Issue**: Destination offset is wrong, count is wrong
**Reproducing**: This is a ~very~ specific case-scenario, but it can happen easily and there's no clear explanation of whats happening.

If you declare a float4x4 in your code and only use it to get a float3 result, it will become a float4x3 with a warning ( "implicit truncation of vector type" ).
Issue is, now we don't have enough space to store float4x4 data (64 bytes), only 48 bytes.

Example of the problem:

```
float4x4 World;

float3 Position = mul(inPosition, World);
```

This will build correctly though 2MGFX on OpenGL, but with a warning. When you apply the pass the data won't be able to be copied.

**Solution**: 
1. Change float4x4 to float4x3 on everything that you won't need a float4 result.
or
2. Change "implicit truncation of vector type" from a warning to an error.

Though it's a simple mistake, I think this can be a block to newcomers (riemers.net tutorials wouldn't work, for example, which is pretty much how I started learning HLSL).

**Comment by InfiniteProductions** [comment] 2016-07-28 09:31
What I see is there is one or more issue(s) in your description/title, hard to understand what is all about !

And your so called "solution" is worth than bad, as replacing the warning by an error will just prevent maybe 90% of shader codes from at least samples and tutorials to just compile ! As most of authors didn't take the times to do things right (the only one I see in XNA/MonoGame world is the author of dhpoware website.)
The first way is not clear either, you just have to do things right.

Assuming inPosition is a float4 (vector type), the line should be written:

`float3 Position = mul(inPosition, World).xyz;`

as the warning comes from the truncation of a float4 (result of 'mul' to the float3 Position).
(multiplying a float4 with a float4x4 matrix is ok)

A good book about HLSL and shaders is _ShaderX2 Introductions And Tutorials with DX9_ (one of the authors is one the HLSL designer himself !)

casting rules from the book, page 16:
> Vector-to-matrix The size of the vector must be equal to the size of the matrix.
> Matrix-to-vector The size of the matrix must be equal to the size of the vector.

**Comment by Jjagg** [comment] 2018-12-11 10:01
Closing as duplicate of #911. The other issue has more information and a shader to reproduce the error.

**Closed by Jjagg** 2018-12-11 10:01 UTC
