### ISSUE TITLE
dotnet tool `dotnet-mgcb` to be reinstalled every time when project build.

### ISSUE THREAD

**Issue by ryancheung** [MonoGame/MonoGame#7150] opened 2020-05-22 13:37 UTC
When trying to build the project every time, it tries to install the dotnet tool `dotnet-mgcb`, it connects to the configured nuget source which dramatically reduces the build speed if you have a bad network connection to the nuget server.

The following is the log when project starts build:
```
  dotnet-mgcb      3.7.200-develop      mgcb      D:\xxx\xxx\xxx.Playground.WindowsDX\.config\dotnet-tools.json
  Creating this template will make changes to existing files:
    Overwrite   .config/dotnet-tools.json

  Rerun the command and pass --force to accept and create.
C:\Users\ryanc\.nuget\packages\monogame.content.builder.task\3.7.200-develop\build\MonoGame.Content.Builder.Task.targets(105,5): warning MSB3073: Command“dotnet new tool-manifest”exited, exit code is -2147467260。 [D:\xxx\xxx\xxx.Playground.WindowsDX\xxx.Playground.WindowsDX.csproj]
```

NOTE I'm use a custom preview version number `3.7.200-develop`(which is actually the MonoGame develop branch). Maybe it's bugged on the version string detection?

@jnoyola Could you please give some favor on this? It's really hard to debug with `MonoGame.Content.Builder.Task.targets`

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- DesktopGL, WindowsDX, Android

**Comment by jnoyola** [comment] 2020-05-22 19:35
That’s a good point. I can jump into the detail when I’m off mobile lately, but I think the idea is that it will check what version you intend to install based on your nuget reference or a property if you override it. It will then check the manifest for that version. If it’s not present it will install it. If it is present, it _always_ does a restore because it’s hard to tell if the tool has actually been installed or just written in the manifest.

I can look into ways of improving this and check out your error later. Please share if you have any ideas :)

**Comment by jnoyola** [comment] 2020-05-22 19:41
Can you give more details about that log message? It looks like it’s trying to use 3.7.200-develop, which appears to be the same version as your nuget package. Is there an issue with the version there, or is the issue that it’s asking you to call the command with —force?

**Comment by ryancheung** [comment] 2020-05-22 22:41
There should be no issue with the version, it's just a custom version number. And I use the same version number for all MG nuget packages. 
It use `--force` automatically because it runs `dotnet new tool-manifest` command when there's a tool manifest file already `.config/dotnet-tools.json`, which means it failed to detect current installed tool version and it runs the `InstallMGCB` procedure to create a manifest file and then restore it.

**Comment by ryancheung** [comment] 2020-05-22 22:55
I'm not sure if it's the dotnet tool restore command that make a connection to nuget source even the tools were installed already. 
If it is true, then I think we can skip the tool restore process on build start. We can query the install dotnet tool package, if they exist in the local nuget package cache (~/. nuget/packages) then it is sure there's no dotnet tool to restore.

**Comment by jnoyola** [comment] 2020-05-22 23:04
> We can query the install dotnet tool package, if they exist in the local nuget package cache (~/. nuget/packages) then it is sure there's no dotnet tool to restore.

NuGet has all sorts of ways that the package cache can be configured, so I don't think we want to maintain our own way of resolving the package location. If dotnet has some CLI command to query installed packages, that could work, but I don't think it does.

Let me start by looking into the version detection and manifest overwrite, because I've used complex version strings like that without issue.

**Comment by harry-cpp** [comment] 2020-05-22 23:12
> If dotnet has some CLI command to query installed packages

```
dotnet tool list --local
```

**Comment by jnoyola** [comment] 2020-05-22 23:17
> `dotnet tool list --local`

From what I understand, this lists what tools are listed in the manifest and assumed to be installed, but doesn't actually check the package cache. We _could_ continue with that same assumption, and if running the tool fails, leave it up to the user to manually restore or fix it.

**Comment by jnoyola** [comment] 2020-05-22 23:24
Back to the log message:

> It use `--force` automatically

I don't think this is true. The targets file never uses `--force`. This task is here to ensure there is a targets file, which is why it continues on error. So yes, you will see that log that it tried to create a manifest, but one already existed so it didn't overwrite it. That's working as intended

```xml
    <!-- Ensure there is a manifest for the project. -->
    <Exec
      WorkingDirectory="$(MSBuildProjectDirectory)"
      Command="$(DotnetCommand) new tool-manifest"
      ContinueOnError="true" />
```

**Comment by jnoyola** [comment] 2020-05-22 23:31
Can you try editing your local cache of the targets file to print what it parsed at line 90?
Something like this:
```xml
    <Message Importance="high" Text="%(DotnetTool.PackagId);%(DotnetTool.Version);%(DotnetTool.Commands);%(DotnetTool.Manifest)" />
```

**Comment by harry-cpp** [comment] 2020-05-23 00:10
> From what I understand, this lists what tools are listed in the manifest and assumed to be installed, but doesn't actually check the package cache. We _could_ continue with that same assumption, and if running the tool fails, leave it up to the user to manually restore or fix it.

Oh I see. Couldn't we just have a normal nuget package reference to `dotnet-mgcb`, that way the build process would ensure that the tool exists in the nuget cache?

**Comment by ryancheung** [comment] 2020-05-23 01:17
> EDIT: Also just wanted to double check, do you have [this change](https://github.com/MonoGame/MonoGame/commit/4629bc1774169b84df1156b6e2bc862ba8054323#diff-3907cf812f624f46758af0411dd0a66a) from April 7?

Yeah, I have the change.

**Comment by ryancheung** [comment] 2020-05-23 01:19
> Oh I see. Couldn't we just have a normal nuget package reference to `dotnet-mgcb`, that way the build process would ensure that the tool exists in the nuget cache?

I think this is a great idea. ❤️

**Comment by ryancheung** [comment] 2020-05-23 01:22
> Did it continue to do a `dotnet tool install` after that log message? I'm still trying to find out why it didn't like that version.

It prints:
```
;3.7.200-develop;mgcb;D:\xxx\xxx\xxx.Playground.WindowsDX\.config\dotnet-tools.json
```

**Comment by ryancheung** [comment] 2020-05-23 01:23
> Can you try editing your local cache of the targets file to print what it parsed at line 90?
> Something like this:
> 
> ```
>     <Message Importance="high" Text="%(DotnetTool.PackagId);%(DotnetTool.Version);%(DotnetTool.Commands);%(DotnetTool.Manifest)" />
> ```
> 
> EDIT: Also just wanted to double check, do you have [this change](https://github.com/MonoGame/MonoGame/commit/4629bc1774169b84df1156b6e2bc862ba8054323#diff-3907cf812f624f46758af0411dd0a66a) from April 7?

It prints:
```
;3.7.200-develop;mgcb;D:\xxx\xxx\xxx.Playground.WindowsDX\.config\dotnet-tools.json
```

**Comment by ryancheung** [comment] 2020-05-23 01:30
I found it's bugged here:
```
  <Target Name="UpdateMGCB" Condition="'$(MGCBCommand)' == ''" DependsOnTargets="GetInstalledMGCB">

    <!-- If the correct version is in the manifest, restore to ensure it's installed. -->
    <Exec
      Condition="$(MGCBInstalledVersion) == $(MGCBVersion)"
      Command="$(DotnetCommand) tool restore" />

    <!-- If the correct version is not in the manifest, install the correct version. -->
    <CallTarget
      Condition="$(MGCBInstalledVersion) != $(MGCBVersion)"
      Targets="InstallMGCB" />

    <Message Importance="high" Text="$(MGCBInstalledVersion)" />
    <Message Importance="high" Text="$(MGCBVersion)" />
    <Message Importance="high" Text="$(MGCBInstalledVersion) != $(MGCBVersion)" />

    <PropertyGroup>
      <MGCBCommand>$(DotnetCommand) tool run mgcb</MGCBCommand>
    </PropertyGroup>

  </Target>
```
It prints:
```
  3.7.200-develop
  3.7.200.0-develop
  3.7.200-develop != 3.7.200.0-develop
```

**Comment by jnoyola** [comment] 2020-05-23 01:52
> Couldn't we just have a normal nuget package reference to dotnet-mgcb, that way the build process would ensure that the tool exists in the nuget cache?

I think that is an option. In fact I thought we had considered it before but decided to do this instead, maybe because then it's easier to change the version with a property and use the package manually if desired since it's registered as a dotnet tool. I'm down to compare the pros and cons again if you want.

**Comment by jnoyola** [comment] 2020-05-23 01:55
> Everytime `UpdateMGCB`, it failed to compaire version number to do `InstallMGCB`, we should handle the appended patch version number `.0`.

Good catch! I guess NuGet adds those automatically. We'll have to see what we can do to fix that.

**Comment by ryancheung** [comment] 2020-05-23 02:07
I just tried with `System.Version` to compare the two versions, but it only support numeric versions but not version number with strings.

**Comment by jnoyola** [comment] 2020-05-23 02:21
The default `MGCBVersion` is taken from the csproj's `$(PackageVersion)` [here](https://github.com/MonoGame/MonoGame/blob/develop/Tools/MonoGame.Content.Builder.Task/MonoGame.Content.Builder.Task.csproj#L13), so that must be automatically adding the `.0`. If you look within the NuGet package you should see the `build\version\$(PackageVersion)` folder, and that section of the path is the version that the targets file looks for.

**Comment by ryancheung** [comment] 2020-05-23 04:32
So the proper workaround at the moment should be including a patch version number for nuget packages.

**Comment by jnoyola** [comment] 2020-05-23 04:55
I suppose so. But PackageVersion should respect whatever Version value you pack with by default. I don’t understand how the Version could end up with one value and the PackageVersion something else unless you explicitly set them. I’ll have to experiment with that same version string later. Did you do `dotnet pack /p:Version= 3.7.200-develop`?

**Comment by ryancheung** [comment] 2020-05-23 06:01
Yeah, with the cake script: `dotnet cake --build-version=3.7.200-develop`.

I think it's kinda complex to do version string comparison within msbuild target file. I just tried in the morning with `String.SubString` and `System.Version.Equals`, it just too hard to write some simple C# in msbuild target file.

I suggest let the `MonoGame.Content.Build.Task` package dependent on a specific version of the mgcb tool, yeah the same version as the task package. This  approach save lots of things in the msbuild  target file.

**Comment by harry-cpp** [comment] 2020-05-23 10:51
I was talking about something like: https://github.com/MonoGame/MonoGame/pull/7155

2 things modified:
- Remove dotnet tool restoring
- Added a project reference to the mgcb, that way when the user adds a reference to MonoGame.Content.Builder.Task, they will also add a reference to dotnet-mgcb of the same version

**Comment by harry-cpp** [comment] 2020-05-23 10:52
@jnoyola I'll let you handle fixing the version check

**Comment by ryancheung** [comment] 2020-05-23 11:41
I found the `dotnet tool restore` command does not connect the nuget source, It just instant returned when the tool was restored before. 

And I believe `dotnet tool restore` has to run at least once to make the tool available even the tool package was installed already, which means it's not necessary to remove the dotnet tool restoring.

@harry-cpp

**Comment by harry-cpp** [comment] 2020-05-23 11:47
Well my solution fails for several reasons. One thing I would wanna do is hide `dotnet tool restore` output so you don't see it during each build.

**Comment by jnoyola** [comment] 2020-05-23 20:57
I’ll check it out in a few hours. In the meantime, I’m interested in @Jjagg’s opinion too since he helped with the original design.

**Dotnet tool restore**
Pros:
* installs tool for manual use
* allows overriding tool version
* saves dev space

Cons:
* difficult to understand and maintain targets file
* prone to bugs with parsing dotnet output

**NuGet reference**
Pros:
* uses standard nuget installation
* easier to maintain targets file
* saves dev space

Cons:
* depends on nuget paths to reach into other package’s folder
* doesn’t install tool for manual use

**Pack app directly into Builder.Task**
Pros:
* uses standard nuget installation
* easier to maintain targets file
* paths are all self-contained

Cons:
* doesn’t install tool for manual use
* uses more dev space if tool is also installed manually

I don’t know if I got everything, but based on this I would say maybe we should just pack the app directly into the Builder.Task package like how it works for Builder.Editor. So if you reference Builder.Task, Builder.Editor, or dotnet-mgcb, they’ll each come packaged with their own copy of mgcb.

**Comment by harry-cpp** [comment] 2020-05-23 22:35
Well I found the solution to our problem, it should be `DotNetCliToolReference`. Btw. I don't want us to switch from the dotnet tool approach, what I was talking about with PackageReference above is meant for dotnet tool restoring to the global cache.

**Comment by jnoyola** [comment] 2020-05-23 22:46
I'm not sure if we want to take a dependency on `DotNetCliToolReference`. It was that previous version of dotnet local tools and is [now deprecated](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj#dotnetclitoolreference). Additionally, I believe it prevents the tool from being used outside the project folder, and I'm not sure if they propagate through nuget packages anyway.

I like the idea of keeping it as a dotnet tool too, but if it's more maintainable and understandable to ship each package with its own version of mgcb, I'm not opposed to that since that's what Builder.Editor already does, and it's also easier to understand how the versions are tightly coupled.

**Comment by harry-cpp** [comment] 2020-05-23 22:59
Well that sucks :(

**Comment by jnoyola** [comment] 2020-05-26 03:25
So back to the main issue, @ryancheung I'm curious how your `MGCBVersion` ended up with the `.0`. Can you look in the nuget cache for that package? My folder structure looks like this `build/version/3.7.200-develop/Version.props` so it should be picking up the correct version string. What does yours look like?

**Comment by harry-cpp** [comment] 2020-05-26 07:39
Version that teamcity builds is `3.8.0.1368-develop`.

**Comment by ryancheung** [comment] 2020-05-26 07:40
Mine is the same as you, it's `3.7.200-develop` also in the package cache.

But I don't think this issue matter. Since MG released versions could be something like 3.8.0 or 3.8.0.2. We have to support 3.x.x and 3.x.x.x numbers both.

**Comment by jnoyola** [comment] 2020-05-26 07:55
I agree that any arbitrary version should be supported. Can you try to identify what's giving `MGCBVersion` the `.0` if your path doesn't have it? [This](https://github.com/MonoGame/MonoGame/blob/develop/Tools/MonoGame.Content.Builder.Task/version/Version.props#L3) is where it's supposed to read its own version out of the path, and [this](https://github.com/MonoGame/MonoGame/blob/develop/Tools/MonoGame.Content.Builder.Task/MonoGame.Content.Builder.Task.props#L8) is where it's supposed to set `MGCBVersion` if not already set. Are you definitely not setting it manually anywhere?

**Comment by harry-cpp** [comment] 2020-05-26 08:36
The number will not be arbitrary, it should always be `3.8.0`(main version) + `1368-develop`(buildnumber).

**Comment by ryancheung** [comment] 2020-05-26 08:52
> I agree that any arbitrary version should be supported. Can you try to identify what's giving `MGCBVersion` the `.0` if your path doesn't have it? [This](https://github.com/MonoGame/MonoGame/blob/develop/Tools/MonoGame.Content.Builder.Task/version/Version.props#L3) is where it's supposed to read its own version out of the path, and [this](https://github.com/MonoGame/MonoGame/blob/develop/Tools/MonoGame.Content.Builder.Task/MonoGame.Content.Builder.Task.props#L8) is where it's supposed to set `MGCBVersion` if not already set. Are you definitely not setting it manually anywhere?

![monogame task issue](https://user-images.githubusercontent.com/240899/82880585-38b92500-9f71-11ea-8969-659c0e82d6db.PNG)

**Comment by ryancheung** [comment] 2020-05-26 09:01
I guess it's the cake build script appending the `.0` to the passed build version `3.7.200-develop`.

**Comment by ryancheung** [comment] 2020-05-26 09:11
A quick fix: 
```
diff --git a/Tools/MonoGame.Content.Builder.Task/MonoGame.Content.Builder.Task.csproj b/Tools/MonoGame.Content.Builder.Task/MonoGame.Content.Builder.Task.csproj
index 56a07f28e..7bd1ef156 100644
--- a/Tools/MonoGame.Content.Builder.Task/MonoGame.Content.Builder.Task.csproj
+++ b/Tools/MonoGame.Content.Builder.Task/MonoGame.Content.Builder.Task.csproj
@@ -10,7 +10,7 @@
   <ItemGroup>
     <Content Include="MonoGame.Content.Builder.Task.props" PackagePath="build" />
     <Content Include="MonoGame.Content.Builder.Task.targets" PackagePath="build" />
-    <Content Include="version\Version.props" PackagePath="build\version\$(PackageVersion)" />
+    <Content Include="version\Version.props" PackagePath="build\version\$(Version)" />
   </ItemGroup>

   <ItemGroup>
```

Which is change `PackageVersion` to `Version`.

The result nuget package now has the correct version number.
![monogame task issue2](https://user-images.githubusercontent.com/240899/82882626-ea595580-9f73-11ea-929d-e27b2acf6947.PNG)

**Comment by jnoyola** [comment] 2020-05-26 09:51
> The result nuget package now has the correct version number.

I don’t follow. Didn’t you say it already had the correct version number? That’s what I understood when you said:

> Mine is the same as you, it's 3.7.200-develop also in the package cache.

___

I don’t see where the cake script would be appending the .0 unless it’s some odd internal cake detail. But even if it did, I don’t know why Version and PackageVersion would end up different.

**Comment by harry-cpp** [comment] 2020-05-26 10:36
If you pass 3.7.300 than msbuild will append a 0 as assembly versions should be 4 numbers. I assume @ryancheung passed the wrong version to the build script.

**Comment by ryancheung** [comment] 2020-05-26 11:30
I think any version string like 3.7.300 or even 3.8 is ok. There're valid version numbers. We have to support any of them. Or we were limited to 4 number version strings.

**Comment by harry-cpp** [comment] 2020-05-26 13:44
No, again, its a thing in C#, your assembly versions should be 4 digit. The best we can do is when you pass an incorrect version to CAKE script, it auto corrects it for you.

**Comment by ryancheung** [comment] 2020-05-26 14:59
> The best we can do is when you pass an incorrect version to CAKE script, it auto corrects it for you.

This is a good option.

**Comment by jnoyola** [comment] 2020-05-26 16:35
> If you pass 3.7.300 than msbuild will append a 0 as assembly versions should be 4 numbers. I assume @ryancheung passed the wrong version to the build script.

But I tested it myself. When I use a 3 part version it works fine. I wasn’t able to reproduce this issue.

**Comment by jnoyola** [comment] 2020-05-26 17:39
I'm still curious, did your original nuget package not have the correct folder structure? Because you said it was the same as mine (the correct path), but then you said your change fixes it (implying it originally had the incorrect path).

**Comment by ryancheung** [comment] 2020-05-26 22:53
The nuget structure is here in the screenshot https://github.com/MonoGame/MonoGame/issues/7150#issuecomment-633896847
It's not the same as you maybe. And when I apply the quick fix, it works with three number version https://user-images.githubusercontent.com/240899/82882626-ea595580-9f73-11ea-929d-e27b2acf6947.PNG

**Comment by jnoyola** [comment] 2020-05-27 00:02
Ah you're right, they were different in that screenshot. Ok so to summarize:

* We still don't know why the .0 was appended. I tried replicating this issue, but the .0 wasn't appended for me.
* Changing `PackageVersion` to `Version` seems to fix the issue. We could also recommend people only use the standard 4 part version or auto-fix it in the script.
* I'm going to mess around with keeping `Builder.Task` independent of the `dotnet-mgcb` tool to see how many movie parts it removes.

**Comment by ryancheung** [comment] 2020-05-27 00:32
> * We still don't know why the .0 was appended. I tried replicating this issue, but the .0 wasn't appended for me

Did you build with cake?

**Comment by jnoyola** [comment] 2020-05-27 00:36
> Did you build with cake?

I did. The only difference might be that I called the `-build-target=BuildTools` instead of the entire build. Can you try that? And maybe try what you were doing before too just to confirm that it consistently adds the .0?

**Comment by jnoyola** [comment] 2020-05-28 02:20
Opened a PR that could obsolete this whole class of errors. I'm curious what people think. It greatly simplifies the Builder.Task, and the `dotnet-mgcb` global tool is still there if you want it.

**Comment by ryancheung** [comment] 2020-05-28 03:25
> I did. The only difference might be that I called the `-build-target=BuildTools` instead of the entire build. Can you try that? And maybe try what you were doing before too just to confirm that it consistently adds the .0?

Just rebuild the Task package use `PackageVersion` in csproj and it generated the version number without .0. 
Maybe because I updated nuget or Visual Studio 2019.

**Closed** 2020-07-28 00:23 UTC
