### ISSUE TITLE
Monogame and .Net Core 2.0

### ISSUE THREAD

**Issue by daviatorstorm** [MonoGame/MonoGame#5876] opened 2017-08-16 08:35 UTC
Will Monogame port/support .Net Core 2.0?

**Comment by KonajuGames** [comment] 2017-08-16 10:15
It was just released yesterday, so we haven't even thought about it yet. It
certainly looks like it could, but nothing has been discussed our tried yet.

**Comment by cra0zy** [comment] 2017-08-16 13:21
Duplicate of: #5339, should get closed.

Als:o https://github.com/cra0zy/MonoGameCore (probably should update it with the newest changes...)

**Comment by razorware** [comment] 2018-06-23 19:39
@cra0zy 
Do you have a NuGet? I'm using .NetCore 2.0 and MonoGame is going to my best bet. I'm not sure how much more attention OpenTK.NetCore is going to get. Seems to be waxing interest for some reason.

**Comment by cra0zy** [comment] 2018-06-23 20:46
https://github.com/MonoGame/MonoGame/issues/5339#issuecomment-342686703

Also closing this since its technically a duplicate of #5339

**Closed by cra0zy** 2018-06-23 20:46 UTC
