### ISSUE TITLE
Unable to compile OBJ to XNB

### ISSUE THREAD

**Issue by minhnguyenlinknode** [MonoGame/MonoGame#5395] opened 2017-01-05 16:08 UTC
I have been using Monogame Pipeline tool 3.5.1 to convert OBJ to XNB but got following error message.

![image](https://cloud.githubusercontent.com/assets/9201108/21687356/d9edc092-d360-11e6-94c7-2cc86ba7ed04.png)

I've attached my OBJ for investigation.

[obj.zip](https://github.com/MonoGame/MonoGame/files/687683/obj.zip)

**Comment by Jjagg** [comment] 2017-01-05 19:43
Something goes wrong in assimp when postprocessing. I narrowed it down to FindDegenerates step, commenting that out makes the model build. This seems to be a bug in assimp since the postprocess call returns a nullpointer. Maybe it's fixed in the latest version, assimp should be updated either way for other bugfixes (#4769). I tried with the latest version of AssimpNet which uses assimp 3.1.1 so at least it's not fixed in that version yet.

**Comment by Jjagg** [comment] 2017-01-05 19:49
@minhnguyenlinknode Here's a link to the built xnb, you should be able to use this model 
https://www.dropbox.com/s/fum7htpwkf1f898/ce268263-8ea0-49c3-98ff-8d7ae6875a48_out.xnb?dl=0

**Comment by Jjagg** [comment] 2017-01-05 20:02
Open3mod, the assimp model viewer succesfully imports the model when degenerate primitives are removed, so the issue is most likely fixed in the latest version of assimp.

**Comment by minhnguyenlinknode** [comment] 2017-01-13 17:25
Thanks. I'll check it out and let you know.

**Comment by harry-cpp** [comment] 2020-06-14 12:18
Assimp has been updated, so closing this.

**Closed by harry-cpp** 2020-06-14 12:18 UTC
Labels: ContentPipeline
