### ISSUE TITLE
GameWindow.TextInput is not recording keys - only characters.

### ISSUE THREAD

**Issue by BaronMercury** [MonoGame/MonoGame#6002] opened 2017-10-12 06:41 UTC
The `TextInputEventArgs` objects produced by the `GameWindow.TextInput` Event always have their Key field set to `Keys.None`.

**Comment by cra0zy** [comment] 2018-09-30 14:50
Duplicate of: https://github.com/MonoGame/MonoGame/issues/6447

**Closed by cra0zy** 2018-09-30 14:50 UTC
