### ISSUE TITLE
Cross Platform Desktop Project doesn't support VideoPlayer

### ISSUE THREAD

**Issue by bangclash** [MonoGame/MonoGame#5277] opened 2016-11-05 02:43 UTC
Cross Platform Desktop Project doesn't support VideoPlayer object. Same code doesn't have error in DirectX project.

![capture](https://cloud.githubusercontent.com/assets/10566143/20027061/d0f2345c-a2c6-11e6-8aae-f324c864848e.PNG)

**Comment by cra0zy** [comment] 2016-11-06 09:57
Duplicate of #3983

**Comment by cra0zy** [comment] 2017-05-02 20:42
@tomspilman This is a duplicate, it can be closed.

**Closed** 2017-05-02 20:45 UTC
