### ISSUE TITLE
Shader compile failed on Linux

### ISSUE THREAD

**Issue by demonixis** [MonoGame/MonoGame#2080] opened 2013-10-12 07:33 UTC
Hi, I've an error with my game since I've update latest MonoGame revision. When I run the game the shader compilation failed and I've a black screen.

You can see errors in this screenshot http://www.hostingpics.net/viewer.php?id=232784shaderError.png How can I fix that ? Have you an idea ?

Thanks

**Comment by cra0zy** [comment] 2017-04-29 15:06
@tomspilman  This is duplicate of #2167 and therefore can be closed.

**Closed** 2017-04-30 01:33 UTC
