### ISSUE TITLE
RenderTarget2D.SaveAsJpeg NotImplementedException

### ISSUE THREAD

**Issue by vmachacek** [MonoGame/MonoGame#2269] opened 2014-03-10 13:27 UTC
Hi Everyone, 

Im trying to use renderTarget2D.SaveAsJpeg() with iOS build I got System.NotImplementedException: The requested feature is not implemented". Is there any known workaround?

**Comment by Jjagg** [comment] 2018-12-11 21:46
Duplicate of #1615.

**Closed by Jjagg** 2018-12-11 21:46 UTC
