### ISSUE TITLE
Wireframe mode broken (Windows build)

### ISSUE THREAD

**Issue by StainlessTobii** [MonoGame/MonoGame#6505] opened 2018-10-18 07:31 UTC
Setting the fill mode in rasterizer state to FillMode.WireFrame does nothing

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- WindowsDX

**Comment by tomspilman** [comment] 2018-10-18 13:21
Thanks for reporting this... that would be a pretty big bug.

**Comment by tomspilman** [comment] 2018-10-18 15:43
> Are you doing this thru spritebatch

Also realize that wireframe is still textured if your primitive/sprite is textured.  

So if for instance your sprite has transparency at the edges... you won't see the wireframe along the edges of the quad like some would expect.

**Comment by StainlessTobii** [comment] 2018-10-19 07:56
Hi Tom,

No this is all 3D. I have written a multi-threaded renderer for myself and it caches RasterizerStates.

In an effort to work out why some sub-meshes appear to have broken lighting, I changed all the cached states to have FillMode.WireFrame.

Nothing happened, everything was still filled and shaded.

Meshes end up being rendered by DrawIndexPrimitives.....

I will check and see if I can see anything else.

**Comment by roy-t** [comment] 2019-01-05 10:56
Are you sure it is not your code? Because I was not able to reproduce this with the following rasterizer state:

```
var rasterState = new RasterizerState
{
        CullMode = CullMode.None,
        FillMode = FillMode.WireFrame
;
```

Both models (using `Mesh.Draw`) and drawing myself using `DrawUserIndexedPrimitives` properly render in wireframe mode:

![wireframe](https://user-images.githubusercontent.com/623634/50723619-6bdee800-10e0-11e9-86cf-7a3fe284662b.PNG)

Maybe something else is changing the device state later. Can you reproduce the problem in a smaller build or is the code available somewhere?

**Comment by StainlessTobii** [comment] 2019-01-07 10:05
Hi Roy,

I will do some more tests to se if I can track it down.

My renderer is heavily multi-threaded so it may be an issue with that. Luckily I have built in a graphical profiler so I should be able to see if it is threading that’s causing the problem.

Thanks for looking at it though

Cheers

Paul


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Jjagg** [comment] 2020-08-04 16:13
Going to close this because multiple people failed to reproduce this.

**Closed by Jjagg** 2020-08-04 16:13 UTC
Labels: DirectX, Help Wanted, Needs Testing
