### ISSUE TITLE
android.runtime.JavaProxyThrowable

### ISSUE THREAD

**Issue by FrancescoBonizzi** [MonoGame/MonoGame#6092] opened 2017-12-01 11:05 UTC
Hi!

I published an Android game with Monogame 3.6, from the crashes reports I see:

I check my code and I cannot reproduce it, so it doesn't seem a regular error, but I'd like to fix it anyway.

Do you have any clue? Can I give you more informations?

```
android.runtime.JavaProxyThrowable: at Microsoft.Xna.Framework.Graphics.GraphicsExtensions.GetGLFormat (Microsoft.Xna.Framework.Graphics.SurfaceFormat format, Microsoft.Xna.Framework.Graphics.GraphicsDevice graphicsDevice, OpenTK.Graphics.ES20.PixelInternalFormat& glInternalFormat, OpenTK.Graphics.ES20.PixelFormat& glFormat, OpenTK.Graphics.ES20.PixelType& glType) [0x00016] in <8335ffb25c73411d8c018e841c87a942>:0
at Microsoft.Xna.Framework.Graphics.Texture2D+<>c__DisplayClass4.<PlatformConstruct>b__3 () [0x00022] in <8335ffb25c73411d8c018e841c87a942>:0
at Microsoft.Xna.Framework.Threading+<>c__DisplayClass1.<BlockOnUIThread>b__0 () [0x00019] in <8335ffb25c73411d8c018e841c87a942>:0
at Microsoft.Xna.Framework.Threading.Run () [0x0002a] in <8335ffb25c73411d8c018e841c87a942>:0
at Microsoft.Xna.Framework.AndroidGameWindow.OnUpdateFrame (System.Object sender, OpenTK.FrameEventArgs frameEventArgs) [0x0001d] in <8335ffb25c73411d8c018e841c87a942>:0
at OpenTK.GameViewBase.OnUpdateFrame (OpenTK.FrameEventArgs e) [0x00008] in <451b7a4f0a5d45abb436100a4f7c5bf6>:0
at OpenTK.Platform.Android.AndroidGameView.UpdateFrameInternal (OpenTK.FrameEventArgs e) [0x00009] in <451b7a4f0a5d45abb436100a4f7c5bf6>:0
at OpenTK.Platform.Android.AndroidGameView.RunIteration (System.Threading.CancellationToken token) [0x00073] in <451b7a4f0a5d45abb436100a4f7c5bf6>:0
at OpenTK.Platform.Android.AndroidGameView+<>c__DisplayClass59_0.<StartThread>b__1 (System.Object _) [0x00000] in <451b7a4f0a5d45abb436100a4f7c5bf6>:0
at Android.App.SyncContext+<>c__DisplayClass3_0.<Send>b__0 () [0x00000] in <e0c0cc8d857046a2b6a8a56ff4053f11>:0
at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <e0c0cc8d857046a2b6a8a56ff4053f11>:0
at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <e0c0cc8d857046a2b6a8a56ff4053f11>:0
at (wrapper dynamic-method) System.Object:b6c46774-2c5e-43a1-9683-c699198a9a2b (intptr,intptr)
  at mono.java.lang.RunnableImplementor.n_run (Native Method)
  at mono.java.lang.RunnableImplementor.run (RunnableImplementor.java:30)
  at android.os.Handler.handleCallback (Handler.java:751)
  at android.os.Handler.dispatchMessage (Handler.java:95)
  at android.os.Looper.loop (Looper.java:154)
  at android.app.ActivityThread.main (ActivityThread.java:6682)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1520)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1410)
```

**Comment by Juhlinus** [comment] 2017-12-02 03:32
Is there a possibility that you could clone the MonoGame repo and build it to see if the issue is resolved? I'm guessing this issue is related to OpenTK, and since the team has started removing OpenTK little by little it could be that this has been fixed.

**Comment by FrancescoBonizzi** [comment] 2017-12-02 08:48
All right, I'll try that! Thank you, I'll let you know!

**Comment by Juhlinus** [comment] 2017-12-02 08:53
Great! OpenTK should be removed completely from the `develop-branch`, so if OpenTK is the cause, then you should be fine.
Let us know if it works out!

**Comment by FrancescoBonizzi** [comment] 2017-12-04 08:00
Hi guys, it seems that the problem is solved! Thanks!

Are there some plans to distribute via Nuget a 3.6.x version of Monogame? It would be really appreciated for everyone I think!

Thanks again for all you work,
Francesco.

**Comment by Jjagg** [comment] 2017-12-04 13:08
You mean develop, right? That's 3.7.x. 
There's a NuGet feed for the develop version. From the [Downloads](http://www.monogame.net/downloads/) page: 
> You could also add our [develop branch NuGet feed](http://teamcity.monogame.net/guestAuth/app/nuget/v1/FeedService.svc/) to your IDE to get the latest development assemblies.

**Comment by FrancescoBonizzi** [comment] 2017-12-04 13:12
Perfect, thank you!

**Comment by FrancescoBonizzi** [comment] 2018-05-23 16:47
I had to reopen this issue because after a lot of time that my game is in production with `MonoGame.Framework.Android 3.7.0.1467-develop`, I saw another time that error.

In particular on: `Motorola Moto X (4) (payton_sprout), 3072MB RAM, Android 7.1`

```
android.runtime.JavaProxyThrowable: at Microsoft.Xna.Framework.Graphics.Texture2D.GenerateGLTextureIfRequired () [0x000be] in <fdb773441760472fa5405ad8aa1656f7>:0
at Microsoft.Xna.Framework.Graphics.Texture2D+<>c__DisplayClass1.<PlatformConstruct>b__0 () [0x00000] in <fdb773441760472fa5405ad8aa1656f7>:0
at Microsoft.Xna.Framework.Threading+<>c__DisplayClass1.<BlockOnUIThread>b__0 () [0x00019] in <fdb773441760472fa5405ad8aa1656f7>:0
at Microsoft.Xna.Framework.Threading.Run () [0x0002a] in <fdb773441760472fa5405ad8aa1656f7>:0
at Microsoft.Xna.Framework.AndroidGameWindow.OnUpdateFrame (System.Object sender, Microsoft.Xna.Framework.MonoGameAndroidGameView+FrameEventArgs frameEventArgs) [0x0000b] in <fdb773441760472fa5405ad8aa1656f7>:0
at Microsoft.Xna.Framework.MonoGameAndroidGameView.UpdateFrameInternal (Microsoft.Xna.Framework.MonoGameAndroidGameView+FrameEventArgs e) [0x0000f] in <fdb773441760472fa5405ad8aa1656f7>:0
at Microsoft.Xna.Framework.MonoGameAndroidGameView.UpdateAndRenderFrame () [0x00058] in <fdb773441760472fa5405ad8aa1656f7>:0
at Microsoft.Xna.Framework.MonoGameAndroidGameView.processStateRunning (System.Threading.CancellationToken token) [0x0005b] in <fdb773441760472fa5405ad8aa1656f7>:0
at Microsoft.Xna.Framework.MonoGameAndroidGameView.RunIteration (System.Threading.CancellationToken token) [0x000e0] in <fdb773441760472fa5405ad8aa1656f7>:0
at Microsoft.Xna.Framework.MonoGameAndroidGameView+<>c__DisplayClasse.<WorkerThreadFrameDispatcher>b__c (System.Object s) [0x00017] in <fdb773441760472fa5405ad8aa1656f7>:0
at Android.App.SyncContext+<>c__DisplayClass3_0.<Send>b__0 () [0x00000] in <c53e868e1c3d4712a3b2b3a3c9214693>:0
at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <c53e868e1c3d4712a3b2b3a3c9214693>:0
at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <c53e868e1c3d4712a3b2b3a3c9214693>:0
at (wrapper dynamic-method) System.Object.1fb5367f-4839-423f-aae7-cacbd26f2d6c(intptr,intptr)
  at mono.java.lang.RunnableImplementor.n_run (Native Method)
  at mono.java.lang.RunnableImplementor.run (RunnableImplementor.java:30)
  at android.os.Handler.handleCallback (Handler.java:751)
  at android.os.Handler.dispatchMessage (Handler.java:95)
  at android.os.Looper.loop (Looper.java:154)
  at android.app.ActivityThread.main (ActivityThread.java:6165)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:888)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:778)
```

Can I give you more informations? I can't reproduce the issue on my device.

**Comment by cra0zy** [comment] 2018-09-30 14:31
Closing as the reopened issue has no connection with the original issue.

**Closed by cra0zy** 2018-09-30 14:31 UTC
