### ISSUE TITLE
WebVR and Web Assembly - Possibility in the future

### ISSUE THREAD

**Issue by LukeTOBrien** [MonoGame/MonoGame#6628] opened 2019-01-06 13:05 UTC
Hello there,

This is something to put in your pipe and smoke... Or open discussion.

I have recently been interested in seeing if MonoGame could work with [Blazor](https://blazor.net/), I have come to the conclusion that I will have to wait for .Net Core support https://github.com/MonoGame/MonoGame/issues/5339 planned in [3.8 Release](https://github.com/MonoGame/MonoGame/milestone/14).

Two of the [Use Cases for Web Assembly](https://webassembly.org/docs/use-cases/) are Virtual Reality and games, both of which MonoGame would be great for.

I am also interested by a WebVR project called [A-Frame](https://aframe.io/) which uses ThreeJS and I believe that in the future MonoGame could be used for a similar project built from server-side [Razor Components](https://blazor.net/docs/components/index.html) rather than client-side (custom) HTML.

In fact the [demo on the Web Assembly website](https://webassembly.org/demo/) is Tanks! which is a Unity game, built in C# I would assume (unless the Wasm guys converted to C++), so it is realistic to think that MonoGame could also be used with Web Assembly in the same way.

As well as all this, a MonoGame web app built with Blazor could also open up [Electron](https://electronjs.org/) and [Cordova](https://cordova.apache.org/) as new platforms.

What do you think about all this?  
Blazor is still experimental so it could be distant future stuff, but still possible.

Luke

**Comment by roy-t** [comment] 2019-01-06 13:37
@LukeTOBrien have you seen this: http://community.monogame.net/t/monogame-for-web-alpha-release/11019 ?

**Comment by Jjagg** [comment] 2019-01-06 13:41
MonoGame can currently be compiled for web using Bridge.NET (which transpiles C# to JS). We'd like to compile to WebAssembly directly, but that's still experimental. People are working on it in the CoreRT project.

Blazor sits in between those two in a way since it uses a .NET runtime compiled to WASM. I don't know what the value is for MG to support Blazor as a platform, because it's not the end goal for the MG web build and we already have a working web build. Not sure if it's warranted to divert resources to MG Blazor, but I'm curious for any arguments to implement a Blazor platform.

> In fact the demo on the Web Assembly website is Tanks! which is a Unity game, built in C# I would assume (unless the Wasm guys converted to C++)

Yes, Unity transpiles to C++ before compiling down to WASM.

> As well as all this, a MonoGame web app built with Blazor could also open up Electron and Cordova as new platforms.

I don't really see the point of this. MonoGame natively targets mobile (using Xamarin) and desktop. Why use web technology?

> I am also interested by a WebVR project called A-Frame which uses ThreeJS and I believe that in the future MonoGame could be used for a similar project built from server-side Razor Components rather than client-side (custom) HTML.

This is orthogonal to the Blazor feature request, I suppose. We should have a separate discussion for this.

**Comment by LukeTOBrien** [comment] 2019-01-06 14:19
> I don't really see the point of this. MonoGame natively targets mobile (using Xamarin) and desktop. Why use web technology?

@Jjagg Because it provides an alternative, web technologies are the future and it might be an easier development experience, HTML for the UI.  
Xamarin for iOS still requires a Mac for compilation and cross-plaform solution requires many projects, but with web it is much simpler.

@roy-t Thank you for the link. - I had not seen that before.  
As Blazor is now part of the [central ASP.NET Core repo](https://github.com/aspnet/AspNetCore/tree/master/src/Components) and Web Assembly is supposed to be faster than JavaScript (although at the moment I think it is slower) I think it would be good to consider Web Assembly for the future.  
Blazor will load up .dll files as opposed to generating JS.

**Comment by Jjagg** [comment] 2019-01-06 14:46
> web technologies are the future

I know this is hotly debated, but I don't believe they are. Not in the way Cordova does it anyway. Performance will take a big hit compared to native apps.

> and it might be an easier development experience, HTML for the UI.

This is not exclusive to Blazor. Bridge.NET lets you interact with the DOM and I expect CoreRT will also expose it in some way.

> Xamarin for iOS still requires a Mac for compilation

So does Cordova: https://cordova.apache.org/docs/en/latest/guide/platforms/ios/index.html

> cross-plaform solution requires many projects

Yeah, I think MG can improve on managing game projects for different platforms. But to be fair, if you'd like to target desktop, mobile and web you'd need 3 different builds with an all web stack (Cordova, Electron, Web) whereas with MG currently you need 4 (DesktopGL, Android, iOS, Web).

**Comment by LukeTOBrien** [comment] 2019-01-06 15:49
> So does Cordova: https://cordova.apache.org/docs/en/latest/guide/platforms/ios/index.html
Yes that is true.  
I forgot to mention that I mostly use [PhoneGap Build](https://build.phonegap.com/), I have managed to sign an app and generate the certificates needed all from Windows. Just upload a .zip to their service and download .ipa file.

> Performance will take a big hit compared to native apps.
But the size of the apps might be smaller, no dependency on Xamarin

> This is not exclusive to Blazor. Bridge.NET lets you interact with the DOM and I expect CoreRT will also expose it in some way.
Bride.NET generates JavaScript and Blazor compiles to Web Assembly.  
At the moment, Web Assembly cannot access the DOM, but in the future that will change.  
Web Assembly is compiled to a lower level than JavaScript and has the potential to be a lot faster.  

It's just something to consider for the future.

**Comment by LukeTOBrien** [comment] 2019-01-06 17:09
> The first time I entered a professional company, back in 1999, I was told that web technologies were the future. One would expect the future would be here by now, but they keep insisting on it :)
🤣 Yes that is true - The future is now!
I create web apps and SaaS/Cloud Computing is a big thing professionally.

> Blazor does not compile to WebAssembly. I mentioned this in my first comment. Compiling to WASM is what we really want in the end. Blazor runs a version of Mono compiled to WASM to run .NET code.
I just read this issue on the Blazor issue board https://github.com/aspnet/Blazor/issues/286  
I think .NET Standard is what we want to target, from what I gather, the folk behind the Blazor project are currently using Mono (and advised by the CoreRT team), but this could change in the future.

> I am also interested by a WebVR project called A-Frame which uses ThreeJS and I believe that in the future MonoGame could be used for a similar project built from server-side Razor Components rather than client-side (custom) HTML.
There used to be a project called [Engine Nine](https://archive.codeplex.com/?p=nine), back in the day I used it and it worked well, you could define primitives and textures using XAML - So this is the kind of thing I was thinking about with server-side Razor Components.  
True this is separate but related.  
If we can manage to get MonoGame compiled to Web Assembly, then a Razor Component library of primitives and other objects would be a good complementary project to start.

**Comment by cra0zy** [comment] 2019-01-08 15:52
Closing this as this is pretty much a duplicate of #3895

**Closed by cra0zy** 2019-01-08 15:52 UTC
Labels: Feature Request

**Comment by LukeTOBrien** [comment] 2019-01-08 18:13
... Slight difference, AOT Web Assembly compilation as opposed to
JavaScript. But I will comment on the thread to make the other chap aware
of this idea.

**Comment by Jjagg** [comment] 2019-01-08 18:31
I'd like to say for a third time that Blazor does not let you compile your project to WebAssembly, but runs a .NET runtime (version of Mono) that's been compiled to WASM. And 'the other chap' is cra0zy himself.

**Comment by LukeTOBrien** [comment] 2019-01-08 20:19
Well I think we'll all a little bit crazy in our own way
