### ISSUE TITLE
MGPT doesn’t build and has occasional crashes

### ISSUE THREAD

**Issue by Hafinator** [MonoGame/MonoGame#6458] opened 2018-09-30 21:14 UTC
It seems I have stumbled upon a problem when using content pipeline. I have just freshly formatted my PC (am running WIN 10, build 1709) and the latest version of VS 2017. After reading that monogame just "levelled up" to 3.7 I figured to give it a go. After pulling a project from my GitHub, I noticed that the VS vas throwing me messages for not building my content prior to running the game (I forgot...), so I grabbed the pipeline tool, added the same content from what was previously used, and hit build, but nothing happens, the output window remains empty, and sometimes it crashes. 

The message that is thrown by VS : Severity	Code	Description	Project	File	Line	Suppression State
Error	The command ""C:\Program Files (x86)\MSBuild\MonoGame\v3.0\Tools\MGCB.exe" /@:"D:\Moji programi\Game1\Game1\Content\Content.mgcb" /platform:Windows /quiet /outputDir:"bin\Windows\Content" /intermediateDir:"obj\Windows\Content"" exited with code 5. Please verify that you have sufficient rights to run this command.	Game1

Error output if you try to import an existing folder, but click Cancel: 
System.InvalidOperationException: File name not available - dialog was canceled.
at Microsoft.WindowsAPICodePack.Dialogs.CommonFileDialog.CheckFileNamesAvailable()
at Microsoft.WindowsAPICodePack.Dialogs.CommonFileDialog.get_FileName()
at MonoGame.Tools.Pipeline.MainWindow.ChooseContentFolder(String initialDirectory, String& folder)
at MonoGame.Tools.Pipeline.PipelineController.IncludeFolder()
at Eto.Forms.Command.OnExecuted(EventArgs e)
at Eto.Forms.Command.System.Windows.Input.ICommand.Execute(Object parameter)
at Eto.Forms.ToolItem.OnClick(EventArgs e)
at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
at System.Windows.Controls.Primitives.ButtonBase.OnClick()
at System.Windows.Controls.Button.OnClick()
at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
at System.Windows.Input.InputManager.ProcessStagingArea()
at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
at System.Windows.Application.RunDispatcher(Object ignore)
at System.Windows.Application.RunInternal(Window window)
at MonoGame.Tools.Pipeline.Program.Main(String[] args)

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- Windows 10

#### What MonoGame platform are you using:

- WindowsDX

**Comment by cra0zy** [comment] 2018-10-01 05:28
Duplicate of #6448, already fixed.

**Closed by cra0zy** 2018-10-01 05:28 UTC
