### ISSUE TITLE
[Mac/iOS] Content does not seem to copy from shared project

### ISSUE THREAD

**Issue by Dokug** [MonoGame/MonoGame#7897] opened 2022-08-02 16:59 UTC
After upgrading my existing solution to MonoGame v3.8.1 (from 3.8) I found that my setup with a dedicated iOS/Mac/Windows project and a shared MonoGame library does not seem to work anymore for iOS and Mac.
It seems as if the .xnb files created by mgcb do not get copied to the correct directory, as the LoadContent() method throws a FileNotFoundException() when executing my guard logic against missing files. (Basically the file Content/[...].xnb is not found.)

Am I missing a step in the upgrade guide?
I added a new iOS project (that is basically empty anyway, as the whole thing uses the shared library), which I generated from the template.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.1.303

#### What operating system are you using:
- MacOS

#### What MonoGame platform are you using:

- iOS

**Comment by AndreyFromGomel** [comment] 2022-08-02 17:24
I have the same issue for iOS project, but macOS and Android projects works well for me.

**Comment by kurtcz** [comment] 2022-08-13 05:57
Same for me, iOS project is unable to find any xnb files - I am using the MG 3.8.1.303 templates and MGCB editor. The files are not getting copied to the output folder

**Comment by damian-666** [comment] 2022-08-13 12:32
what  i do in the meantime (i dont have ios licnese. so cant help) is  I just  use the mgcb editor and build everything and copy the xnb files directly and move to other bin folders that all got moved around with fresh project files i had to make, as this gets sorted out for the various build tools being used.   but have similar problems with a legacy level editor , that used .netstandard 2 and moving that to net6 really introduct sublte weirdness.  I just  use the mgcb editor and build everything and copy the xnb files directly and move to other bin folders that all got moved around with fresh project files i had to make, as this gets sorted out for the various build tools being used.   check the paths that the .net libs the new project files simpler, but you lost your old setup.      im havign a ton of problesm and dont have an ios license so i cant build and trace MG and help or seee why thsi happened.. it works for me but i used to just build and embedded xnb files like nez does, as embedded resources in the shared DLL, but then the copy and build of content, works for osx and GL and windows netcore, so i stopped dong that because i wanted shader transpiling.      ****The shared project should be part of the test suilte.****  right now even the sample is not updated.. def needs help but im swamped.

**Comment by inkcomic** [comment] 2022-09-03 08:28
> Same for me, iOS project is unable to find any xnb files - I am using the MG 3.8.1.303 templates and MGCB editor. The files are not getting copied to the output folder. Android project is able to load them just fine.

Same for me, Same code shared by two project, for Mac the resource can be exported to output folder correctlly, for iOS not.

**Comment by impworks** [comment] 2022-09-03 11:34
Having the same problem. Not even using a shared project, just creating a new app from default template for iOS and adding a single content file already fails to work. This is a showstopper for me :(

Steps to reproduce:
1. Create a sample project using MonoGame iOS template
2. Change minimum iOS version to 15.0
3. Add an image to Content.mgcb, build it
4. Add code to load and draw the the image
5. Deploy to device and run it

Repro project here:
https://github.com/impworks/monogame-ios-content-bug

**Comment by damian-666** [comment] 2022-09-03 23:36
The show must go on... Can u manually.copy. it? For now just to get unstcuk? If u aren't working on shader.....or...do the shaders.work.on another.platfrom,    Someone admit it's may be Acore bug just 
 for Mac tool. it's so hard to maintain 14 targets and there lot of help wanted...tags.. and its summer. those repro projects  realy help tho. I finally after 4 weeks almost done all thisnet 6 hell  update. Also there is a copy target to output folder.  Gave me tons of issues w net6 paths..
  Bit if we were usjng unity or unreal it would be a full year before their stuff updated..and we wouldn't have the source unless we pay big $$$

**Comment by impworks** [comment] 2022-09-05 09:45
Here's a temporary workaround until the bug is fixed:

1. Mark all XNB files in the project as `EmbeddedResource`
2. Create a custom `ContentManager` class that inherits from the default one, but overrides `OpenStream` to use `Assembly.GetManifestResourceStream` internally
3. Use the new content manager instead of the default one in your `Game` implementation

**Comment by damian-666** [comment] 2022-09-05 10:58
That's what Nez does..or did. I think u can take his content manager..still sucks to do all that and I stopped  because of another issue.

**Comment by corykroll** [comment] 2022-11-06 17:31
I've found a fix that works in my own development testing that I'm putting together a PR for.
The MonoGame.Content.Builder.Task.targets file needs the following added to the PropertyGroup (right below the DisableFastUpToDateCheck tag):

`  
<PropertyGroup>
    <DisableFastUpToDateCheck>true</DisableFastUpToDateCheck>
	<CollectBundleResourcesDependsOn>
		  IncludeContent;
	</CollectBundleResourcesDependsOn>
  </PropertyGroup>
`

This is based on a similar issue logged here where BundleResource in targets was not working - the same issue I see in this issue:
https://github.com/xamarin/xamarin-macios/issues/11984

**Comment by dellis1972** [comment] 2024-03-12 11:12
I think we can close this issue as the PR #7961  was merged

**Closed** 2024-03-12 14:59 UTC
Labels: iOS, Help Wanted
