### ISSUE TITLE
Volume Down is interpreted as Keys.C

### ISSUE THREAD

**Issue by Pixelnicks** [MonoGame/MonoGame#6235] opened 2018-03-07 20:59 UTC
#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- DesktopGL

The Volume Down key on a laptop is interpreted as Keys.C 

`KeyboardState ks = Keyboard.GetState();`

`// The following is output whether the user presses C or Volume Down`
`if (ks.IsKeyDown(Keys.C))`
`  Console.WriteLine("C or Volume Down is pressed");`

`// Keys.VolumeDown will never fire`
`if (ks.IsKeyDown(Keys.VolumeDown))`
`  Console.WriteLine("This will never print");`

**Comment by cra0zy** [comment] 2018-03-07 21:40
Hmm, just tested this and it works fine for me. What keyboard layout are you using?

**Comment by Pixelnicks** [comment] 2018-03-07 21:50
Interesting. I use the UK keyboard layout on two different models of laptop.

**Comment by cra0zy** [comment] 2018-03-07 21:57
Yup, can't reproduce it.

**Comment by tomspilman** [comment] 2018-03-07 22:19
@cra0zy - So this must be an SDL2 issue correct?

@Pixelnicks - Can you share the make/model of laptop?  Is this one of these keys where you have to press some other function key first?  Is there any key remapping software running on the laptop?

**Comment by cra0zy** [comment] 2018-03-07 22:27
> @cra0zy - So this must be an SDL2 issue correct?

Most likely.

**Comment by Pixelnicks** [comment] 2018-03-07 22:34
It occurs on two laptops:

Dell XPS 13 4243
Volume down: FN+F2

ASUS ZenBook UX430UA-GV415T
Volume down: FN+F11

**Comment by tomspilman** [comment] 2018-03-07 22:39
Curious it occurs on two very different laptops.

Can someone else check `Keys.VolumeDown` on their laptop to see if maybe this has just always been broken?

**Comment by Pixelnicks** [comment] 2018-03-07 22:48
Here's a list of all special keys which are mapped incorrectly for me:

Volume Up: B
Volume Down: C
Mute: D
Touchpad enable/disable: LeftControl & LeftWindows

**Comment by tdeeb** [comment] 2018-03-08 07:22
This happened to me on MonoGame 3.5 and still happens on 3.7.0.1129. I'm on an Alienware 15 R3, and it doesn't seem to occur until I've pressed the C key at least once. It reports most of the same mappings Pixelnicks has for me as well. I'll list everything for completeness:

Volume Up: B
Volume Down: C
Mute: D
Airplane Mode: D3
Disable Windows Key (Fn + F6): F9
I/D GFX (switches integrated and discrete GPUs on supported models - does nothing on this one): Space
Project (Fn + F8): Left Windows
Brightness Down: D4
Brightness Up: D5
Touchpad Toggle (not supported on this model): Escape

**Comment by tomspilman** [comment] 2018-03-08 07:32
@cra0zy - Seems like we need to make a simple SDL2 test app and verify this is a SDL2 bug and if so report it to them to review.

**Comment by cra0zy** [comment] 2018-03-08 08:38
Sure, I'll cook up an example in C.

**Comment by Quinn-L** [comment] 2018-03-16 02:39
I think the SDL team were aware of this, as I think this bug tracker mentions something like this:
https://bugzilla.libsdl.org/show_bug.cgi?id=3247

I'm struggling to navigate the website to figure out where this commit is placed, but I think it's part of release-2.0.6 (as per fishing through the link of the last comment in that bug tracker).

**Comment by cra0zy** [comment] 2018-03-16 10:09
I forgot too cook up an example in C, sorry about that.

> I'm struggling to navigate the website to figure out where this commit with the fix is placed, but I think it's part of release-2.0.6 (as per fishing through the link of the last comment in that bug tracker).

Awesome, so we just need to update SDL.

**Comment by Jjagg** [comment] 2018-05-09 16:32
SDL was updated to 2.0.7 in #6186, so this is fixed :)

**Comment by cra0zy** [comment] 2018-05-09 19:03
Nope, it only got bumped up for Linux back then.

**Comment by tdeeb** [comment] 2018-06-12 21:04
Is there any progress on this? What would be required to update and test SDL within MonoGame?

**Comment by cra0zy** [comment] 2018-06-12 21:13
We are waiting for @tomspilman, he started doing some work with new dependencies(assimp and NVTT), merged the PR to dependencies repo, than stopped midway so now no new dependencies can be submitted until that work gets done :(

Also waiting for build bot to come online as well.

**Comment by dellis1972** [comment] 2018-06-26 09:24
@cra0zy the bots and up :) and I think the assimp/nvtt stuff is done now

**Comment by cra0zy** [comment] 2018-06-26 10:58
They are not, still waiting for the @tomspilman assimp dependency bump PR.

**Comment by tomspilman** [comment] 2018-06-26 23:46
@dellis1972 @cra0zy - I'll get that fixed up this week.

**Comment by cra0zy** [comment] 2018-07-24 12:07
SDL 3.0.8 has been merged, this issue should be fixed in devel.

**Closed by cra0zy** 2018-07-24 12:07 UTC
Labels: Help Wanted
