### ISSUE TITLE
XACT Cue Doppler effect is not implemented

### ISSUE THREAD

**Issue by OlegSkripnyak** [MonoGame/MonoGame#6927] opened 2019-11-02 00:17 UTC
I was going to use the Doppler effect of moving sounds in my game using cues, after spending half a day, checked the code. Its just not implemented (!)
```
                // Calculate doppler effect.
                var relativeVelocity = emitter.Velocity - listener.Velocity;
                relativeVelocity *= emitter.DopplerScale;
```
The DopplerPitchScalar variable of a cue instance is not used at all. See the /MonoGame/MonoGame.Framework/Audio/Xact/Cue.cs#Apply3D
I'm sure its not optimized mathematically, but here is my implementation
```
                // Calculate doppler effect.
                var distancePlusVelocity = ((listener.Position + listener.Velocity) - (emitter.Position + emitter.Velocity)).Length();
                var relativeVelocity = (distance - distancePlusVelocity) * emitter.DopplerScale; // negative if moving away, positive if gets closer
                var dopplerPitchScalar = (1f + relativeVelocity / SoundEffect.SpeedOfSound) / (1f - relativeVelocity / SoundEffect.SpeedOfSound);
                var d = FindVariable("DopplerPitchScalar");
                _variables[d].SetValue(dopplerPitchScalar);
```
So what is going on here

1. We have a distance between listener and emitter now in relative units, say meters.
2. We calculate distance between them in next second, after velocity was applied.
3. So we get relative velocity in meters per second by (1st - 2nd distance).
4. This relative velocity is actually used as V in the Doppler equation 
![Doppler equation](
https://wikimedia.org/api/rest_v1/media/math/render/svg/4a76f04dcc2cfddd73fbf5cc44f30fa1a8554ef3)
, where C is the speed of sound in environment, W0 is original frequency and W is final frequency. I was implemented it by Russian Wiki (https://ru.wikipedia.org/wiki/Эффект_Доплера), seems there is the same formula in English Wiki, but looking different.
5. This multiplier of W0 and the DopplerPitchScalar variable for XACT are the same
![XACT RPC](https://i.imgur.com/5C2atbx.png) just found it empirically, and it worked, but can't be fully sure.
Can you guys implement it correctly ?
Thanks !

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7.1

#### What operating system are you using:
- Windows 10

#### What MonoGame platform are you using:

- DesktopDX

**Comment by OlegSkripnyak** [comment] 2019-12-07 03:49
Seems that it's wrong, if there both listener and emitter velocities > 0
Was searching for a solution, and found this for C++
https://gamedev.stackexchange.com/questions/23583/how-do-i-simulate-a-doppler-effect-in-a-game
Actually there is no scalar calculated, but it can be simply guessed.
If someone interested, here is my code for both calculations of volume and the doppler:
```
            soundElements.ForEach(e =>
            {
                var cuePosition = new Vector3(e.PhysicPosition, 0);
                var distance = cuePosition - ScreenCenter;
                var distanceLength = distance.Length();
                e.Cue.SetVariable("Distance", distanceLength);
                var dopplerPitchScalar = 1.0f;
                if (e.AssociatedBody != null)
                {
                    //https://gamedev.stackexchange.com/questions/23583/how-do-i-simulate-a-doppler-effect-in-a-game
                    var screenVelocity = Vector3.Dot(ScreenVelocity, distance) / distanceLength;
                    var cueVelocity = Vector3.Dot(new Vector3(e.AssociatedBody.LinearVelocity, 0), distance) / distanceLength;
                    var relativeVelocity = screenVelocity - cueVelocity;
                    dopplerPitchScalar = (1f + relativeVelocity / SoundEffect.SpeedOfSound) / (1f - relativeVelocity / SoundEffect.SpeedOfSound);
                    //Console.WriteLine($"C: {ScreenCenter}, V: {ScreenVelocity}, D: {dopplerPitchScalar}");
                }
                e.Cue.SetVariable("DopplerPitchScalar", dopplerPitchScalar);
            });
```

**Comment by Jjagg** [comment] 2020-07-28 00:44
Duplicate of #5740.

**Closed by Jjagg** 2020-07-28 00:44 UTC
Labels: Audio
