### ISSUE TITLE
Mac MonoGame performs faster with ".HardwareModeSwitch = false" but scaling wrong

### ISSUE THREAD

**Issue by mdrejhon** [MonoGame/MonoGame#6308] opened 2018-05-02 04:23 UTC
Strange results are happening if I don't enable .HardwareModeSwitch on Mac.

Scaling is correct only if I enable HardwareModeSwitch (mouse coordinates matches spriteBatch coordinates).   But if I avoid HardwareModeSwitch (set to false), the same resolution performs faster but the scaling is all out of whack -- mouse coordinates do not match spriteBatch coordinates.

```
// Out of whack on Mac for mouse-vs-spritebatch coordinates, but performs a bit faster
graphics.HardwareModeSwitch = false;
graphics.IsFullScreen = true;
graphics.PreferredBackBufferWidth = GraphicsAdapter.DefaultAdapter.CurrentDisplayMode.Width;
graphics.PreferredBackBufferHeight = GraphicsAdapter.DefaultAdapter.CurrentDisplayMode.Height;
graphics.ApplyChanges();
```

versus

```
// Correctly scaled (mouse coordinates matches sprite batch coordinates), but performs a bit slower
graphics.HardwareModeSwitch = true;
graphics.IsFullScreen = true;
graphics.PreferredBackBufferWidth = GraphicsAdapter.DefaultAdapter.CurrentDisplayMode.Width;
graphics.PreferredBackBufferHeight = GraphicsAdapter.DefaultAdapter.CurrentDisplayMode.Height;
graphics.ApplyChanges();
```

Same buffer resolution, but different pros/cons.   Performance seems about 30% slower if I do a hardware mode switch on Mac.

Desired fix is to make sure that MonoGame Mac mouse coordinates + sprite batch coordinates are in sync.  

To verify if I did something wrong -- I checked scaling parameter variables and there's no way to detect how it's scaled -- it is not an exact 2:1 scaling (e.g. 1280x800 -> 2560x1600) but some kind of odd 1.6 or 1.7 scaling factor as if it forgot to internally update some internal variables.   I tried the Matrix.CreateScale tricks with hardcoded values but the 'odd' values make this hard -- there's no way to detect the correct 'weird' scaling as all the querying/metrics say 1280x800.

The problem does not happen on a PC (coordinates stay in sync).  So there might be an internal scaling calculation issue.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7.0.1494

#### What operating system are you using:
- Mac

#### What MonoGame platform are you using:

- DesktopGL

**Comment by mdrejhon** [comment] 2018-05-02 15:41
**The BIG problem is there's no way to detect the scaling ratio.**

**Comment by cra0zy** [comment] 2018-05-02 16:31
`HardwareModeSwitch = false` does no scaling, of any kind, so you can just fetch the window width/height for the sizes.

Also you can control if the system will try to DPI scale your app with the plist file. See #4802

**Comment by mdrejhon** [comment] 2018-05-02 16:45
Window width/height doesn't seem to help in scaling calculations -- the buffer is 1280x800, the preferred back buffer is 1280x800, the viewport is 1280x800, the window size is 1280x800 (but is full screen), and it's a 2560x1600 MacBook at default 2:1 retina scaling.   

There's no ratios I'm able to get to the oddball ratio.

I will try all the tips in #4802 first, to see if the .plist tweaking helps at all, and report back.  

But I feel should still be able to mathematically calculate the ratio (I can't) even without that -- no ratios are available.

**Comment by cra0zy** [comment] 2018-09-30 13:51
Closing as part of this is not a bug, and the other part is #4802.

**Closed by cra0zy** 2018-09-30 13:51 UTC
