### ISSUE TITLE
3.8.0.1082: Pipeline Tool - crash on startup

### ISSUE THREAD

**Issue by s-m-k** [MonoGame/MonoGame#7161] opened 2020-05-24 17:18 UTC
The Pipeline Tool installed with 3.8.0.1082, which is the build currently linked on the website, doesn't launch (possibly a crash on startup).

Windows 10
#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.0.1082

#### What operating system are you using:
- Windows 10

#### What MonoGame platform are you using:
- DesktopGL

**Comment by harry-cpp** [comment] 2020-05-24 17:52
Duplicate of: https://github.com/MonoGame/MonoGame/issues/7057

**Closed by harry-cpp** 2020-05-24 17:52 UTC
