### ISSUE TITLE
Empty Window on macOS Mojave

### ISSUE THREAD

**Issue by mbmleone** [MonoGame/MonoGame#6724] opened 2019-04-28 22:54 UTC
Hello everybody,

MonoGame gives an empty window on macOS Mojave.
It does work correctly High Sierra, there everything is painted as expected.
So there seems an incompatibilty that started with Mojave.

This problem can very easily be reproduced with Mac OS Sample:
https://github.com/MonoGame/MonoGame/tree/develop/ProjectTemplates/DotNetTemplate/MonoGame.Templates.CSharp/content/BlankApp.MacOS
When running that demo on Mojave you should notice the color set is not rendered.

Originally I suspected it was an SDL issue.
There is a bug report here that seems a match:
https://bugzilla.libsdl.org/show_bug.cgi?id=4272
However, even SDL 2.0.9 is showing the issue with Monogame.
And there the bug was claimed to be fied.

So it could be something else is going on.
Can someone else also please take a look?
Thanks!

**Comment by mrhelmut** [comment] 2019-04-30 07:18
Hey there,

Our Macs are on Mojave and we have no issues at all (SDL 2.0.7 here).

Would you mind trying a DesktopGL (cross-platform) project instead of a pure MacOS one?

Also, make sure that you have a plist with retina support disabled.

**Comment by mbmleone** [comment] 2019-04-30 23:06
@mrhelmut, many thanks for your quick response, I appreciate it.
You are right that the DesktopGL sample is working on Mojave.

Unfortunately DesktopGL doesn't seem a solution for my project.
We need access to the MacOS Environment also.
And I don't see way to access that in DesktopGL.
So we need the pure MacOS to work also.

This is a sample that shows the problem with pure Mac OS:
[MonogameSample.zip](https://github.com/MonoGame/MonoGame/files/3133401/MonogameSample.zip)
It should give a window with background color.
In Mojave you can however see it stays light gray and doesn't show color that was set.

I really hope there is someone why has an idea how to fix this.
Thanks!

**Comment by mrhelmut** [comment] 2019-05-01 11:33
What's very weird is that Mac projects actually uses the same code and backend as DesktopGL when it comes to graphics and windowing.

There's no apparent reason they should behave differently.

You can manually add a reference to Xamarin.Mac if you need an access to the Mac API.

**Comment by AidanMcK** [comment] 2019-08-03 21:29
I had to switch some time ago from using the Mac project to a DesktopGL one to get things to work for me. I can't remember what the problem was now (sorry!), but just to point out  that there are differences somewhere.

**Comment by harry-cpp** [comment] 2020-03-25 23:32
Gonna close this as I cannot reproduce it either.

**Closed by harry-cpp** 2020-03-25 23:32 UTC
Labels: MacOS, Need Info
