### ISSUE TITLE
Error when opening the Pipeline Tool in Visual Studio 2019 version 16.5.0

### ISSUE THREAD

**Issue by simoneddeland** [MonoGame/MonoGame#7061] opened 2020-03-18 08:57 UTC
After upgrading Visual Studio 2019 Community to version 16.5.0, I get the following error when I try to open my Content.mgcb file through the Solution explorer in Visual Studio.

"The operation could not be completed.  The parameter is incorrect."

My students have been experiencing the same thing with MonoGame 3.7.1 on their home PC:s.

I get the same error when installation Visual Studio Community 2019 version 16.6.0 Preview. It works in Visual Studio 2017 Community though.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.0.1082
- MonoGame 3.7.1

#### What operating system are you using:
- Windows 10

#### What MonoGame platform are you using:

- WindowsDx, DesktopGL

**Comment by lostallmymoney** [comment] 2020-03-20 06:01
Same here VS2019 last version of monogame.

**Comment by harry-cpp** [comment] 2020-03-20 19:15
I have VS 2019, and MG 3.7.1 installed on my Windows device and I can't seem to reproduce this issue.

**Comment by Jjagg** [comment] 2020-03-20 19:56
I don't see how this could be a VS issue, it simply delegates opening the file to the default editor for the extension. I don't understand how you could get different behavior in different VS versions.

**Comment by simoneddeland** [comment] 2020-03-20 20:18
> I have VS 2019, and MG 3.7.1 installed on my Windows device and I can't seem to reproduce this issue.

Have you updated to the latest version of VS 2019? I didn't have this problem before updating to VS 2019 version 16.5.0, it worked fine on 16.4.something.

> I don't see how this could be a VS issue, it simply delegates opening the file to the default editor for the extension. I don't understand how you could get different behavior in different VS versions.

Could there be something wrong in the templates in the VS2019MonoGame.zip file found in this post then? https://github.com/MonoGame/MonoGame/issues/6695#issuecomment-557758216
Me and all my students are using these templates since the installer doesn't add templates for VS 2019.

**Comment by simoneddeland** [comment] 2020-03-24 08:17
@harry-cpp @Jjagg After finding someone having the same issue in a post on reddit today, https://www.reddit.com/r/monogame/comments/fns7i2/im_experiencing_a_really_frustrating_issue/ , also found a way to get the Pipeline Tool to open properly in Visual Studio 2019 version 16.5.0. By manually adding the Pipeline.exe file when using "Open With" in Visual Studio the Pipeline tool opens as expected. Maybe this can help narrow the problem down. Is the default link to the "MonoGame Pipeline Tool" added by the installer perhaps?

**Comment by slanger** [comment] 2020-04-04 16:11
I'm experiencing this problem as well, after updating Visual Studio 2019 from version 16.4 (I think) to 16.5.1 (MonoGame version = 3.7.1). A work-around I found from an old MonoGame tutorial video (https://youtu.be/q-XlaN-hOg8?t=275, set at the relevant time in the video) is, inside Visual Studio, right-click the Content.mgcb file, click "Open Containing Folder", then open the Content.mgcb file from inside File Explorer, which should open the file in the MonoGame Pipeline Tool.

**Comment by Jjagg** [comment] 2020-04-04 22:16
Huh, so VS does not use the default tool for the extension 🤔 That seems like a VS bug then...

**Comment by Jjagg** [comment] 2020-04-04 22:22
I'm gonna go ahead and close this since there's two workarounds and it's not a bug on our side. Feel free to reopen if you disagree :)

Thanks for reporting @simoneddeland and @slanger!

**Closed by Jjagg** 2020-04-04 22:22 UTC
