### ISSUE TITLE
Can't install templates.

### ISSUE THREAD

**Issue by SamuelKlit** [MonoGame/MonoGame#4838] opened 2016-05-11 18:32 UTC
I can't install templates when i'm using the installer. I suspect it is because my documents library folder is on D: on C:. I tried to copy the template from another computer but that didn't seem to work.  Let me know if there is any workarounds.

**Comment by KonajuGames** [comment] 2016-05-11 23:00
Moving the Documents folder is the cause of do many issues, especially when it is moved after Visual Studio is installed. Visual Studio's registry entries will likely still be pointing to the old location, which is what we use.  We will have to try to bullet proof this some more.

**Comment by MasterQuestMaster** [comment] 2016-05-13 10:34
Oh, now I feel dumb for creating an issue about the same problem.
I think that maybe installing the templates manually would work.

**Comment by SamuelKlit** [comment] 2016-05-13 11:14
I tried to copy the templates from another computer which installed Monogame correctly. But that didn't seem to work.

**Comment by jmclem** [comment] 2016-11-29 21:47
Just had following problem : installing Monogame for Visual Studio 15 on Win 7, all templates were greyed out. It turns it is probably because my account is a Standard User account, not administrator.
I logged in into an admin account, all went ok.
As a work around, I copied from hand the templates from the admin's documents to my user's documents, worked.

**Comment by KonajuGames** [comment] 2016-11-30 02:02
> It turns it is probably because my account is a Standard User account, not administrator.
I logged in into an admin account, all went ok.

Yes, this is a known problem.  We need administrator privileges to install MonoGame into Program Files, but this means authenticating as an admin user.  The installer then runs under that admin user, so when we access the registry to find the location of the user's Visual Studio project templates folder, it is reading the registry for the admin user, not the standard user.

I'm thinking we might need to add a small template installer tool to the distribution that the standard user can run separately after the main install and it will run as that standard user, thus finding that user's Visual Studio project templates folder.

**Comment by Jjagg** [comment] 2018-12-09 01:52
Installer doesn't use the registry keys anymore because it caused issues with VS2017. Closing in favor of #3808.

**Closed by Jjagg** 2018-12-09 01:52 UTC
