### ISSUE TITLE
Pipeline Filter View slows down build process

### ISSUE THREAD

**Issue by tomspilman** [MonoGame/MonoGame#5233] opened 2016-10-21 01:17 UTC
I have a content project that takes 6 seconds to build in the regular output view.

When i switch to the filter view the same build takes a crazy **2m 17 seconds**.  Nothing else has changed... the slowdown is consistent when the filter view is enabled.

I suspect how the filter view works is very very slow.... and it happens to be blocking the MGCB.exe output stream keeping it from progressing as fast as it could.

**Comment by tomspilman** [comment] 2016-10-21 01:17
@cra0zy

**Comment by james0x0A** [comment] 2016-10-21 01:36
I did some profiling on this issue a couple weeks ago and found that it spends a lot of time measuring and remeasuring the height of each element in the view whenever something is added. It actually starts out at a reasonable speed and grinds to a halt after a hundred items or so.  I wasn't able to track it to anything more specific because of deadlines, but that's the gist of it.

**Comment by nkast** [comment] 2016-10-21 06:38
How about this @cra0zy ? #5234 
I am not sure if I have to use Eto.Threading or something else.

**Comment by tomspilman** [comment] 2016-10-22 05:02
Reopening this.

First @nkast fix worked in that build itself finishes just as fast in either the plain or filtered views.

Still while the build finished...  the filtered view still takes up to 2 minutes to complete updates.  You can even see it getting slower as the more and more items are added to it.

I did a test making some obvious optimizations to how the filter view works, i even disabled the auto scroll, and i got ZERO improvement in performance.

The underlying `Xwt.TreeStore` control is horribly slow and completely cripples the filter view feature from being useful as an output window alternative.

@cra0zy - I see three paths:

 1. Replace the Xwt control with the Eto one hoping it is faster.
 2. Try to fix the Xwt control... which might not be possible.
 3. Implement our own fast custom control using Eto for rendering.

**Comment by tomspilman** [comment] 2016-10-22 05:09
@cra0zy @nkast  - Maybe we should return to having the plain output view as the default until the filter view is fixed.  It currently just makes MonoGame and the pipeline look bad.

**Comment by KonajuGames** [comment] 2016-10-22 05:31
Does Eto support a virtual treeview?  I used these back in Delphi days (90's) to populate treeviews and listviews with large numbers of items.  The control uses events to ask the application for the information to display on visible items only so less information needs to be copied into the nodes in the control.

**Comment by nkast** [comment] 2016-10-22 06:46
The control is still populated with items even if it's hidden. 
For now can we try to add all assets in the begging? Kind of like download managers present ongoing Tasks (started, paused, finished, etc).  If the control supports disabling Updates/Resizing similar to  WinForms `SuspendLayout()`/`ResumeLayout()` that would be an improvement.

The way I image the Filter View is a panel at the top with info like 
Build Time: | Ellapse Time: | Total Assets: (total) | Build: ?/(total) (%) 
[Succeded: ?] | [Skipped: ?] | [Errors: ?] | [Warning: 0]
and bellow a panel with all assets and their statuses.

For that we need a form of Binding, Eto supports MVVM, Xwt was temporary, right?
Eto was slow in adding new items, perhaps Eto's TreeView was slow in adding new items @cra0zy but fast in updating icons, childer, etc and works better with this approach.

**Comment by cra0zy** [comment] 2016-10-22 12:59
> Does Eto support a virtual treeview?

It does not.

> Implement our own fast custom control using Eto for rendering.

I think this would be a good solution.

> For that we need a form of Binding, Eto supports MVVM, 

If you are referring to https://github.com/picoe/Eto/wiki/Custom-Platform-Controls than yes.

> Xwt was temporary, right?

Xwt was temporary, but it seems both Eto and Xwt have horrible treeviews :(

**Comment by cra0zy** [comment] 2016-10-22 13:05
I think the best solution is to make BuildOutput control per platform so it can be optimized properly.

@nkast Wanna work with me on this one, the idea is to use https://github.com/picoe/Eto/wiki/Custom-Platform-Controls to make a skeleton for a control, and than I will work on implementing it for Gtk and you can work on implementing it for WPF?

**Comment by tomspilman** [comment] 2016-10-22 13:15
> I think the best solution is to make BuildOutput control per platform so it can be optimized properly.

Why is this better than our own custom control?

A custom control could be developed once and work the same across all platforms.

Implementing two different controls would mean double the work for double the bugs.

**Comment by cra0zy** [comment] 2016-10-22 13:23
> Why is this better than our own custom control?
> 
> A custom control could be developed once and work the same across all platforms.
> 
> Implementing two different controls would mean double the work for double the bugs.

Oh you meant to do the same as what I did for PropertyGrid... yea that could work as well... I'll think for a few minutes about this.

**Comment by cra0zy** [comment] 2016-10-22 13:24
On a side note I need #5214 merged since it fixes getting drawn text height.

**Comment by tomspilman** [comment] 2016-10-22 13:27
> Oh you meant to do the same as what I did for PropertyGrid

Yeah sort of.

I mean literally rendering a custom control.  Like `DrawText(label); DrawIcon(icon); DrawExpander(pos);`.

This way we work from our own data set in whatever efficient structure we want to keep it.  No need to insert it into some other control object's data structure.

There are no other windows, objects, controls, etc involved in rendering the filter view.  Just our own draw commands using Eto as an abstraction.

**Comment by nkast** [comment] 2016-10-22 13:34
Yes, the problem is that those two controls were inefficient, not that Eto is inherently slow (I hope not).
 
>Does Eto support a virtual treeview?
>>For that we need a form of Binding, Eto supports MVVM,
> If you are referring to https://github.com/picoe/Eto/wiki/Custom-Platform-Controls than yes.
No, I was talking about that one. https://github.com/picoe/Eto/wiki/Data-Binding

**Comment by tomspilman** [comment] 2016-10-22 13:40
> Eto's TreeView 

We stopped using this because it lack features for multi-select correct?

There is no reason we couldn't use it for the filter view... which doesn't need that feature...  if it is faster than Xwt.  We should give this a try.

Also if data binding is faster than manually adding items to the tree view we should try that as well.

**Comment by cra0zy** [comment] 2016-10-22 13:50
> There is no reason we couldn't use it for the filter view... which doesn't need that feature... if it is faster than Xwt. We should give this a try.

It's not faster, it's the opposite, slower :o

**Comment by cra0zy** [comment] 2016-10-22 13:58
So I thought about this a bit, and custom drawing the filter view can make it look much nicer than a treeview ever could. What's more we will be able to do some more custom stuff like coloring the error text for example.

PS. Gtk filterview can process adding 102 items in less than a half of a second.

**Comment by tomspilman** [comment] 2016-10-22 14:03
> So I thought about this a bit

That is true...  we could have a real custom view there that is specifically designed for our needs.

> Gtk filterview can process adding 102 items in less than a half of a second.

Then this issue is simply with the WPF implementation of treeview in Xwt/Eto?

**Comment by cra0zy** [comment] 2016-10-22 14:06
> Then this issue is simply with the WPF implementation of treeview in Xwt/Eto?

That's an issue with WPF treeview in general, it's much slower than the Gtk counterpart.

**Comment by tomspilman** [comment] 2016-10-22 14:18
> That's an issue with WPF treeview in general, it's much slower than the Gtk counterpart. 

Maybe we should see if the regular optimizations on WPF tree views help us:

https://blogs.msdn.microsoft.com/permanenttan/2009/11/20/wpf-treeview-memory-consumption-and-performance/

More important for the project view once we switch back to Eto for that.

**Comment by cra0zy** [comment] 2016-10-22 14:21
Virtualization only helps with treeview once items have been loaded, it's not helpful for something like filterview which requires loading and displaying them over and over again.

**Comment by tomspilman** [comment] 2016-10-22 14:29
> Virtualization only helps with treeview once items have been loaded,

That isn't accurate with what I've done with control virtualization in the dozens of Windows GUI apps I've built over the years.  However I can't say I've tried this specific optimization on WPF tree views, so who knows.

My guess is that the issues Eto and Xwt have with tree views are all solvable, but no one has had the time to dig in and fix it.  Which sucks, but that is how open source is.

**Comment by nkast** [comment] 2016-10-22 21:14
>Then this issue is simply with the WPF implementation of treeview in Xwt/Eto?
>>That's an issue with WPF treeview in general

That's racist!

**Comment by nkast** [comment] 2016-10-22 21:17
So, is it that any control under WPF/Eto will be slow? Or the WPF in general?

**Comment by james0x0A** [comment] 2016-10-22 22:18
Seems like Eto WPF  extends the WPF TreeView .  Is it possible that, on Windows, the native control could be wrapped in a VirtualizingStackPanel and use the native TreeView facility for virtualization?

**Comment by nkast** [comment] 2016-10-23 11:10
@tomspilman Can you test https://github.com/MonoGame/MonoGame/pull/5239 with your project?
BTW , take a look at https://github.com/MonoGame/MonoGame/pull/4450 if you have the time. :pray:

@cra0zy there is a bug where the treeview is cropped during the build. Is that a known issue with Xwt?

**Comment by cra0zy** [comment] 2016-10-23 11:19
> @cra0zy there is a bug where the treeview is cropped during the build. Is that a known issue with Xwt?

cropped? how so?

**Comment by nkast** [comment] 2016-10-23 11:34
> cropped? how so?
You can see it at the screenshots of #5239. It's like the control is smaller by ~100 pixels. It get's resized to the correct width once build is finished.

**Comment by cra0zy** [comment] 2016-10-23 17:04
New filterview is on the left:

![newfilter](https://cloud.githubusercontent.com/assets/6773302/19627955/6328d7f4-9953-11e6-8445-8025d6987228.png)

**Closed** 2016-10-30 21:33 UTC
Labels: ContentPipeline, Help Wanted
