### ISSUE TITLE
PipelineTool - Incorrect display (Dev branch 3.7)

### ISSUE THREAD

**Issue by MarcVador** [MonoGame/MonoGame#5697] opened 2017-05-05 09:45 UTC
Hi
I have noticed since the build 313 that the tools displays incorrectly folders (Windows7 x64, I have no other OS to test with right now):
- The + has vanished when a folder can be expanded.
- The content of 2 folders at the same level cannot be expanded
- Files in an expanded folder are not always indented in the folder (same vertical line as the containing folder) (1st screenshot: basicscene should be indented to appear in the "Scene" folder)
- Folders too (for ex, 3rd screenshot, the folder space is in "modelsB")
- The scrollbar on the right cannot be used (2nd screenshot)

![capture bad indentation](https://cloud.githubusercontent.com/assets/19704413/25740584/738f9764-3187-11e7-8b11-3dab36e9086f.JPG)
![capture scrollbar](https://cloud.githubusercontent.com/assets/19704413/25740585/739595b0-3187-11e7-8077-dfeb1c1b9cfa.JPG)
![capture folder](https://cloud.githubusercontent.com/assets/19704413/25740586/73968b82-3187-11e7-933d-29ff0e0f2c54.JPG)

**Comment by tomspilman** [comment] 2017-05-05 14:47
Thanks for reporting this @MarcVador .

I checked the latest Pipeline tool on Windows here and I get the same issue.

In fact on my machine all the drop down menus open on the top of my primary display.

![image](https://cloud.githubusercontent.com/assets/103522/25750619/df05387e-3177-11e7-8c10-d0d0e7a0fda4.png)

@cra0zy - This all has to be fixed ASAP.

**Comment by cra0zy** [comment] 2017-05-05 16:26
I actually can't reproduce any of the above issues on Windows 10. @tomspilman Did you test on Windows 7 as well?

> In fact on my machine all the drop down menus open on the top of my primary display

I kind of forgot about the menubar bug... I noticed it a couple months ago, had it fixed in #5489, but due to Eto Forms dependency update not being merged I kind of stopped updating that PR and forgot about it... #5700 fixes it now.

**Comment by tomspilman** [comment] 2017-05-05 16:28
> I actually can't reproduce any of the above issues on Windows 10

@cra0zy - I'm running Windows 10 here and it all occurs for me.

Maybe this is related to multiple monitors?  This wasn't a bug a few weeks ago... so it is something changed recently.

**Comment by cra0zy** [comment] 2017-05-05 16:30
Just to be clear, when I said issues above I meant the ProjectView stuff, the menubar thing really is a bug I've noticed a long time ago (and fixed and forgot about it).

**Comment by Jjagg** [comment] 2018-12-10 13:00
@cra0zy I can't replicate any of these. I guess they're fixed? I'm on Windows 10, but since it all uses WPF there shouldn't be any issues specific to Windows version at least on our side.

**Comment by cra0zy** [comment] 2018-12-10 17:11
Probably.

**Closed by cra0zy** 2018-12-10 17:11 UTC
Labels: Pipeline Tool
