### ISSUE TITLE
Installer does not detect VS if not in default location

### ISSUE THREAD

**Issue by WardBenjamin** [MonoGame/MonoGame#3808] opened 2015-05-02 13:10 UTC
Hey all,

Just wanted to report that I cannot install the VS templates with the new installer, since in my case VS is not located in the default location, as it is installed on my SSD, along with a few other things and the OS, but not the default Program Files and Documents folders. 

![capture](https://cloud.githubusercontent.com/assets/4739008/7441199/12d649dc-f0ab-11e4-835b-20703ef86a1b.PNG)

Is there somewhere that I could download these seperately?

**Comment by WardBenjamin** [comment] 2015-05-02 13:15
I just figured out that I can build them through Protobuild, and that fixes my specific problem, but the  above issue is still relevant to others in the same situation.

**Comment by KonajuGames** [comment] 2015-05-02 13:18
We don't check for the install location to see if a particular version of VS is installed, and there is no hard-coded install paths used.  For VS versions, we check for the existence of the (C# project templates)[https://github.com/mono/MonoGame/blob/develop/Installers/Windows/MonoGame.nsi#L253] folder in your Documents folder.  Do you have that folder?

**Comment by WardBenjamin** [comment] 2015-05-02 13:20
I do have that folder, but it was empty, which I think was the issue, since you are checking for the existence of files in that folder.

**Comment by Shqrdx** [comment] 2015-05-02 13:22
The Visual studio installs all things into this folder. It always create folder like ..\Documents\Visual Studio 2013\Templates\ProjectTemplates\Visual C#\. Thats strange that your VS does not do that.

**Comment by WardBenjamin** [comment] 2015-05-02 13:25
@Shqrdx I do have that folder, but there is nothing in it, as I said in my comment above. I think you misunderstood :)

**Comment by Shqrdx** [comment] 2015-05-02 13:25
Visual Studio 2013\Templates\ProjectTemplates\Visual C# it must be in Documents folder

**Comment by WardBenjamin** [comment] 2015-05-02 13:27
Again, I think you misunderstood. In actuality, the line of code that checks for the folder actually only checks for files in that folder:

``` IfFileExists `$DOCUMENTS\Visual Studio 2013\Templates\ProjectTemplates\Visual C#\*.*` InstallTemplates CannotInstallTemplates```

This line checks for any files inside of the VS2013 C# Templates folder, which I do have but was not filled with anything.

**Comment by Shqrdx** [comment] 2015-05-02 13:31
I maded this change and I think it is works correctly. Something wrong with your system. Try reinstall VS.

**Comment by Shqrdx** [comment] 2015-05-02 13:33
IfFileExists in this description checks for folder not for files inside it.

**Comment by WardBenjamin** [comment] 2015-05-02 13:36
Alright, I will try reinstalling VS when I get back home today. Thanks for
the help.

On Sat, May 2, 2015 at 9:34 AM, Yuri Roubinsky <notifications@github.com>
wrote:

> IfFileExists in this description checks for folder not for files inside it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mono/MonoGame/issues/3808#issuecomment-98357566>.
>



-- 
Benjamin Ward

**Comment by KonajuGames** [comment] 2015-05-02 13:49
That folder exists on mine, and by default it is indeed empty, but the MonoGame installer has added a MonoGame subfolder and installed the templates.  I installed latest dev build of MonoGame tonight on a Windows 10 system with freshly installed VS2015 Community and the templates were installed.

I'm not sure what is happening in your case.  Perhaps a reinstall will fix it?  Hard to say for sure what could be causing it.

**Comment by Shqrdx** [comment] 2015-05-02 13:57
I suppose he install VS to separated SDD instead to default location. Than his Document folder could not be equal to VS directory for projects. Even if these restrictions are not exist he was unable to install it correctly because they are equal to actual install locations.

**Comment by WardBenjamin** [comment] 2015-05-02 22:39
Hmm. It seems like reinstall fixed but this is limited to the default location now. It seems like since there is some stuff that is put in `Program Files (x86)` for each template, that even if they are installed in the correct `Documents` folder they fail to work.

**Comment by KonajuGames** [comment] 2015-05-02 23:18
We never hard-code any paths.  We ask the system for the locations of the
special folders, such as Documents, MSBuildDir, etc.​

**Comment by WardBenjamin** [comment] 2015-06-02 20:03
I don't know what the issue is then. I'm closing since I don't really need this, but it's still an issue that should be considered in the future.

**Comment by WardBenjamin** [comment] 2015-09-18 02:14
Welp. I found what as acutally the issue for this. It seems that Monogame installed all project templates to the root user's Documents folder for me, rather than the user that I'm actually using. I don't really have an explaination for this, but I believe that it could be because the installation executable is run as an administrator. Copying over the files to my user's Documents folder seems to make VS find them.

**Comment by InfiniteProductions** [comment] 2016-03-28 08:17
Why not letting the use choose ? He/She know what VS is installed on his/her system (I hope) + MS create a mess with registry keys, names, paths which may be a value or another depending on which version of VS is installed. 

Sometimes, trying to be too smart (like Microsoft) is not smart at all :/.

**Comment by tomspilman** [comment] 2016-03-28 11:12
> Why not letting the use choose ?

Because we can identify the correct path 100% of the time if we do it correctly. See https://github.com/mono/MonoGame/pull/4616.

@KonajuGames @WardBenjamin - Didn't https://github.com/mono/MonoGame/pull/4616 fix this issue?  Can we close this one?

**Comment by LeeC2202** [comment] 2018-12-23 15:03
The problem is caused by Microsoft being idiots to be quite honest.

Monogame installs the templates to [UserName]\My Documents\Visual Studio 2015\Templates\ProjectTemplates\Visual C#

Which is where you would expect them to go.

Visual Studio 2015 expects to find them in [UserName]\Documents\Visual Studio 2015\Templates\ProjectTemplates\Visual C#

Those are not the same location.

If I type %userprofile% into windows explorer, I can see both of those locations in my profile. So I now have a single application on my system (i.e. Visual Studio) that has decided to create it's own subdirectory tree in my profile and all probably because some MS Halfwit chose "Documents" instead of "My Documents".

I think MS Developers are losing the plot tbh and it's sad to see the consequences of that, cause so many problems for other developers, who know what they're doing.

And just for reference, this was from a Monogame install today (23/12/2018), into VS2015.

**Comment by Halofreak1990** [comment] 2019-01-07 12:42
I've never seen "My Documents" in any Windows version after XP. From Windows Vista onwards, the user directories got moved and renamed, and XP-style names (like "Documents and Settings") got changed into symlinks. What version of Windows are you using, and did you happen to upgrade this machine from XP to a later version of Windows at some point in time?

The default location for user documents is C:\Users\[UserName]\Documents, and any locale-specific folder names are handled in the UI.

**Comment by LeeC2202** [comment] 2019-01-07 15:00
"The default location for user documents is C:\Users[UserName]\Documents, and any locale-specific folder names are handled in the UI."

My experience says otherwise.

If you've never seen it before, then it's your lucky day because not only do you get to see one... you get to see two.

This is a picture of my server running Windows 7 Pro. There is no Documents folder at all, it's called My Documents. This PC has only ever had Windows 7 installed and has never had any folders moved.
[img]https://imgur.com/qMqXN7s.jpg[/img]

And here's an image grabbed from a fresh Windows 7 Home Premium installed into VMWare
[img]https://imgur.com/4Soh9Ut.jpg[/img]

My main dev machine has both and that is only because Microsoft created C:\Documents when I installed Visual Studio 2015

**Comment by LeeC2202** [comment] 2019-01-07 15:01
"The default location for user documents is C:\Users[UserName]\Documents, and any locale-specific folder names are handled in the UI."

My experience says otherwise.

If you've never seen it before, then it's your lucky day because not only do you get to see one... you get to see two.

This is a picture of my server running Windows 7 Pro. There is no Documents folder at all, it's called My Documents. This PC has only ever had Windows 7 installed and has never had any folders moved.
https://imgur.com/qMqXN7s.jpg

And here's an image grabbed from a fresh Windows 7 Home Premium installed into VMWare
https://imgur.com/4Soh9Ut.jpg

My main dev machine has both and that is only because Microsoft created C:\Documents when I installed Visual Studio 2015

**Comment by LeeC2202** [comment] 2019-01-07 15:03
Sorry, that should read "Microsoft created C:\Users\Lee\Documents"

I can't edit the post thanks to gitHub being asshats about old Firefox versions and not allowing IE in any shape or form.

**Comment by harry-cpp** [comment] 2020-03-24 22:40
This is no longer an issue with 3.8.

**Closed by harry-cpp** 2020-03-24 22:40 UTC
Labels: Installer
