### ISSUE TITLE
Sound Effects only play intermittently on Android (MG 3.6)

### ISSUE THREAD

**Issue by HypedHamster** [MonoGame/MonoGame#5418] opened 2017-01-16 08:06 UTC
This has been an Android issue since MG3.5 (all was good in 3.4). Sound effects usually play fine the first time they play and then hardly ever work after that. Clicking a button that repeatedly plays a sound effect will eventually crash the device too, with the following error:

 AL.Source (SourceId, ALSource3f.Position, _pan, 0, 0.1f);
        ALHelper.CheckError("Failed to set source pan.");

Manually setting the pan for each sound effect stops this crash but the sound effect still only plays occasionally.

**Comment by jakepoz** [comment] 2017-01-30 22:55
@HypedHamster does the roponator fix work for you? 

I have a similar bug report here: https://github.com/MonoGame/MonoGame/issues/5387

**Comment by HypedHamster** [comment] 2017-01-31 05:05
I'll make a blank project and do some tests in next couple of days.

**Comment by Jjagg** [comment] 2018-12-10 11:14
Closing as duplicate of #5387.

**Closed by Jjagg** 2018-12-10 11:14 UTC
