### ISSUE TITLE
Missing XINput.dll on clean machine

### ISSUE THREAD

**Issue by theZMan** [MonoGame/MonoGame#3240] opened 2014-12-08 04:45 UTC
Tom and I installed MonoGame on a totally clean windows installation for the MVA video.

The desktop template doesn't work because any reference to the GamePad API throws this error
"xinput1_3.dll not found". We're not the only one to notice it was mentioned in this article too http://www.codemag.com/Article/1411081

XInput is not a part of the default DirectX install so it doesn't ship with windows. You need to run the DirectX web installer to fix it http://www.microsoft.com/en-us/download/details.aspx?id=35 (or install XNA which is why most of us never see the error). We did note that the windows store template does not suffer from this issue suggesting that the GamePad API is not wrapping XInput on windows store apps.

Solution: The MonoGame installer should use DirectX setup to make sure that XInput1_3.dll (and any other optional DX components) are installed. 

Or maybe SharpDX needs to link to a later version? Chucks block talks about a 1_4 and a 9_1 version on windows 8 http://blogs.msdn.com/b/chuckw/archive/2012/04/26/xinput-and-windows-8-consumer-preview.aspx

**Comment by xoofx** [comment] 2015-01-16 23:43
Sorry, completely forgot about this post. 

In Paradox, we are redistributing a minimal set of DirectX June 2010 runtime through the installer, but we haven't work for the client side redistribution (a client developing a game that would like to redistribute it as well).

I don't know the details about the difference between the API 9.1.0 and 1.3/1.4, and I agree that this is currently quite annoying that we can't easily target these APIs from a all-in-one assembly. I don't know if we can have an hybrid system where we could support 1.3 or 9.1.0 if it is installed, and 1.4 on Win8 assemblies. 

Unfortunately, the Windows 8 AppStore restrictions with DllImport is super annoying and forbid to achieve an ideal scenario where we could target all system DLL from the same SharpDX assembly (not allowing to LoadLibrary / GetProcAddress for system dlls but only allowing static DllImport and only allowing authorized imports, so if there are un-authorized imports - that you don't use, the App Certification will fail....etc.)

Anyway, feel free to log an issue on SharpDX though I really don't have any time to work on this for now... but if someone is interested to dig into this, he will be welcome!

**Comment by polsys** [comment] 2015-01-17 11:06
I investigated the DirectX Runtime installer option a bit...

The [runtime installer files](http://www.microsoft.com/en-us/download/details.aspx?id=8109) from Microsoft contain all the components since 2005. Of those packages, these files are required to install XInput 1.3 (about half a megabyte compressed):
```
dxsetup.exe
dsetup.dll
dsetup32.dll
dxupdate.cab
apr2007_xinput_x64.cab
apr2007_xinput_x86.cab
```

The MonoGame installer would extract the files to a temporary directory and run
```
dxsetup.exe /silent
```

On my XInput-less laptop the install was basically instant and I could confirm the desktop template working after it.

Even with this I think there needs to be some mention of the XInput dependency so that developers know to add XInput to their game installers.

**Comment by aredfox** [comment] 2015-06-29 09:12
it seems this issue is still happening? I can correct the issue myself, but it would be nice if this would be solved somehow, without having to manually correct it each time?

**Comment by KonajuGames** [comment] 2015-06-29 09:13
When we update to latest SharpDX the problem goes away as it uses XInput
that comes installed.​

**Comment by xoofx** [comment] 2015-06-29 12:45
FYI, SharpDX latest 3.0.0 (alpha) is wrapping into the same assemblies XAudio and XInput for both version Windows 8 + DirectXJune2010. So if you are on Windows 8.x+, you should not need to install XAudio, otherwise you still need to install from DirectX June2010 Runtimes as usual.

**Comment by allansson** [comment] 2015-07-29 18:42
I can confirm that the same problem exists on a clean Windows 10 install, not that it should surprise anybody.

**Comment by KonajuGames** [comment] 2015-07-30 01:17
> I can confirm that the same problem exists on a clean Windows 10 install, not that it should surprise anybody.

Was that after installing the DirectX runtime?  Any application that uses DirectX should always install the DirectX runtime first, even if that runtime does nothing.

**Comment by allansson** [comment] 2015-07-30 10:04
> Was that after installing the DirectX runtime? Any application that uses DirectX should always install the DirectX runtime first, even if that runtime does nothing.

No, it was before installing the DirectX runtime. Installing it worked like a charm. I just stumbled upon this ticket while looking for a solution for the same issue after installing MonoGame on my clean install of Windows 10. And since nobody had mentioned Windows 10, I thought I would just say something for the record.

**Comment by KakCAT** [comment] 2015-08-01 10:53
Hi,

what are the implications of this issue when publishing to the Windows 10 store?

**Comment by mrhelmut** [comment] 2015-08-02 12:07
Hey,
not sure if it is related, but I am trying to deploy a pre-built Desktop game on a clean Win7 32bit install and can not get XInput gamepads to work. While 360 controllers are perfectly installed and working within the system on vanilla drivers, the game doesn't recognize them.
I've tried to install the DX runtime, in case ShardDX was looking for XInput 1.3, but that is not working either.
Any reason this is failing?

**Comment by MichaelDePiazzi** [comment] 2016-12-13 04:42
Some new information on this issue:

**XAudio2_7.dll** also needs to be installed for sound to work. Currently if it's not installed, MonoGame silently catches the exception and disables sound. So in addition to the files @polysys already mentioned, the following cabs need to be included:
```
Jun2010_XAudio_x64.cab
Jun2010_XAudio_x86.cab
```
I've confirmed that this is required on a fresh installation of Windows 7 SP1.

Also worth mentioning - MonoGame no longer crashes if xinput1_3.dll is not installed. Since PR #3821, the exception is now silently caught (effectively disabling gamepad support).

**Comment by tomspilman** [comment] 2016-12-13 06:38
@MichaelDePiazzi - That is great info... we need to get this into the MonoGame docs.  I think specifically we need a "Windows DirectX" section here:

http://www.monogame.rocks/documentation/?page=Platform_Specific_Notes

If someone gets a chance please submit a PR.

**Comment by MichaelDePiazzi** [comment] 2016-12-13 06:50
@tomspilman - I remember @mrhelmut started work on this kind of documentation earlier this year in PR #4430, but he mentioned it was not ready to be merged yet... It would be good if this could be merged first so as not to create any potential conflicts / double-up of work...

@mrhelmut - What is the status of your PR #4430? Was there still more you wanted to add to it, or can it be merged as it is?

**Comment by mrhelmut** [comment] 2016-12-13 10:46
It's unfinished and since the SDL2 shift in DesktopGL, there's some change to do. Thanks for the reminder and the info.
I'm still up to finish this! I'll try to get back at it soon. I'd like to describe how to package any type of desktop games (inc. using MonoKickstart) and manage dependencies.
I won't go through making an installer, I believe this is a thing of the past regarding how games are published nowadays.

**Comment by MichaelDePiazzi** [comment] 2016-12-14 00:34
@mrhelmut Cool, sounds good! I agree about the installer - they are a bit of a thing of the past (and are a total pain). itch is even dropping support for them in it's app, and is currently building it's own common redistributable installers (similar to Steam's). See: https://itch.io/docs/itch/integrating/manifest.html#prerequisites-windows

> (Note that on a clean machine, the good version of XAudio is also missing, games start without SoundEffect support, but MediaPlayer --which uses Media Foundation-- works.)

That's actually why I revived this thread - I found the same thing, so wanted to mention that it wasn't just XInput that was required :)

**Comment by jamesford42** [comment] 2017-05-04 01:13
Duplicate/related issue:
https://github.com/MonoGame/MonoGame/issues/4934

**Comment by mrhelmut** [comment] 2017-05-04 10:49
D3Dcompiler_43.dll si required by the Pipeline to build shaders, but is not required by games during runtime (unless your game builds shaders at runtime).

It's mostly a developer problem and not an end-user one. For the matter, it is stated on the download page that the DirectX June 2010 SDK is required in order to develop with MonoGame.

**Comment by Jjagg** [comment] 2017-07-09 12:09
Similar to #5777 this willl likely be fixed if we upgrade SharpDX, because newer versions check for multiple versions of XInput. From [SharpDX 3.0 changelog](https://github.com/sharpdx/SharpDX/releases/tag/v3.0.0):

> XInput and XAudio are now providing a backward compatible interface between the various versions. For Desktop, it means that the runtime will try to detect the correct versions for XInput (9.10, 1.3, 1.4) or XAudio (2.7 or 2.8). For Store Apps, the latest one will be used.

I'm not sure what version(s) ships with Win10 though, because MS haven't updated the relevant [MSDN page](https://msdn.microsoft.com/en-us/library/windows/desktop/hh405051%28v=vs.85%29.aspx)

See #3794 for upgrading SharpDX.

**Comment by Jjagg** [comment] 2018-03-03 16:19
This was resolved by upgrading SharpDX as stated in my previous comment. #5825

**Closed by Jjagg** 2018-03-03 16:19 UTC
Labels: Installer
