### ISSUE TITLE
DesktopGL 3.8.0.1082 IsFixedTimestep

### ISSUE THREAD

**Issue by numberoverzero** [MonoGame/MonoGame#7168] opened 2020-05-28 01:30 UTC
In the following example, why does Update still get called approximately 60 times per second?  I expected `IsFixedTimestep=false` to uncap my framerate, but mostly the values jitter around 60fps.  So then I expected changing `TargetElapsedTime` to push me towards the target value, but that doesn't seem to have an effect.  Why doesn't the Game run as fast as possible when `IsFixedTimestep` is false?

```csharp
// MonoGame 3.8.0.1082
// DesktopGL
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
using System;
namespace Sample
{
    public class Sample : Game
    {
        static void Main() { using (var game = new Sample()) game.Run(); }
        int updates = 0; int draws = 0; const int stop = 50;
        public Sample() : base()
        {
            IsFixedTimeStep = false;
            InactiveSleepTime = TimeSpan.Zero; //[0]
            TargetElapsedTime = new TimeSpan(0, 0, 0, 0, 1); //[1]
            
            var gdm = new GraphicsDeviceManager(this);
            gdm.PreparingDeviceSettings += (_, e) =>
            {
                Console.WriteLine("prepared");
                e.GraphicsDeviceInformation.PresentationParameters.PresentationInterval = PresentInterval.Immediate;
            };
            gdm.SynchronizeWithVerticalRetrace = false; gdm.ApplyChanges(); //[2]
        }

        protected override void Update(GameTime gameTime) => Debug(gameTime, true); //[3]
        protected override void Draw(GameTime gameTime) => Debug(gameTime, false); //[3]

        void Debug(GameTime gameTime, bool u)
        {
            if (u) updates++;
            else draws++;
            var ifps = 1000.0 / gameTime.ElapsedGameTime.TotalMilliseconds; //[4]
            Console.WriteLine($"{(u ? 'U' : 'D')} {ifps:00.000}");
            if (updates >= stop && draws >= stop)
            {
                Console.WriteLine($"{updates} updates, {draws} draws");
                Exit();
            }
        }
    }
}
```

Notes: 
**[0-2]** no change for any permutation of commenting out these lines.
**[3]** no change when adding a call to the base Update/Draw methods
**[4]** instantaneous fps is good enough for a quick test

I notice `Update` is called more often with `IsFixedTimestep=true` and a small value for `TargetElapsedTime` but I don't want to force the system towards a target framerate (I just want to not cap it at 60 when possible).

I was debugging a SpriteBatch stuttering issue and on the way through [this thread](https://community.monogame.net/t/solved-random-stuttering-is-giving-me-a-headache/8484/11), #4202, #4207, and [this comment](https://community.monogame.net/t/solved-jittery-choppy-frame-movement-for-2d-game/11888/17) when I decided to get a baseline fps count for an empty project, and that's the above code.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.0.1082

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:
- DesktopGL

**Comment by lithiumtoast** [comment] 2020-05-28 01:48
Hello @numberoverzero,

Do you have vsync enabled?

**Comment by lithiumtoast** [comment] 2020-05-28 01:51
My apologies, I see it is disabled via setting `SynchronizeWithVerticalRetrace` to false. It is a common mistake though. Have you tried doing the following:

```
gdm.PreparingDeviceSettings += (sender, e) => 
{                
    e.GraphicsDeviceInformation.PresentationParameters.PresentationInterval = PresentInterval.Immediate;
};
```

**Comment by numberoverzero** [comment] 2020-05-28 03:16
@lithiumtoast I've updated the initial code sample to include your presentation parameter code.

Both the update and draw intervals seem unchanged.
1. I'm still not sure I understand why the draw and update values are exactly equal.
2. I don't understand why I'm not exceeding 60fps.

I expect to see 300+ fps for a blank window when IsFixedTimestep is disabled.  Do you see the same output if you run the example in a DesktopGL project?


Here's my output, including the `PresentInterval` code (adjust `stop` to reduce the length):

```
prepared
U 8
U 55.063
D 55.063
U 484.520
D 484.520
U 2443.793
D 2443.793
U 25.855
D 25.855
U 1706.193
D 1706.193
U 59.720
D 59.720
U 59.975
D 59.975
U 59.894
D 59.894
U 59.715
D 59.715
U 59.756
D 59.756
U 59.776
D 59.776
U 60.097
D 60.097
U 59.833
D 59.833
U 60.114
D 60.114
U 59.849
D 59.849
U 58.461
D 58.461
U 58.785
D 58.785
U 61.421
D 61.421
U 60.214
D 60.214
U 59.925
D 59.925
U 59.756
D 59.756
U 59.871
D 59.871
U 58.621
D 58.621
U 59.520
D 59.520
U 60.712
D 60.712
U 59.888
D 59.888
U 60.401
D 60.401
U 59.638
D 59.638
U 59.091
D 59.091
U 60.240
D 60.240
U 59.765
D 59.765
U 60.003
D 60.003
U 59.683
D 59.683
U 59.961
D 59.961
U 59.767
D 59.767
U 59.773
D 59.773
U 59.687
D 59.687
U 59.849
D 59.849
U 59.948
D 59.948
U 59.807
D 59.807
U 59.738
D 59.738
U 59.768
D 59.768
U 59.790
D 59.790
U 59.763
D 59.763
U 59.583
D 59.583
U 59.966
D 59.966
U 56.282
D 56.282
U 62.568
D 62.568
U 60.571
D 60.571
U 59.557
D 59.557
51 updates, 50 draws
The program '[6728] Sample.exe' has exited with code 0 (0x0).
```

**Comment by lithiumtoast** [comment] 2020-05-28 03:25
> I'm still not sure I understand why the draw and update values are exactly equal.

That's because when using `IsFixedTimeStep` set to `false`, `Update` is called before `Draw` but they are called in sync one after the other (in almost all cases). [They pass along the same timestamp](https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Game.cs#L511).

> I don't understand why I'm not exceeding 60fps.

Yes, and the reason you are getting approximately 60 is why I jumped to the idea of vertical sync. What is your monitor's refresh rate?

I can test later tomorrow.

**Comment by numberoverzero** [comment] 2020-05-28 03:32
ok, thanks.

Changing the monitor's refresh rate does seem to affect the update frequency, which suggests I'm still locked to vsync despite line 24 trying to disable it.

When I change the display setting in windows from 60 to 144 hz, the update frequencies match accordingly.

**Comment by harry-cpp** [comment] 2020-05-28 07:26
Gonna close this as its a question, and not a bug report / feature request.

**Closed by harry-cpp** 2020-05-28 07:26 UTC
