### ISSUE TITLE
[Mac OS X] Subclass of NSApplication

### ISSUE THREAD

**Issue by mgkcortyw** [MonoGame/MonoGame#5990] opened 2017-10-06 19:57 UTC
Hello, guys!

Can we make some subclass of NSApplication and not break MonoGame life cycle?

i.e. i want somethink like this in Xamarin.Mac project:

    [Register("CustomNSApplication")]
    public class CustomNSApplication : NSApplication
    {
        public CustomNSApplication(NSCoder coder) : base(coder)
        {
        }

        public CustomNSApplication(NSObjectFlag t) : base(t)
        {
        }

        public CustomNSApplication(IntPtr handle ) : base(handle)
        {
        }

        public override void SendEvent(NSEvent theEvent)
        {
            base.SendEvent(theEvent);
        }
    }

in Info.plist i write:

	<key>NSPrincipalClass</key>
	<string>CustomNSApplication</string>

in Main.cs i put this:

            NSApplication.Init();
            NSApplication.Main(args);
            using (var p = new NSAutoreleasePool())
            {
                // game initialization and run inside AppDelegate.WillFinishLaunching
                NSApplication.SharedApplication.Delegate = new AppDelegate();
            }

I successfully hit break point in CustomNSApplication constructor. But in this case MonoGame window not showing.

If i put NSApplication.Main(args); after Delegate initialization -> game window are showed and works fine. But in this case CustomNSApplication not created (not hit on breakpoint in constructor).

I need catch all mouse events in MonoGame over app, and for it i need method CustomNSApplication.SendEvent. Because of this https://github.com/MonoGame/MonoGame/issues/5988 issue.

Any solutions?

Thank in advance!

**Comment by harry-cpp** [comment] 2020-03-25 23:27
Not a bug or a feature request so closing.

**Closed by harry-cpp** 2020-03-25 23:27 UTC
Labels: MacOS
