### ISSUE TITLE
Content Pipeline Tool has so many issues

### ISSUE THREAD

**Issue by Linchy** [MonoGame/MonoGame#5146] opened 2016-09-01 17:31 UTC
I'm running into so many problems today with the tool:
1. can't press the DEL key when changing 'reference' paths, it gives an error dialog.
2. I have to reference the exact dll for custom importers, meaning when I change to x86 configuration and make a change it doesn't know about it as it's still looking at bin/debug. Additionally the ref paths don't support ($OutDir) and other macros so I can't automate this??
3. Re-adding a reference doesn't register in the importer dialog, it just says '[missing] tmx importer'. But then I clean and rebuild and it works...
4. I can't have the tool open and build my projects, as VS tries to replace importer dlls but it can't as the tool has them locked.
5. I keep my mgcb file in a seperate project with just that in, because it has so many issues (an attempt to isolate it), but now any changes I make to files don't get registered. Shouldn't it go 'build main project -> build content project -> build mgcb as there were changes' ??
6. It doesn't support x86 importers. Fine. But at least tell me instead of just letting me add the dll as if it is all ok!!
7. [UI] When building things the scrollbar doesn't go to the bottom and I can't see what is currently building.
8. [UI] It highlights some of my shaders as failed to build with red, but actually they did and it is just warnings?!
9. [UI] Always asks me if I want to save before building. Can this not just be automatic? In what instance would I not want to save before building?

So many problems. I'd like to contribute fixes if possible, if you point me in the right direction to get started.

This is with the `Monogame Pipeline Tool v3.5.1.1679`

**Comment by Linchy** [comment] 2016-09-02 14:55
Another two from today:
10. [UI] Can't copy one line from the text output, it just highlights all or none.
11. [UI] The Filter Output categorises some errors incorrectly under the wrong file

**Comment by tomspilman** [comment] 2016-09-02 18:04
Thanks for reporting all this @Linchy .

@cra0zy

**Comment by cra0zy** [comment] 2016-09-02 18:19
Just gonna mention that it would be much easier if this issue was 11 separate issues, because then in each discussion I could focus on discussing about that 1 issue instead of having to use one comment to respond on 11 different things.

That said I'll get to respond to this later today... it's gonna take some time to write everything up.

**Comment by cra0zy** [comment] 2016-09-03 18:20
> can't press the DEL key when changing 'reference' paths, it gives an error dialog.

A bit more clarification please.

> I have to reference the exact dll for custom importers, meaning when I change to x86 configuration and make a change it doesn't know about it as it's still looking at bin/debug. Additionally the ref paths don't support ($OutDir) and other macros so I can't automate this??

You are doing it wrong, the content pipeline stuff should not be connected to your main game assembly in any way and it's output path should be static (you can set it static in the project properties).

> Re-adding a reference doesn't register in the importer dialog, it just says '[missing] tmx importer'. But then I clean and rebuild and it works...

Duplicate of: #5140
#5149 fixes this.

> I can't have the tool open and build my projects, as VS tries to replace importer dlls but it can't as the tool has them locked.

This one is gonna be a bit tricky to fix... 

> I keep my mgcb file in a seperate project with just that in, because it has so many issues (an attempt to isolate it), but now any changes I make to files don't get registered. Shouldn't it go 'build main project -> build content project -> build mgcb as there were changes' ??

I don't get what you are doing, post screenshots please.

> [UI] When building things the scrollbar doesn't go to the bottom and I can't see what is currently building.

#5149 fixes this.

> [UI] Always asks me if I want to save before building. Can this not just be automatic? In what instance would I not want to save before building?

I found this annoying as well... @tomspilman  you ok with making this change?

> [UI] Can't copy one line from the text output, it just highlights all or none.

> It doesn't support x86 importers. Fine. But at least tell me instead of just letting me add the dll as if it is all ok!!

These should be easy to fix.

> [UI] It highlights some of my shaders as failed to build with red, but actually they did and it is just warnings?!

> [UI] The Filter Output categorises some errors incorrectly under the wrong file

@nkast Since you added the filter parser can you look into these 2?

**Comment by nkast** [comment] 2016-09-04 08:55
| [UI] It highlights some of my shaders as failed to build with red, but actually they did and it is just warnings?!

| [UI] The Filter Output categorises some errors incorrectly under the wrong file

@Linchy can you post a copy of the output and a the .fx file with those warning?
If you disable FilterView you can see the full output and you can select & copy it.

**Comment by cra0zy** [comment] 2016-09-04 09:23
> can't press the DEL key when changing 'reference' paths, it gives an error dialog.

I finally see what's going on.... it's a bug in Eto Forms... well it should be simple to fix.

**Comment by cra0zy** [comment] 2016-09-04 09:59
> [UI] Can't copy one line from the text output, it just highlights all or none.

I can select 1 line just fine...:

![untitled](https://cloud.githubusercontent.com/assets/6773302/18230302/eff737cc-7296-11e6-945d-c936aca4c0b7.png)

**Comment by nkast** [comment] 2016-09-04 11:21
> [UI] It highlights some of my shaders as failed to build with red, but actually they did and it is just warnings?!

@cra0zy 
I think that was by design. We only have 2 states, `Failed` and `Succeed`. 
Build with warnings definitely is not a "Green-light" type of success, the user must know that something is wrong. Do you think we should ignore warnings altogether for now? Meanwhile we can discuss this further in the thread about filtered view improvements.

**Comment by cra0zy** [comment] 2016-09-04 11:39
> @cra0zy 
> I think that was by design. We only have 2 states, Failed and Succeed. 
> Build with warnings definitely is not a "Green-light" type of success, the user must know that something is wrong. Do you think we should ignore warnings altogether for now? Meanwhile we can discuss this further in the thread about filtered view improvements.

It should either be green or it should have a special icon. Failed should be used only if it failed to build the file, warnings don't count since the build did succeed.

**Comment by Linchy** [comment] 2016-09-04 12:47
I uploaded a video showing 4 of the problems: 

https://vimeo.com/181381828

1. I do a build and output goes off screen at the bottom.
2. fxaa fails, but I show it did succeed.
3. I try highlighting one line and it keeps selecting everything.
4. I press backspace a few times on the Output Folder textbox (sorry not references as i said before!) and it works, but then I press delete and it shows the error dialog.

**Comment by cra0zy** [comment] 2016-09-04 12:52
AH, you are using the 3.5 Pipeline... try using the developement build, it should have several issues fixed, tho it might posses some new issues since there was an entire GUI rewrite.

Developemnt build can be downloaded from: http://teamcity.monogame.net/repository/download/MonoGame_PackagingWindows/latest.lastSuccessful/MonoGameSetup.exe?guest=1

**Comment by cra0zy** [comment] 2016-09-04 12:54
You could also use: http://teamcity.monogame.net/repository/download/MonoGame_PackagingWindows/23850:id/MonoGameSetup.exe?guest=1 if you want to try out fixes that are included in #5154

**Comment by Linchy** [comment] 2016-09-04 12:59
I see. Well it is not so easy for me to just upgrade, as I run into so many problems I've just added the MonoGame projects to my game and add fixes as I go. Would take some time to re-apply the fixes and frankly I'd rather spend that time working on the actual game. Once you guys get to a stable release again though and iron out the bugs I'll take another look then.

**Comment by nkast** [comment] 2016-09-04 13:56
[UI] Always asks me if I want to save before building. Can this not just be automatic? In what instance would I not want to save before building?

In case you want to test some alternative options (compression, quality, etc) without making those changes permanent.
VS for example doesn't save your .cs on every build or on every keystroke, it uses a tmp file behind the scene.

> I found this annoying as well... @tomspilman you ok with making this change?

The reason we currently ask the user to save, it's because `Build()` uses the original content file.
If the user choose not to save, the build is canceled. It would be weird to save without the user knowing it, on the other hand he has no choice. It's more like a warning...

`RebuildItems()` saves a temp content file and builds from there:
https://github.com/MonoGame/MonoGame/blob/b7c151b93bc65fb815cb6275d70f0cfeba787fca/Tools/Pipeline/Common/PipelineController.cs#L429-L432

IMO, `Build()` should do the same thing and never ask/save the project.

**Comment by cra0zy** [comment] 2016-09-04 13:59
> The reason we currently ask the user to save, it's because Build() uses the original content file.
> If the user choose not to save, the build is canceled. It would be weird to save without the user knowing it, on the other hand he has no choice. It's more like a warning...
> 
> RebuildItems() saves a temp content file and builds from there:
> https://github.com/MonoGame/MonoGame/blob/b7c151b93bc65fb815cb6275d70f0cfeba787fca/Tools/Pipeline/Common/PipelineController.cs#L429-L432
> 
> IMO, Build() should do the same thing and never ask/save the project.

Visual Studio and MonoDevelop automatically save all when you call build.

**Comment by Scellow** [comment] 2016-09-04 14:10
> In case you want to test some alternative options (compression, quality, etc) without making those changes permanent. VS for example doesn't save your .cs on every build or on every keystroke, it uses a tmp file behind the scene.


There is no Preview panel at all in the Content Builder, why it should matter ?

**Comment by nkast** [comment] 2016-09-04 14:15
> Visual Studio and MonoDevelop automatically call "save al"l when you call build.
Indeed! I had the impression that was not the case.

**Comment by nkast** [comment] 2016-09-04 14:25
> There is no Preview panel at all in the Content Builder, why it should matter ?

I mean change a handful of asset properties, build them and then build your game and test it to see how it goes. Of course you can get the file under version control  or simply keep a copy ahead of time but if you didn't you have to go through all assets again.

That's not a feature request, is it not?

**Comment by Scellow** [comment] 2016-09-04 14:30
> That's not a feature request, is it not?

I just thought about it, that might be usefull

**Comment by cra0zy** [comment] 2016-09-04 14:31
> I mean change a handful of asset properties, build them and then build your game and test it to see how it goes. Of course you can get the file under version control or simply keep a copy ahead of time but if you didn't you have to go through all the assets again.

Undo / Redo works... you can just hold ctrl + z for a bit...

**Comment by PERECil** [comment] 2017-06-13 10:17
I've added issue #5769 for the 4th item. I wasn't aware of this issue list.

**Closed** 2018-02-23 22:00 UTC
Labels: ContentPipeline, Feature Request, Help Wanted
