### ISSUE TITLE
ElapsedGameTime spikes when the window is moved

### ISSUE THREAD

**Issue by neipo13** [MonoGame/MonoGame#7137] opened 2020-04-30 14:10 UTC
Not sure if this is expected or not but has been causing some problems in my movement/collision code. Was not an issue in a previous version of Monogame (I believe I was using 3.5 previously).

Anyway when you set  `IsFixedTimeStep=false` and simply set a `Console.WriteLine(gameTime.ElapsedGameTime.TotalSeconds);` in update you will see that dragging the window around spikes TotalSeconds (up to 0.5s if you hold the window long enough). This is not the case when  `IsFixedTimeStep=true`.

To replicate just create an empty project (I tried on Windows & Desktop GL empty projects) set `IsFixedTimeStep=false`  in constructor or initialize & log the TotalSeconds & drag the window around.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- DesktopGL
- WindowsDX

**Comment by harry-cpp** [comment] 2020-04-30 14:56
Duplicate of #5656

**Closed by harry-cpp** 2020-04-30 14:56 UTC

**Comment by neipo13** [comment] 2020-04-30 15:15
Apologies. I tried looking around but must have missed it. Thanks for the quick response.
