### ISSUE TITLE
Monogame template install error

### ISSUE THREAD

**Issue by MasterQuestMaster** [MonoGame/MonoGame#4848] opened 2016-05-13 09:56 UTC
I already posted this in the community section at the monogame website, but didn't get an answer yet, so I decided to post it here as well.

I tried to install Monogame 3.5 for Visual Studio 2015 on Windows 10.
The setup throws an error when trying to install the templates. It says "Unable to open file to write" on every Template-ZIP. It also doesn't create the Monogame subfolder in the Visual Studio 2015...\Templates\Visual C# folder.

I have administrator rights and executed the setup as administrator. I disabled my Anti-Virus for the installation.
The Visual C# folder had the "write protected" setting in the half-checked state that you get when a program is currently using the folder. Visual Studio is not open though and I don't know how to find out which program currently uses the folder.

I think I would just need the template ZIP files as download to manually copy them to the folder or a fix for my installer problem.
Can I just install the WindowsUniversal.vstemplate from the GIT folder (I won't need the other templates)? How?

Edit: I found out that this issue is a copy of [Can't install templates](https://github.com/mono/MonoGame/issues/4838). I also moved my Libraries to D:\ volume like the creator of that issue.
However, my other question about manually installing the templates still stands and I would appreciate an answer.

**Comment by InfiniteProductions** [comment] 2016-05-13 19:49
For the templates: follow this [link](http://community.monogame.net/t/mg-3-5-installer-vs-wd-2015-templates/7251/2), courtesy of [Damien](http://community.monogame.net/users/Damien_James_Gibson)

So you've got a answer regarding manual installation. I did this and as long as where VS expect to find templates and what you're doing, it "should" work.

(Just for the record, the forum, and even the issue report here are all will-based, no one HAS TO, or MUST reply, answer or anything else to a post or an issue. As frustrating as it could be, it's the way it is, searching the forum may also be a good idea, using relevant keywords as "visual studio" and "template")

**Comment by Jjagg** [comment] 2018-11-16 16:48
Closing as duplicate of #4838.

**Closed by Jjagg** 2018-11-16 16:48 UTC
