### ISSUE TITLE
No keyboard input when instancing and running MonoGame in separate threads?

### ISSUE THREAD

**Issue by kameko** [MonoGame/MonoGame#5222] opened 2016-10-13 19:18 UTC
I'm not sure if this is a bug or a platform limitation, but in my project (MonoGame 3.5 Windows Desktop DirectX, Windows 10 1607), I ran a new thread that instanced MonoGame, and then ran MonoGame's .Run() method in a separate thread (so it would not block the other thread). Trying to get keyboard input from Keyboard.KeyState() in either thread brings up no keypresses, even when using the keyboard. It doesn't matter what thread it happens in, it just works as long as they're both in the same thread. I don't know if this is interesting to the developers or not.

I have to admit though, I was ripping my hair out for a good hour trying to debug this.

**Comment by Jjagg** [comment] 2018-12-11 15:36
Closing as duplicate of #3903.

**Closed by Jjagg** 2018-12-11 15:36 UTC
Labels: Input, Windows
