### ISSUE TITLE
Opening up BRUTE

### ISSUE THREAD

**Issue by tdeeb** [MonoGame/MonoGame#7003] opened 2020-01-28 01:02 UTC
This is not about MG itself but a core component that allows MG to run on consoles - [BRUTE](http://brute.rocks/). Aside from the console-specific bits, is there a reason it's not widely available and open? There's a lack of quality open-source IL to C++ transpilers, and I'd imagine this would create a lot of new opportunities regarding .NET game development, including on desktop, mobile, and especially web platforms.

Currently available .NET AOT options (feel free to enlighten me):
- **.NET Native** - specific to Windows/UWP.
- **CoreRT** - in a preview state and may or may not ever fully develop, as good as it currently is.
- **Unity IL2CPP** - locked down and deeply tied to their proprietary engine.

Based on BRUTE's website, BRUTE sounds like an ideal tool to have an open community of collaborators and users. We know how well it works on consoles due to all the MG games developed for them. I'd love to have a discussion about this and learn more since I don't have access to the tool.

#### What version of MonoGame does the bug occur on:
- Develop

#### What operating system are you using:
- Windows, Linux

#### What MonoGame platform are you using:

- DesktopGL

**Comment by Jure-BB** [comment] 2020-01-28 14:30
I'd like to learn more about this too. 

One known downside of BRUTE is that it's stuck at C# version 5.

**Comment by mrhelmut** [comment] 2020-01-28 17:59
As far as we know, CoreRT is going to retire (and will likely be integrated/replaced by a full AOT scenario in .Net 5 --aka .Net Core 4--, which is scheduled to come out by the end of the year).

**Comment by vpenades** [comment] 2020-02-03 15:32
So, what's the long term plan? update BRUTE to new c# features and keep using it? or abandon it in favour of whatever AOT Microsoft delivers next?

**Comment by tomspilman** [comment] 2020-02-03 15:53
Hey all.

> is there a reason it's not widely available and open? 

Just that i hate a lot of aspects of its current implementation and have been working towards improving it as we work on various ports.

Knowing how open source works it is hard to get any real good contributors.  So opening it will just add more workload on myself providing support, reviewing PRs and usually rejecting them... which i really hate to do.

There is also a more minor issue that technically it exposed the C++ project formats for some consoles.  It is arguable that isn't a big deal... but a little worried by that.

Going to think how i can make it open ASAP and try to guide people into the right direction to help move it forward.

> it's stuck at C# version 5.

 It has been moving forward... we support a lot of 6 and 7.  The issue is the current decompiler we're using to make the code look nice generates some broken code.  Upgrading it may or may not produce better code... i need to test it on some of our projects here.

The bigger plan is to totally drop the decompiler and just work from raw IL.  Our C++ will be uglier, but it will be much more reliable and we'll be in full control over code generation.

> So, what's the long term plan? 

My plan is to keep BRUTE running and as up to date as possible until a superior option presents itself.  At this point i don't see one for the next couple of years.

**Comment by flibitijibibo** [comment] 2020-02-03 16:41
The FNA community is fully prepared to help move this along. We were also looking at updating the decompiler and found out how poorly that project documents their breakages (of which there are a _ridiculous amount of_), but at the same time we've asked ourselves if part of why it's so hard is that there are so few of us looking at it.

Truthfully, based on our experience, everyone who has hacked on BRUTE-FNA knows how terrible their patches are, but the hacks do consistently bring up legitimate issues to be solved later on in the form of not-terrible patches. Bad patches are better than no patches, as crazy as that sounds.

Fixing the template generation is probably the major blocker, as that's where all the NDA stuff is. Aside from that, lots of the portability troubles are either already fixed in the _super_ private repos or have already been raised as issues that someone can look at if they feel inclined. Whatever the blockers are, we're fully prepared to help fix them and also help maintain a FOSS repo, since there definitely isn't an alternative, and the few that have tried don't come remotely close to BRUTE's output, despite all the issues it has right now.

**Comment by tomspilman** [comment] 2020-02-03 16:59
> We were also looking at updating the decompiler and found out how poorly that project documents their breakages

Yeah i sort of gave up on that avenue because of things like that.  It just isn't a reliable library and we need to cut ties with it.

> Fixing the template generation is probably the major blocker

I think i have a plan for that.  The new VS project format allows for us to conditionally include CS files farily easily.  Going to use that to move all that into separate .cs and .target files stored in the console repos.

Going to get that worked out first then we could open things.

**Comment by harry-cpp** [comment] 2020-03-25 18:59
Gonna close this as its not related to the mg repo itself.

**Closed by harry-cpp** 2020-03-25 18:59 UTC

**Comment by RUSshy** [comment] 2020-03-26 01:46
> As far as we know, CoreRT is going to retire (and will likely be integrated/replaced by a full AOT scenario in .Net 5 --aka .Net Core 4--, which is scheduled to come out by the end of the year).

It'll not retire, it is still being developed and maintained, just not by MS itself

https://twitter.com/MStrehovsky/status/1213053948329910272

Many people use and ship their game on steam using CoreRT, in fact, there is even a sample on their repo https://github.com/dotnet/corert/tree/master/samples/MonoGame
