### ISSUE TITLE
ContentTypeReader Type could not be found (Pipeline Tool errro when loading 3d model)

### ISSUE THREAD

**Issue by BrianBergh** [MonoGame/MonoGame#6532] opened 2018-11-11 09:23 UTC
The Development Branch (Visual Studio...), i've got this error:
Microsoft.Xna.Framework.Content.ContentLoadException: 'Could not find ContentTypeReader Type. Please ensure the name of the Assembly that contains the Type matches the assembly in the full type name: Microsoft.Xna.Framework.Content.ReflectiveReader`1[[Microsoft.Xna.Framework.Content.Pipeline.Graphics.MaterialContent, MonoGame.Framework.Content.Pipeline, Version=3.8.0.115, Culture=neutral, PublicKeyToken=null]] (Microsoft.Xna.Framework.Content.ReflectiveReader`1[[Microsoft.Xna.Framework.Content.Pipeline.Graphics.MaterialContent, MonoGame.Framework.Content.Pipeline]])'

when opening a simple model.

(it works in previous versions of Monogame)

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- DesktopGL

**Comment by Jjagg** [comment] 2018-11-11 09:30
This is a duplicate of #6179. You can use the ObjImporter or FbxImporter to process your models (either one will work regardless of the actual format of your model) as a workaround. 
For the cause and more details on this please take a look at the linked issue.

**Closed** 2018-11-11 09:30 UTC
