### ISSUE TITLE
Instancing on OpenGL not working

### ISSUE THREAD

**Issue by YTN0** [MonoGame/MonoGame#6280] opened 2018-04-15 00:56 UTC
#### What version of MonoGame does the bug occur on:
- MonoGame 3.7.0-1465

#### What operating system are you using:
- Windows 10 (latest updates)

#### What MonoGame platform are you using:

- DesktopGL 

Using a test app, instancing works perfectly on DirectX, but on OpenGL, there is just a black / blank screen.

I am attaching a zip file with 2 projects viz. one OpenGL one, and one DirectX one. The code was originally posted in the forum in the following post:

http://community.monogame.net/t/gl-instanced-shader-problem/9721/14

Attention @Jjagg , I believe this is something you worked on.

[samples.zip](https://github.com/MonoGame/MonoGame/files/1911513/samples.zip)

**Comment by YTN0** [comment] 2018-04-15 01:10
@Jjagg I also tested your sample code posted at:

https://github.com/Jjagg/InstancedSample/blob/master/InstancedSampleGL/InstancedModelSampleGame.cs 

Your instancing code seems to work fine on OpenGL, however, @willmotil 's code and my own code (which is also a particle system) does not. So something weird is going on somewhere.

**Comment by Jjagg** [comment] 2018-04-15 12:37
@YTN0 I tried your project and got it to work with two modifications:

1. Your `VertexDeclaration` for the instance data should have usage index 1 for the POSITION element. Since this behaves differently in DesktopGL compared to DX, this is a bug in MonoGame. I've run into DX not handling semantics correctly before (like the infamous bug that VS output must match PS input exactly, rather than relying on semantics). This is because the compiler MG uses does not use the Effect framework stuff (semantics, techniques), instead MG parses this stuff and removes it from the shader before compiling. MG should handle correctly binding the parameters here.

2. I removed the explicit register assignments for the sampler and texture in the shader. It seems like explicitly setting the registers does something funky with MojoShader. By not explicitly setting the registers the texture is correctly assigned to register t0.

With those two modifications the GL version behaved the same the DX version. I'll open two new issues for the above problems. This one can probably be closed then since the problem isn't related to instancing AFAICT.

**Comment by willmotil** [comment] 2018-04-15 13:40
Ya mine was just a stupid mistake, the fact i set it to 1 in the shader just shows i forgot to set it in the cs file. Then later the lack of error messages or inability to identify the affected area of error...

Shows monogame needs more error messages or warnings for the shaders on building.
My shader syntax understanding is poor but i think it was more that i couldn't find what was in error.

**Comment by YTN0** [comment] 2018-04-15 21:47
@Jjagg  Thanks for looking into this! I'll close this one out.

**Closed** 2018-04-18 07:01 UTC
