### ISSUE TITLE
3.7.0.1371 - OpenAL lib warnings?

### ISSUE THREAD

**Issue by 8bitdna** [MonoGame/MonoGame#6228] opened 2018-03-05 09:22 UTC
Not sure if this one truly is an issue or just some warnings, but I wanted to report it just in-case.  I see the following pop up in the console of every app I run:

AL lib: (WW) GetProcPath: Failed to readlink /proc/self/file: No such file or directory
AL lib: (WW) alc_initconfig: Failed to initialize backend "jack"

MonoGame - 3.7.0.1371
OSX 10.13.3 High Sierra
Mono 5.4.1.7
Rider IDE 2017.3.1

Apologies if its a red herring.

**Comment by 8bitdna** [comment] 2018-03-05 09:32
I should also add I've not tried to use any audio yet, I will report back if I find any functional issues as well on playing some basic sounds a little later.  I'm pretty new to MonoGame and the whole .NET ecosystem.  Last dabbled 10 years ago so be gentle :)

**Comment by Jjagg** [comment] 2018-03-05 10:04
This shouldn't cause any audio issues, because another audio backend should be loaded. Not sure why it's logged as a warning, we could look into disabling that.

Good luck and have fun with MonoGame! :)

**Comment by 8bitdna** [comment] 2018-03-05 13:34
Cheers @Jjagg Appreciate your response, good to hear its just a warning.  MonoGame has been awesome so far, enjoying things and coming (slowly) back up to speed with the world of .NET and C# :) :)  Understanding what is going on with the templates and the build process is helping me make sense of some things, can never learn enough :)

**Comment by cra0zy** [comment] 2018-09-30 14:02
Not a bug, just a warning that can be safely ignored, closing...

**Closed by cra0zy** 2018-09-30 14:02 UTC
