### ISSUE TITLE
Can't set MGCB Editor as default in VS 2019

### ISSUE THREAD

**Issue by harry-cpp** [MonoGame/MonoGame#7301] opened 2020-08-12 08:21 UTC
Quite a strange issue, tldr. you can't set MGCB Editor as default unless you specify the full path to it.

@jnoyola @Jjagg You guys are Windowsy guys, can't we use the old registry trick during register to make it the default editor for .mgcb files in VS 2019?

**Comment by Jjagg** [comment] 2020-08-12 16:05
Sounds like a VS bug. Should be logged with them if it isn't already.

**Comment by harry-cpp** [comment] 2020-08-12 17:12
What about the registry trick?

**Comment by willmotil** [comment] 2020-08-12 19:15
It might be simpler to call it a vs bug if...
Setting the mgcb file to open with any of the other text editing programs vs 2019 has in it did not work.  

But they all do even adding notepad++ then setting it to the default works on double click.

And it does open with double clicking from explorer...
Which means i dunno what... that it works but something vs is doing either adds a argument the editor hates or checks for some requirement that the editor doesn't meet and falls back?.

Maybe the name just needs to be in all capital letters like the rest of the programs lol.

![VeryOdd](https://user-images.githubusercontent.com/7495196/90057309-359b1e80-dcae-11ea-8ede-b90f076e3720.png)

It's almost like

**Comment by jnoyola** [comment] 2020-08-12 19:15
When I had tried the registry trick, it didn't work for me with VS 2019 so I left it out. That being said, I didn't confirm that the same thing worked with VS 2017, so it's possible I made a mistake somewhere.

> you can't set MGCB Editor as default unless you specify the full path to it

Where are you trying to set it? Are you referring to the [CurrentSettings.vssettings](https://stackoverflow.com/questions/25038191/add-visual-studio-open-with-option-for-all-file-types/25190833#25190833) file? Requiring an absolute path makes sense to me -- what would you want it to be relative to, the VS executable in Program Files?

**Comment by willmotil** [comment] 2020-08-12 19:49
The new editor works as expected in vs2017 and every were else this is only vs2019 and vs 2019 can be of course set to open other the .mgcb file extension with other applications just not our application specifically.

**Comment by jnoyola** [comment] 2020-08-12 20:14
It's possible. You could try right clicking on the folder or exe, opening properties, and see if there's an "Unblock" checkbox at the bottom. I've had that issue while using PowerShell to load DLLs downloaded from nuget packages before.

**Comment by willmotil** [comment] 2020-08-12 20:44
Um wait there are 2 exe's in two different folders  .... ? ....

_Ignore the copy i made._
![Humm02ImSoConfusedNow](https://user-images.githubusercontent.com/7495196/90065727-b19b6380-dcba-11ea-9900-2d71b17902db.png)

Using 'open with' on the copy in the deep folder though works as well after adding and then defaulting it's double clickable.
![Humm](https://user-images.githubusercontent.com/7495196/90065979-0e971980-dcbb-11ea-9c0d-bd2a3f46b476.png)

**Comment by willmotil** [comment] 2020-08-12 21:01
Hell if i know i renamed the old one so that is actually the wpf version that's gotta be the pre-release version.

**Comment by jnoyola** [comment] 2020-08-12 22:12
The exe in the `dotnet-mgcb-editor` folder is the one you're expecting that is built from our csproj and distributed in the nuget package.

The exe in the `.dotnet\tools` folder is a wrapper that dotnet generates when you install a global tool. This allows dotnet to only add that `.dotnet\tools` folder to your `PATH`, rather than updating your `PATH` every time you install/uninstall a global tool. It simply calls the real exe with any parameters.

**Comment by willmotil** [comment] 2020-08-12 22:34
Oh no it works on both i just renamed a copy of it i was gonna move it and try it but i didn't test that.

I suppose that's the same as using the full path like harry said.
You still have to navigate all the way down to the deep folder using the open with > Add > browse button.

**Comment by jnoyola** [comment] 2020-08-12 22:54
Ok, I'm not understanding the problem then. How would you expect to "Open With" the MGCB Editor without browsing into its folder? Like what is the alternative to using this absolute path?

**Comment by willmotil** [comment] 2020-08-13 01:35
Well if you go by the documentation on the front page then you can install this via a command line, which as far as i know works now. In fact even this bugged version im using 1375, though i had to use the secondary instructions windows did report that this very tool was both installed and register.  Which it then shows up in vs2019 added tools list, without having to use open with manually to register it....   It however failed to open on double clicking the mgcb file thru that method. Also as stated it opened from explorer meaning it was verifyably registered.  Which is strange.

Using the manual open with method and navigating directly to the exe this of course as seen above allows the tool to work via double click.   

The problem is well the documentation says use the install register commands and i can't see why they shouldn't work.  
Also that is a really deep hidden path to ask all your users to navigate i mean open with is a work around but doesn't explain the behavior.

**Comment by jnoyola** [comment] 2020-08-13 02:02
To get one thing straight, the current register command only registers it to open from Windows. It doesn't touch Visual Studio.

Now, you're saying upon doing that, the exe shows up in the **"added tools list"** where it **doesn't work**, but using **"open with"** it **does work**. What is the "added tools list"? Since registering currently only registers in Windows, not in VS, it sounds like what you're talking about might be expected behavior and entirely different from what Harry is talking about.

@harry-cpp could you please describe what you're talking about? Because I'm lost.

**Comment by willmotil** [comment] 2020-08-13 02:20
Ya maybe we are talking about different things but essentially when i double click the mgcb file and i had it set to use the mgcb editor it would not use that and instead use source or notepad or whatever the last program that it decided to use as a default.
I had made a assumption which maybe wrong that this is what he was referring to as well.

**Comment by NicusorN5** [comment] 2020-08-13 05:46
I remember this bug appearing after upgrading both Monogame (to 3.7.???) and Visual Studio 2019. Might be a VS bug tho.

**Comment by harry-cpp** [comment] 2020-08-13 07:21
@willmotil I don't want to sound mean, but you are really not helping in resolving this issue, please don't try to add random topics / assumptions in here.

@jnoyola After doing the --register command, Open With dialog in VS showed me a "mgcb-editor-wpf" option, which did not work if you tried setting it as default, however you could still open using it by not setting it as the default option.

Yes, probably a bug in Visual Studio, but I would like to workaround it if possible.

**Comment by jnoyola** [comment] 2020-08-13 16:09
I see. Is VS registration something we want to accomplish programmatically anyway? It might be less important whether the "Open With" dialog works if we can register in VS ourselves. I think we should try either the registry (which it now sounds like multiple people are saying this doesn't work in VS 2019) or the CurrentSettings.vssettings file.

**Comment by willmotil** [comment] 2020-08-15 21:43
> 
> 
> @willmotil , but you are really not helping in resolving this issue, please don't try to add random topics / assumptions in here.
> 

So he asked me if we are talking about the same thing ? 

> @jnoyola After doing the --register command, Open With dialog in VS showed me a "mgcb-editor-wpf" option, which did not work if you tried setting it as default

Am i in error here maybe you can clarify how are we not talking about the same thing?

> however you could still open using it by not setting it as the default option.

I typically open the mgcb file and i imagine everyone else does too by double clicking.
How is it possible to double click open a mgcb extension file in vs 2019 if it is not set as the default?
Im more confused now then before. 

"I don't want to sound mean"

You don't sound mean, your reply is condescending and makes no sense. 
It's honestly fine i really don't care, i wont bring any bugs to your attention anymore.

**Comment by harry-cpp** [comment] 2020-08-23 17:22
The bug is in Visual Studio, its unable to set an application thats default for an extension as the default application unless you manually specify the path to the .exe. You can try this with a .png file, just try setting the default editor for it to the default system application in VS and it will still open it in its own internal editor.

The solution to this whole problem is either to write an editor extension or maybe CurrentSettings.vssettings that @jnoyola  spoke about earlier.

**Comment by HopefulFrog** [comment] 2020-10-10 01:15
I am able to set the editor as the default using "Open With...", but it still only opens a text version of the MGCB file when I double click it in the solution explorer. However, if I double click the editor in the selection of options in the "Open With..." dialog, that opens up the editor with the MGCB file opened in it.

**Comment by SimonDarksideJ** [comment] 2020-10-14 11:15
Not sure that is the root of the issue @harry-cpp, I have .mgcb files defaulted to the MGCB-Editor and have "set as default" the mgcb editor in VS.

However, since the 3.7 upgrade, every time I double click on the content file in Visual Studio, I still get the text editor.  VS doesn't seem to be respecting the default for some reason.

**Comment by harry-cpp** [comment] 2020-10-14 11:54
https://github.com/MonoGame/MonoGame/issues/7301#issuecomment-678800974

**Comment by bjornenalfa** [comment] 2021-05-17 10:27
This problem seems to be fixed by running `mgcb-editor --register`. Should this issue be closed?

**Comment by lonely-unicorn** [comment] 2022-04-05 23:58
I don't know about vs2019 but in vs2022 "set as default" works.(monogame 3.8)

**Comment by mrhelmut** [comment] 2022-04-23 16:58
Do we have a solution for that in VS2022?

**Comment by mrhelmut** [comment] 2022-04-30 09:54
Moving forward, we'll only support VS 2022 as of 3.8.1 and we now have VS extensions for Windows and macOS which automatically sets the MGCB editor as the default tool to open .mgcb files.

These extensions are not yet published to the VS marketplace.

**Closed by mrhelmut** 2022-04-30 09:54 UTC
Labels: MGCB Editor
