### ISSUE TITLE
MonoGame Pipeline on windows 10 missing library

### ISSUE THREAD

**Issue by Vodacek** [MonoGame/MonoGame#4360] opened 2015-12-24 16:45 UTC
I have latest MonoGame from source and also the latest Windows 10 (will all updates installed), I am getting this exception when I try to build FBX model:

C:/Users/admin/Desktop/programy/devkniha/zvb23/zvb2/Rabaty/RabatyContent/zvb2/sklepeni/sklepeni_chodba005p_Low.fbx: error: Importer 'FbxImporter' had unexpected failure!
Assimp.AssimpException: Error loading unmanaged library from path: Assimp64.dll, see inner exception for details.
Uvedeně modul nebyl nalezen. (Vějimka na z kladŘ hodnoty HRESULT: 0x8007007E) ---> System.IO.FileNotFoundException: Uvedeně modul nebyl nalezen. (Vějimka na z kladŘ hodnoty HRESULT: 0x8007007E)
   --- Konec trasov nˇ z sobnˇku pro vnitýnˇ vějimku ---
   v Assimp.Unmanaged.AssimpLibraryWindowsImplementation.NativeLoadLibrary(String path)
   v Assimp.Unmanaged.AssimpLibraryImplementation.LoadAssimpLibrary(String path)
   v Assimp.Unmanaged.AssimpLibrary.LoadLibrary()
   v Assimp.Unmanaged.AssimpLibrary.LoadIfNotLoaded()
   v Assimp.Unmanaged.AssimpLibrary.CreatePropertyStore()
   v Assimp.AssimpContext.CreateConfigs()
   v Assimp.AssimpContext.ImportFile(String file, PostProcessSteps postProcessFlags)
   v Microsoft.Xna.Framework.Content.Pipeline.OpenAssetImporter.Import(String filename, ContentImporterContext context) v c:\Users\admin\Desktop\programy\devkniha\zvb23\Libs\MonoGame\MonoGame.Framework.Content.Pipeline\OpenAssetImporter.cs:ý dek 220
   v Microsoft.Xna.Framework.Content.Pipeline.FbxImporter.Import(String filename, ContentImporterContext context) v c:\Users\admin\Desktop\programy\devkniha\zvb23\Libs\MonoGame\MonoGame.Framework.Content.Pipeline\FbxImporter.cs:ý dek 22
   v Microsoft.Xna.Framework.Content.Pipeline.ContentImporter`1.Microsoft.Xna.Framework.Content.Pipeline.IContentImporter.Import(String filename, ContentImporterContext context) v c:\Users\admin\Desktop\programy\devkniha\zvb23\Libs\MonoGame\MonoGame.Framework.Content.Pipeline\ContentImporter.cs:ý dek 45
   v MonoGame.Framework.Content.Pipeline.Builder.PipelineManager.ProcessContent(PipelineBuildEvent pipelineEvent) v c:\Users\admin\Desktop\programy\devkniha\zvb23\Libs\MonoGame\MonoGame.Framework.Content.Pipeline\Builder\PipelineManager.cs:ý dek 577

It simply says that, library Assimp64.dll is missing, but it is present inside folder with MonoGame pipeline. I tried also to download and install MonoGame from web installer, but exception is the same. Does anyone also have this issue?

**Comment by KonajuGames** [comment] 2015-12-24 17:47
32-bit or 64-bit Windows 10? Our content pipeline is built for 64-bit
Windows.

**Comment by Vodacek** [comment] 2015-12-24 18:32
I have 64 bit Windows 10 1511 build 10586.36

**Comment by Vodacek** [comment] 2015-12-26 18:06
@KonajuGames I forget to mention that this issue occoured when I installed new Windows 10 build...

**Comment by tomspilman** [comment] 2015-12-31 11:37
I'm really not sure what the issue is here.  We would have to have someone repro it and debug it.

My guess is that it just isn't finding the dll because of the working directory from which MGCB.exe is being launched.

Could you try manually building your content using the MGBC.exe from the command line instead of via the Pipeline tool.

**Comment by davepermen** [comment] 2017-03-11 11:22
Just for your Info, same issue on actual Windows 10 (15055 atm), clean fresh installed vs2017 and monogame 3.6.

assimp64 not loading. even when launching from the folder itself. so it surely should find it.

German Error Output here:

C:/Users/davep/Projekte/Far Off Wanderer/game/src/game/Content/schiff V37.FBX
C:/Users/davep/Projekte/Far Off Wanderer/game/src/game/Content/schiff V37.FBX: error: Importer 'FbxImporter' had unexpected failure!
Assimp.AssimpException: Error loading unmanaged library from path: Assimp64.dll, see inner exception for details.
Das angegebene Modul wurde nicht gefunden. (Exception from HRESULT: 0x8007007E) ---> System.IO.FileNotFoundException: Das angegebene Modul wurde nicht gefunden. (Exception from HRESULT: 0x8007007E)
   --- End of inner exception stack trace ---
   at Assimp.Unmanaged.AssimpLibraryWindowsImplementation.NativeLoadLibrary(String path)
   at Assimp.Unmanaged.AssimpLibraryImplementation.LoadAssimpLibrary(String path)
   at Assimp.Unmanaged.AssimpLibrary.LoadLibrary()
   at Assimp.Unmanaged.AssimpLibrary.LoadIfNotLoaded()
   at Assimp.Unmanaged.AssimpLibrary.CreatePropertyStore()
   at Assimp.AssimpContext.CreateConfigs()
   at Assimp.AssimpContext.ImportFile(String file, PostProcessSteps postProcessFlags)
   at Microsoft.Xna.Framework.Content.Pipeline.OpenAssetImporter.Import(String filename, ContentImporterContext context)
   at Microsoft.Xna.Framework.Content.Pipeline.ContentImporter`1.Microsoft.Xna.Framework.Content.Pipeline.IContentImporter.Import(String filename, ContentImporterContext context)
   at MonoGame.Framework.Content.Pipeline.Builder.PipelineManager.ProcessContent(PipelineBuildEvent pipelineEvent)

**Comment by davepermen** [comment] 2017-03-11 22:41
Apparently it's fixed by installing "Visual C++ Redistributable für Visual Studio 2012 Update 4" so i _guess_ that should get added to the distribution? (now onto the next bits that don't work.. something about nvidia converter for textures)

**Comment by Jjagg** [comment] 2018-12-11 14:34
Fixed in #6222.

**Closed by Jjagg** 2018-12-11 14:34 UTC
