### ISSUE TITLE
Building fail in pipeline tool PNG

### ISSUE THREAD

**Issue by elguoshiy** [MonoGame/MonoGame#7055] opened 2020-03-04 21:24 UTC
I dpn't know what ot do please HELP!
C:/Users/joelg/source/repos/Shooting gallery/Shooting gallery/Content/crosshairs.png
C:/Users/joelg/source/repos/Shooting gallery/Shooting gallery/Content/crosshairs.png: error: Importer 'TextureImporter' had unexpected failure!
System.DllNotFoundException: Unable to load DLL 'FreeImage': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at FreeImageAPI.FreeImage.GetFileType(String filename, Int32 size)
   at FreeImageAPI.FreeImage.LoadEx(String filename, FREE_IMAGE_LOAD_FLAGS flags, FREE_IMAGE_FORMAT& format)
   at Microsoft.Xna.Framework.Content.Pipeline.TextureImporter.Import(String filename, ContentImporterContext context)
   at Microsoft.Xna.Framework.Content.Pipeline.ContentImporter`1.Microsoft.Xna.Framework.Content.Pipeline.IContentImporter.Import(String filename, ContentImporterContext context)
   at MonoGame.Framework.Content.Pipeline.Builder.PipelineManager.ProcessContent(PipelineBuildEvent pipelineEvent)

**Comment by willmotil** [comment] 2020-03-04 22:34
http://community.monogame.net/t/monogame-noob-unable-to-load-freeimage/6255/6

**Comment by elguoshiy** [comment] 2020-03-05 07:49
I'd installed Visual C++ Redistributable for Visual Studio 2012 Update 4 but it still doesn't work.

> http://community.monogame.net/t/monogame-noob-unable-to-load-freeimage/6255/6

**Comment by elguoshiy** [comment] 2020-03-05 07:54
Nvm, It worked Thanks

**Comment by tomspilman** [comment] 2020-03-05 13:47
@harry-cpp @Jjagg - So this issue which is fairly common and solved by installing the VS201 runtime...   isn't something we can fix from a nuget.  We would have to ensure we static link against the runtime in all our 3rd party native dlls.

**Comment by Jjagg** [comment] 2020-03-05 21:10
See also #4485 and #3556.

**Comment by willmotil** [comment] 2020-03-06 19:11
I must have answered this question 30 times now.  This really is a annoying bug.

The vs 2012 and or 2013 also drop in a couple environmental variables.

**Comment by harry-cpp** [comment] 2020-03-28 13:26
Duplicate of https://github.com/MonoGame/MonoGame/issues/3556

**Closed by harry-cpp** 2020-03-28 13:26 UTC
