### ISSUE TITLE
MonoGame Pipeline Tool crash when adding references

### ISSUE THREAD

**Issue by arcanewater** [MonoGame/MonoGame#5944] opened 2017-09-15 08:25 UTC
Version 3.6.0.1625
MacOS: 10.12.6

Using MacOS pipeline tool, when trying to add references to dll on clicking OK it crashes. 

```
Application Specific Information:
System.NullReferenceException: Object reference not set to an instance of an object
  at (wrapper managed-to-native) AppKit.NSApplication:NSApplicationMain (int,string[])
  at AppKit.NSApplication.Main (System.String[] args) [0x0003d] in <c6073fd3d8a24e8c8486d70c91715e73>:0 
  at Eto.Mac.Forms.ApplicationHandler.Run () [0x0004e] in <07e1a440fba94bd1a16059b07bd0b6e0>:0 
  at Eto.Forms.Application.Run (Eto.Forms.Form mainForm) [0x0002c] in <330b729e54b34ae38c2b6aa66a4c6304>:0 
  at MonoGame.Tools.Pipeline.Program.Main (System.String[] args) [0x00066] in <954e325a58604e01b1c6d4ec1ce51c32>:0 
```
I am using current development build of pipeline tool for Mac.

**Comment by tomspilman** [comment] 2017-09-16 01:08
@cra0zy @dellis1972 ?

**Comment by cra0zy** [comment] 2017-09-16 17:13
@arcanewater Can you try the develop version of MG? I think that bug got fixed in there.

**Comment by arcanewater** [comment] 2017-09-16 19:01
@cra0zy Tried the newest one and its crashing when adding references.

**Comment by stephkno** [comment] 2017-09-29 08:59
I also have this issue with the develop build.

**Comment by VampireMonkey** [comment] 2018-09-15 07:52
It's also crashing for me on Windows 10, also using developer build, however it seems to work fine if i add the reference manually by editing the "Content.mgcb" in my game project.

**Comment by cra0zy** [comment] 2018-09-15 08:15
I was not able to reproduce the issue back than, if you have a set of steps that need to be done for the crash to occur, do tell and I'll take a loot at it on Monday.

**Comment by VampireMonkey** [comment] 2018-09-15 22:01
@cra0zy Tried following [this guide](http://blog.dylanwilson.net/posts/2015/creating-custom-content-importers-for-the-monogame-pipeline/)
Oddly enough tho, it works when adding the reference manually.

**Comment by cra0zy** [comment] 2018-09-30 14:52
Fixed in devel.

**Closed by cra0zy** 2018-09-30 14:52 UTC
Labels: ContentPipeline, Help Wanted, MacOS
