### ISSUE TITLE
Input lag on Linux

### ISSUE THREAD

**Issue by ddabrahim** [MonoGame/MonoGame#6345] opened 2018-06-24 07:21 UTC
Hi. 
I'm experiencing input lag on Ubuntu 18.04.
I'm trying to move a sprite around the screen but the sprite stop every 2 seconds.
The frame rate does not drop and the speed of the sprite does not fluctuate.

Tried with different keys and different keyboards and I get the same result.
I believe it is the same problem like it was on Windows:
https://github.com/MonoGame/MonoGame/pull/5520
This is the code I'm trying
```
 public class Ship
    {
        public Vector2 Position = new Vector2(100, 100);
	public int Speed = 200;

        public void Update(GameTime gameTime)
		{
			KeyboardState kState = Keyboard.GetState();

			float deltaTime = (float)gameTime.ElapsedGameTime.TotalSeconds;

			if(kState.IsKeyDown(Keys.Right))
			{
				Position.X += Speed * deltaTime;
			}

			if (kState.IsKeyDown(Keys.Left))
                        {
				Position.X -= Speed * deltaTime;
                        }

			if (kState.IsKeyDown(Keys.Up))
                       {
				Position.Y -= Speed * deltaTime;
                       }

			if (kState.IsKeyDown(Keys.Down))
                      {
				Position.Y += Speed * deltaTime;
                      }

		}
    }
```

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7.0.1

#### What operating system are you using:
- Ubuntu 18.04 64bit

#### What MonoGame platform are you using:

-Desktop OpenGL

Thanks.

**Comment by cra0zy** [comment] 2018-06-24 08:41
I am unable to reproduce your bug... few questions:
1. Are you using NuGet
2. When did you create your project from templates

I have a feeling that it might be native dependencies that are causing the problem since there was a bug with SDL 2.0.5 and its keyboard pressed checking on Linux. The way to fix it is to:
- Delete `x86` and `x64` folders from project
- Delete `libSDL2-2.0.0.dylib` and `libopenal.1.dylib`
- Than depending on what you want to use:
  - If you want to use NuGet
    - Remove all MonoGame references from project
    - Add development nuget feed: http://teamcity.monogame.net/guestAuth/app/nuget/v1/FeedService.svc/
    - Add nuget `MonoGame.Framework.DesktopGL` to your project from that feed (you'll need to check prerelease checkbox I think)
  - If you want to use local refs
    - Make sure you have the newest MonoGame addin for MonoDevelop
    - Create a new empty project
    - Copy over the stuff you deleted above to it and set their "build action" to "copy if newer"

**Comment by ddabrahim** [comment] 2018-06-24 10:02
1. I don't use NuGet
2. Two days ago.

Thank you for the suggestions. I have installed MonoDevelop and the MonoGame extension few days ago, only getting started and it saying there is no update available for MonoDevelop. Is that mean it is the latest, or should I download and install manually? I tried what you told but it did not solve the problem but I was not expecting anything else since noting has changed, updated.

One thing I have noticed though. MonoDevelop tells me the MonoGame version number is 3.7 but If I go to the project preferences, it shows the assembly version number is 3.6
Probably I'm not using the latest development build then but have no clue how to update it.

Probably it is not a bug then, only me using an outdated version.

Thanks.

**Comment by cra0zy** [comment] 2018-06-24 10:09
You can get the newest development build for Linux from: http://teamcity.monogame.net/repository/download/MonoGame_PackageMacAndLinux/latest.lastSuccessful/Linux/monogame-sdk.run?guest=1

Just follow the instructions in my comment above, and I would recommend using NuGet.

I'm gonna close this as it seems to be just the case of outdated libraries, if you have any more questions feel free to ask them and if the problem appears after updating to the latest version, feel free to reopen the issue.

**Closed by cra0zy** 2018-06-24 10:09 UTC
