### ISSUE TITLE
ContentTypeReaderManager exception in Android AnyCPU Release with trimming

### ISSUE THREAD

**Issue by Jekops** [MonoGame/MonoGame#8061] opened 2023-09-01 11:54 UTC
I'm currently facing an issue with MonoGame version 3.8.1.303 targeting net6.0 for android with Visual Studio 2022 version 17.7.3 for Windows.

The project runs fine with Windows AnyCPU Debug/Release and Android AnyCPU Debug, but when I switch to **Android AnyCPU Release**, a runtime exception of type ContentLoadException raise, while loading a SpriteFont with the standard MonoGame ContentManager.

```
Time	Device Name	Type	PID	Tag	Message
08-31 16:36:13.362	pixel_5_-_api_33	Info	29249	MonoDroid	android.runtime.JavaProxyThrowable: Microsoft.Xna.Framework.Content.ContentLoadException: Could not find ContentTypeReader Type. Please ensure the name of the Assembly that contains the Type matches the assembly in the full type name: Microsoft.Xna.Framework.Content.ListReader`1[[System.Char, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]] (Microsoft.Xna.Framework.Content.ListReader`1[[System.Char, mscorlib]])
   at Microsoft.Xna.Framework.MonoGameAndroidGameView.UpdateAndRenderFrame()
   at Microsoft.Xna.Framework.MonoGameAndroidGameView.processStateRunning(CancellationToken token)
   at Microsoft.Xna.Framework.MonoGameAndroidGameView.RunIteration(CancellationToken token)
   at Microsoft.Xna.Framework.MonoGameAndroidGameView.<>c__DisplayClass62_0.<WorkerThreadFrameDispatcher>b__0(Object s)
   at Android.App.SyncContext.<>c__DisplayClass3_0.<Send>b__0()
   at Java.Lang.Thread.RunnableImplementor.Run()
   at Java.Lang.IRunnableInvoker.n_Run(IntPtr , IntPtr )
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V , IntPtr , IntPtr )
	at mono.java.lang.RunnableImplementor.n_run(Native Method)
	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

From the MonoGame source file ContentTypeReaderManager in method LoadAssetReaders.

The sprite font XNB file contains following readers.
```
Microsoft.Xna.Framework.Content.SpriteFontReader, MonoGame.Framework, Version=3.8.1.303, Culture=neutral, PublicKeyToken=null
Microsoft.Xna.Framework.Content.Texture2DReader
Microsoft.Xna.Framework.Content.ListReader`1[[Microsoft.Xna.Framework.Rectangle, MonoGame.Framework, Version=3.8.1.303, Culture=neutral, PublicKeyToken=null]]
Microsoft.Xna.Framework.Content.RectangleReader
Microsoft.Xna.Framework.Content.ListReader`1[[System.Char, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]
Microsoft.Xna.Framework.Content.CharReader
Microsoft.Xna.Framework.Content.ListReader`1[[Microsoft.Xna.Framework.Vector3, MonoGame.Framework, Version=3.8.1.303, Culture=neutral, PublicKeyToken=null]]
Microsoft.Xna.Framework.Content.Vector3Reader
```

This happen in both emulated and real devices, tested with Android 11 (API 30) and Android 13 (API 33).

I find a similar issue here: https://github.com/MonoGame/MonoGame/issues/7174, solved in a previous version of the software.

Here a sample project showing the issue.
[MonoGameTest8.zip](https://github.com/MonoGame/MonoGame/files/12497569/MonoGameTest8.zip)

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.1.303

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:
- Android

**Comment by Jekops** [comment] 2023-09-02 11:36
I'm wondering why MonoGame is forcing me to include the mscorlib assembly to instantiate a System.Char, when in net 6.0 the type is correctly handled by the System.Private.CoreLib as defined in the XNB file.

The exception message is showing that the type **[System.Char, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]** is replaced by the **[System.Char, mscorlib]** and this seems to be a bug in the MonoGame framework.

mscorlib is mainly a .net framework compatibility assembly and should not replace the System.Private.CoreLib.

**Comment by mrhelmut** [comment] 2023-12-16 10:13
Duplicate of #7872

**Closed by mrhelmut** 2023-12-16 10:13 UTC
