### ISSUE TITLE
MGCB-Editor about page needs some love

### ISSUE THREAD

**Issue by SimonDarksideJ** [MonoGame/MonoGame#7332] opened 2020-08-25 23:38 UTC
A minor niggle, but the title on the MGCB-Editor about page should be more friendly.

![image](https://user-images.githubusercontent.com/1793042/91238159-4d55b680-e734-11ea-9059-be6efa84634f.png)

The text layout also needs formatting.

Might also be good to add a link to the MGCB-Editor documentation guide.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8

#### What operating system are you using:
- Windows

**Comment by harry-cpp** [comment] 2020-08-26 04:44
Duplicate of #6242

**Closed by harry-cpp** 2020-08-26 04:44 UTC
