### ISSUE TITLE
MonoDevelop: Invalid Configuration Mapping (Fedora 29)

### ISSUE THREAD

**Issue by briguyjm** [MonoGame/MonoGame#6593] opened 2018-12-13 03:43 UTC
I am on Fedora 29 and have `mono` installed from the Mono project's custom repo. I have installed MonoGame 3.7.1. I am using MonoDevelop v7.7 (build 1869)

MonoDevelop's about page:

> === MonoDevelop ===
> 
> Version 7.7 (build 1869)
> Installation UUID: 2805de41-8b57-4629-bd45-5cc3256a0651
> 	GTK+ 2.24.32 (Breeze theme)
> 
> === Mono Framework MDK ===
> 
> Runtime:
> 	Mono 5.16.0.220 (tarball Mon Nov 26 17:05:57 UTC 2018) (64-bit)
> 
> === NuGet ===
> 
> Version: 4.7.0.5148
> 
> === .NET Core ===
> 
> Runtime: /usr/share/dotnet/dotnet
> Runtime Version: 2.2.0
> SDK: /usr/share/dotnet/sdk/2.2.101/Sdks
> SDK Version: 2.2.101
> MSBuild SDKs: /usr/lib/mono/msbuild/15.0/bin/Sdks
> 
> === Build Information ===
> 
> Release ID: 707001869
> Git revision: f0f3d1d931d44682f076dde486ecec835f705b8d
> Build date: 2018-11-29 14:54:14-05
> 
> === Operating System ===
> 
> Linux
> Linux 4.19.7-300.fc29.x86_64 #1 SMP Wed Dec 5 22:21:07 UTC 2018 x86_64
> 
> === Enabled user installed extensions ===
> 
> MonoGame Extension 3.7.0.1
> 

Output of `mono --version`
```
Mono JIT compiler version 5.16.0.220 (tarball Mon Nov 26 17:05:57 UTC 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug 
        Interpreter:   yes
        LLVM:          yes(3.6.0svn-mono-/)
        GC:            sgen (concurrent by default)
```

When using the MonoGame addin, the project is created just fine, but it is always appended by '.Desktop'. For example, if I make `projectfoo`, the actual project is renamed to `projectfoo.Desktop`. And there is a warning that that reads _Invalid configuration mapping_ that shows up next to the project name (but not the solution) in MonoDevelop. Opening the solution file in MonoDevelop does not allow the project to build. I get the error:

```
Thread finished: Finalizer #2
Cannot open assembly '/home/brian/Projects/monogame/monogame/bin/DesktopGL/Any CPU/Debug/monogame.Desktop.exe': No such file or directory.
```

Finally, if I open the `.csproj` file directly, instead of the `.sln` file in MonoDevelop, I can work with the software, and it builds and runs just fine. The downside is that it creates another `.sln` file in the same directory as the `.csproj` file.

I don't know why this does this. I also don't know if there is a command line build or project generator I should be using instead. Any help would be appreciated. 

I have attached a screenshot of what the MonoDevelop window looks like. This is right after I started a new MonoGame project using the addin. I have not edited any of the files

![image](https://user-images.githubusercontent.com/24214308/49914369-f1170a00-fe5e-11e8-8b34-7eb13c466912.png)

And the window when I click on the red 'X'

![image](https://user-images.githubusercontent.com/24214308/49914390-0be97e80-fe5f-11e8-93d9-b121d7854a01.png)

And lastly, the output of `tree` in the project directory

```
.
├── monogame
│   ├── app.manifest
│   ├── bin
│   │   └── DesktopGL
│   │       └── Any CPU
│   │           └── Debug
│   ├── Content
│   │   └── Content.mgcb
│   ├── Game1.cs
│   ├── Icon.bmp
│   ├── Icon.ico
│   ├── monogame.Desktop.csproj
│   ├── obj
│   │   └── Any CPU
│   │       └── Debug
│   │           └── monogame.Desktop.csprojAssemblyReference.cache
│   ├── Program.cs
│   └── Properties
│       └── AssemblyInfo.cs
└── monogame.sln

```

**Comment by Jjagg** [comment] 2018-12-13 23:13
Hey @briguyjm! 
I can replicate this issue. Damn, these MD templates have broken a lot before, that's always frustrating.

> I also don't know if there is a command line build or project generator I should be using instead.

There isn't one yet, but we're working on `dotnet new` support. There are unofficial `dotnet new` templates available. 

@cra0zy Can these be installed with CLI or only from source right now? 
Considering this add-in is broken and we don't have any other official way to generate a project on Linux,  maybe we should add the `dotnet new` solution to the official docs. Also we should fix this of course.

**Comment by cra0zy** [comment] 2018-12-14 11:43
> @cra0zy Can these be installed with CLI or only from source right now?
> Considering this add-in is broken and we don't have any other official way to generate a project on Linux, maybe we should add the `dotnet new` solution to the official docs. Also we should fix this of course.

I have compiled the official templates:
```
dotnet new --install MonoGame.Templates.CSharp
dotnet new mgdesktopgl
```

Also this is a duplicate of #6227, as such closing.

**Closed by cra0zy** 2018-12-14 11:43 UTC

**Comment by peon501** [comment] 2018-12-16 02:56
Dude use JetBrains Rider :)

**Comment by briguyjm** [comment] 2018-12-22 01:48
Rider doesn't work, it can't find the target framework for a Cross Platform application

**Comment by Jjagg** [comment] 2018-12-22 01:54
@briguyjm if you need some help figuring it out, I recommend posting on the forum (with some more information so people can actually help): http://community.monogame.net

**Comment by cra0zy** [comment] 2018-12-22 16:00
The templates generated by MonoDevelop cannot be used because once generated MonoDevelop incorrectly modifies the .csproj file causing it to be invalid.

**Comment by risooonho** [comment] 2019-12-15 19:32
http://community.monogame.net/t/building-directory-contains-space/11230

Solution:
This is an old topic but I do have a trick that works if anyone still needs to know.

When starting a new solution - uncheck "[] Create project directory within the solution directory" (don't really need it anyway) and you may notice a red X beside "MyProjectName.Desktop" (for example) that says "invalid configuration" when you hover over the X.
1) Right click on it
2) Tools >> Edit
3) Ctrl-H (replace ALL) "Any CPU" with "AnyCPU" [no space]
4) File >> Save, Clean All, rebuild - should work.
