### ISSUE TITLE
[3.3] OpenTK crashes if you exit on windows without calling dispose on textures

### ISSUE THREAD

**Issue by Thraka** [MonoGame/MonoGame#3749] opened 2015-04-21 18:21 UTC
I don't use the content pipeline and I just load textures by hand using `Texture2D.FromStream` or `new Texture2D`. With 3.2 I had no problems. When I upgraded to 3.3 I suddenly get this exception from OpenTK when I close the game window:

```
An unhandled exception of type 'OpenTK.Graphics.GraphicsContextException' occurred in OpenTK.dll

Additional information: Failed to make context 131072 current. Error: 6
```

**Comment by totallyeviljake** [comment] 2015-04-23 18:43
+1 this happens every time I close an OpenGL project with MonoGame. It's in the finalizer of the GrahpicsResource class. The MainWindow is not valid when the finalizer is invoked, so the RunOnUIThread calls fail because they use the window context for thread management.

This happened last year and @thefiddler was going to look at it. I believe a change was made to address this issue, so this may be a regression problem.

**Comment by paewie** [comment] 2015-04-24 16:48
+1 and exactly the same problem on other platforms (at least Linux) as I already stated in addition to #3540. So this is (sadly) not Windows-only, even if Linux seems to be much more stable (very, very rare).

**Comment by WardBenjamin** [comment] 2015-07-04 02:24
This is definitely still a problem. I create a single pixel texture for drawing lines, and this error seems to be happening still. @tomspilman @thefiddler do we have any news on this?

**Comment by ZackCDLVI** [comment] 2015-07-16 18:28
This happens in a project using 3.4 that contribute too. According to the developer...,
> Garbage collector causes random crashes when trying to release textures...

**Comment by Scellow** [comment] 2015-08-15 13:20
Same here Windows OpenGL

Windows 10
MonoGame 3.4

**Comment by cra0zy** [comment] 2017-04-29 15:09
@tomspilman This got fixed with the SDL switch.

**Closed** 2017-04-30 01:38 UTC
Labels: OpenGL, OpenTK, Windows
