### ISSUE TITLE
Monogame 3.6 Pipeline tool does not work with Visual Studio 2017

### ISSUE THREAD

**Issue by diliupg** [MonoGame/MonoGame#5889] opened 2017-08-22 21:01 UTC
This is a problem which has been going on for some time with no solution still. All versions of monogame give the same error of freetype file

**Comment by cra0zy** [comment] 2017-08-22 21:06
Install http://www.microsoft.com/en-NZ/download/details.aspx?id=30679, it should solve it.

Also this should be a duplicate of: #3556

**Comment by diliupg** [comment] 2017-12-29 17:43
Thanks. All's well now.

**Comment by cra0zy** [comment] 2018-03-17 11:07
Closing since this is a duplicate of: #3556

**Closed by cra0zy** 2018-03-17 11:07 UTC
