### ISSUE TITLE
Weird SpriteBatch.Draw performance cliff

### ISSUE THREAD

**Issue by bwiklund** [MonoGame/MonoGame#7910] opened 2022-08-15 02:38 UTC
I found a very strange bug where my game goes from 5% cpu utilization to 15% (3x slower) at a very exact number of calls to `SpriteBatch.Draw`: 43.

`<=42` calls makes no change to CPU usage
`>=43` spikes it up 3x cpu usage (but increasing the number of calls to like, hundreds, doesn't make it any worse)

I'm using SpriteBatch, in Deferred mode, and using it in this order:

.Begin() 
   .Draw(...) for all the characters of a pixel font.
.End()

More details:
- I'm using a single global spritebatch instance, and (incidentally) 7 Begin/End passes per frame. (globally)
- The sprites are characters in a pixel font, are all from a single texture atlas, using src/dest rects to pick out characters
- Removing the final call to .Draw() for each character fixes CPU usage, so I'm confident it's not the work I'm doing to set up each character.
- Explicitly forcing a Begin/End around each set of text sprites makes no difference.
- The game renders about ~700 sprites per frame, so i wouldn't expect 43 more calls to do this.
- Present in debug and release

Also: changing the global spritebatcher to ImmediateMode actually improves performance, which goes against my intuition for how sprite batching should work with hundreds of sprites per frame.

ALSO: adding an extra `Draw` call, with a different texture (to force it to flush?) between _every single character_ makes it run faster. That doesn't seem right?

- MonoGame 3.8.0 (also present on 3.8.1.303 hotfix)
- Windows
- DesktopGL

**Comment by bwiklund** [comment] 2022-08-15 02:44
Digging around, SpriteBatcher's `maxBatchSize` is 42 (256/6), so this seems like a really strong lead.
https://github.com/MonoGame/MonoGame/blob/a9e5ae6befc40d7c86320ffdcfcd9d9b66f786a8/MonoGame.Framework/Graphics/SpriteBatcher.cs#L30

This is indeed probably the only place in the game's code where I draw >42 sprites from the same texture in a row. I'm still at a loss for how exceeding that limit one time per frame to draw my text would have such a huge hit to performance, tho?

**Comment by MrGrak** [comment] 2022-08-15 03:20
256 != 42

**Comment by bwiklund** [comment] 2022-08-15 03:32
256/6 verts per sprite = 42.666

Actually it looks like the 256 there is supposed to refer to items, not vertexes. And the `private int InitialVertexArraySize = 256` is not even referenced anywhere, is that dead code?

Either way I doubt it's just a coincidence that performance runs of a cliff at exactly 256/6 + 1 sprites.

**Comment by MrGrak** [comment] 2022-08-15 03:33
> Actually it looks like the 256 there is supposed to refer to items, not vertexes.
Correct

**Comment by lithiumtoast** [comment] 2022-08-15 03:56
It's unclear but looking at the code there is no immediate clue that the problem is `SpriteBatch`.

Options:

- Free. Use `dotnet trace --format=Speedscope` and upload the resulting profile file to https://www.speedscope.app. Compare and contrast to < 42 and > 42.

- Free trial, paid otherwise. Use JetBrains dotTrace app and profile < 42 and > 42.

**Comment by mrhelmut** [comment] 2022-08-15 08:01
It may simply happen that this threshold hits a caching size limit somewhere. It could be anything, from CPU caching, to .NET caching, to GPU driver caching, to your code using a collection that triggers a cache. I don't think that it is related to MonoGame itself, and I wouldn't worry much about it either.

**Comment by tomspilman** [comment] 2022-08-15 18:32
I vaguely remember we put some limits on the initial size of `SpriteBatch` because people that used multiple of them in low memory situations (older mobile titles) had out of memory issues.

For this reason we also added a capacity argument to the `SpriteBatch` constructor:

https://docs.monogame.net/api/Microsoft.Xna.Framework.Graphics.SpriteBatch.html#Microsoft_Xna_Framework_Graphics_SpriteBatch__ctor_Microsoft_Xna_Framework_Graphics_GraphicsDevice_System_Int32_

That said... most mobile devices are 1GB or more in memory size.  We could consider increasing the default size of `SpriteBatch`.

**Comment by mrhelmut** [comment] 2022-09-18 22:15
Can't confirm this as a bug, so I'll be closing this for the time being. Feel free to comment with more insights.

**Closed by mrhelmut** 2022-09-18 22:15 UTC
