### ISSUE TITLE
Unknown argument "workingDir" when loading mgcb with Pipeline Tool

### ISSUE THREAD

**Issue by Vega-KH** [MonoGame/MonoGame#6074] opened 2017-11-24 02:09 UTC
On Windows 10, the pipeline tool can no longer open any mgcb files. When attempting to open, an error occurs stating that there was an unknown argument "workingDir."

This happens even when the pipeline tool is run with no command line arguments, and even when workingDir is not set in the mgcb file.

 #6056 appears to be the cause of the error. It did not appear in builds before this.

**Comment by MarcVador** [comment] 2017-11-24 09:00
Same problem here, on Win7 x64 and VS2017. 
It used to work cleanly with the build 1097.

**Comment by KonajuGames** [comment] 2017-11-24 09:02
We'll get this fixed today. It was most likely caused by a pull request
merge yesterday.

**Comment by KonajuGames** [comment] 2017-11-24 13:18
That change has been reverted until a better solution is worked out.

**Comment by Jjagg** [comment] 2017-11-24 13:24
Tagging @cra0zy

**Comment by KonajuGames** [comment] 2017-11-24 13:25
I re-opened the original issue.

**Comment by cra0zy** [comment] 2017-11-24 13:26
@KonajuGames my issue is completely separate thing from this one.

**Comment by cra0zy** [comment] 2017-11-24 13:28
btw. I'll look into this now, expect a PR shortly.

**Comment by cra0zy** [comment] 2017-11-24 13:55
#6075

**Comment by Jjagg** [comment] 2018-10-08 15:41
Fixed in #6076.

**Closed by Jjagg** 2018-10-08 15:41 UTC
